### ISSUE TITLE
pageLoadSampled documented as string

### ISSUE THREAD

**Issue by thenewguy** [elastic/apm-agent-rum-js#1004]
Please verify https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#page-load-sampled

Should it be a boolean? Docs say data should be a string.  Can you provide an example.

**Comment by vigneshshanmugam** [comment]
Good catch, it should be a boolean not a string. Would you like to open a PR?

**Comment by ikalkov** [comment]
I was confused by the documentation as well. Would be great to have it fixed!
