### ISSUE TITLE
Remove trailing forward slash from distributedTracingOrigins

### ISSUE THREAD

**Issue by antonselukh** [elastic/apm-agent-rum-js#1010]
If the items in `distributedTracingOrigins` are set with a trailing forward slash the correlation logic does not work and the traceparent header is not added to the requests.
The following example works:
`var apm = initApm({ ... distributedTracingOrigins: ['https://api.example.com'] })`
but this does not:
`var apm = initApm({ ... distributedTracingOrigins: ['https://api.example.com/'] })`

`traceparent` header is not added to the requests in the second case.

We should remove the trailing slash from the `distributedTracingOrigins`.

Related: #248

**Comment by vigneshshanmugam** [comment]
@antonselukh Problem is too specific here as we expect the users to pass the origin and not a regular URL. 

The agent already supports passing RegExp for distributed tracing origins which should work for the above case. You could do

```js
initApm({ distributedTracingOrigins: [/api.example.com/] })
```

**Comment by antonselukh** [comment]
Yes, it's mostly needed as a protection against stupid
Documentation change, or keeping this issue in the list would be enough for the next person to see what they did wrong.

Btw, i didn't know you can use regexp in this property. Thanks
