### ISSUE TITLE
Installation not working on new angular project.

### ISSUE THREAD

**Issue by mattiaspantzare** [elastic/apm-agent-rum-js#1026]
I created a new angular project with
`ng new apm-app`

Ann the I tried to add the apm package

`% npm install @elastic/apm-rum-angular --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: apm-app@0.0.0
npm ERR! Found: @angular/core@12.0.2
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=9.0.0 <12.0.0" from @elastic/apm-rum-angular@2.0.1
npm ERR! node_modules/@elastic/apm-rum-angular
npm ERR!   @elastic/apm-rum-angular@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/mattias/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mattias/.npm/_logs/2021-05-28T08_28_24_458Z-debug.log`

**Comment by vigneshshanmugam** [comment]
@mattiaspantzare `@elastic/apm-rum-angular` library is tested and works only from version 9 till 11, we have not tested in version 12 and not sure if the breaking changes affects us in any way. 

https://github.com/elastic/apm-agent-rum-js/blob/6c44e48974640933a976a6dba52f0e8f8096043a/packages/rum-angular/package.json#L37-L38

We would need to add tests and ensure if it works in version 12 and publish a new version. 

In the meanwhile, you can use the previous version of Angular(<12) and still use the APM library.

**Comment by mattiaspantzare** [comment]
The documentation should say 9 to 11, not 9 and up as it does now.

For the next update, maybe do the testing for angular 13 when the release candidates are released instead of waiting for a bug report?

**Comment by vigneshshanmugam** [comment]
> The documentation should say 9 to 11, not 9 and up as it does now.

Sure will fix that. Thanks for spotting it. 

Yeah we will do that. Thanks. Regarding Angular 12, we will add support ASAP.

**Comment by paulb-elastic** [comment]
https://github.com/elastic/apm-agent-rum-js/issues/1028 raised to track support for Angular 12
