### ISSUE TITLE
Add support for Angular 12

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/apm-agent-rum-js#1028]
ACs:
* Update the RUM Agent to work with Angular version 12
* Update the documentation to clarify the Agent is supported up to and including version 12

**Comment by vigneshshanmugam** [comment]
We can publish a new minor version while adding the support for Angular 12 by keeping the `enableIvy: false` in our `tsconfig`.This is backwards compatible and does not need to be in major version as applications can still rely on `ngcc` to build the libraries for View Engine compatibility. 

Going forward in the next major ^3.0, we can enable the `enableIvy: true, compilationMode: partial` to use the new library distribution mechanism for Ivy and drop support for view engine.  

Info - https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4

**Comment by vigneshshanmugam** [comment]
We have to move from webpack 4 -> webpack 5 to use the new ng build system in Angular 12.
