### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by ChrisTitos** [elastic/apm-agent-rum-js#1031]
Hi,

I was going to try out integrating this library with our react app, but it turns out it only supports React 16, while we are using 17. Are there plans of upgrading to this version?
Same with React Router, we use v5.

**Comment by FedeOmoto** [comment]
Same issue here.
We're using React 17 and React router 5, but because of the peer dependencies we can't install the RUM agent: https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-react/package.json#L47

Any ETA when is this going to be fixed?

**Comment by ChrisTitos** [comment]
Thanks @vigneshshanmugam . Any eta on when the new version will be released?

**Comment by GuidovdRiet** [comment]
Same issue here, would be appreciated if the new version is released soon.

**Comment by vigneshshanmugam** [comment]
Will do a release this week, Thanks for your patience.
