### ISSUE TITLE
load-testing-results cannot be ingested in Elasticsearch

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-rum-js#1037]
### What

The file generated with the load testing cannot be ingested in Elasticsearch fails with

```
Benchmarks: there was a response with an error. Review response {"took":5,"errors":true,"items":[{"index":{"_index":"benchmarks-rum-load-test","_type":"_doc","_id":"Ez647HkBI8xiny4xJ-_u","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}}}]}
````

File content can be seen in https://apm-ci.elastic.co/job/apm-agent-rum/job/apm-agent-rum-mbp/job/master/413/artifact/src/github.com/elastic/apm-agent-rum-js/apm-agent-load-testing-results.json/*view*/

### Logs

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/master/413/pipeline/2349#step-2505-log-1

Please let me know if you need further details

**Comment by vigneshshanmugam** [comment]
@v1v Thanks for the details. We can disable posting the `load-testing` results for the time being as we are not actively pursing the analysis åt the moment.
