### ISSUE TITLE
Add custom labels or context on specific error

### ISSUE THREAD

**Issue by seravifer** [elastic/apm-agent-rum-js#1049]
Hi.
Is there a way to add any kind of custom information (labels or custom context) when we catch an error?
I don't want that information to appear in another transactions or errors. I just want to add extra information to a bug caught and identified by me.
As I understand it, labels and custom context are global information.

**Comment by JonKrone** [comment]
👋  This was really helpful information for us! It took a while to find, though - ended up looking at official docs, googling, and searching Github Issues with a few different queries. Seems like a good candidate to add to the docs if this is an official feature.
