### ISSUE TITLE
does it work with Nativescript ?

### ISSUE THREAD

**Issue by udit2910** [elastic/apm-agent-rum-js#1052]
I have been trying to configure this module with nativescript (+angular). but i am not able to integrate it
does this module supports nativescript ? If it does then how should i implement it.
Thanks.

**Comment by vigneshshanmugam** [comment]
@udit2910 We don't have out of the box support for NativeScript at the moment. I am not sure if we will even work on supporting it in the future as it will be covered by our Mobile agents - https://github.com/elastic/apm-agent-ios
