### ISSUE TITLE
apmRequest is never invoked due to beforeSend being undefined

### ISSUE THREAD

**Issue by humiston** [elastic/apm-agent-rum-js#1054]
Upon running my application with a defined apmRequest function, I noticed that my apmRequest is never invoked. My configuration is as follows:

```
const apm = initApm({
  serviceName: 'my application',
  serverUrl: 'http://localhost:8200/',
  serviceVersion: '0.0.1',
  environment: 'development',
  apmRequest: (x) => {
    // debugger
    return true;
  }
});
```

Upon attempting to debug with the debugger statement uncommented, I noticed that I never reached this point. 

After some digging in the apm-rum-core code via https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-core/src/common/apm-server.js, I found that beforeSend was undefined:

```
  _makeHttpRequest(
    method,
    url,
    { timeout = 10000, payload, headers, beforeSend } = {}
  ) {
    // beforeSend is undefined
    return new Promise(function (resolve, reject) {...}) 
  }
```
After tracing this back, I found that the result object was being passed to _makeHttpRequest from the postJson method and that the result object did not contain a beforeSend property but did include others:

```
payload = Blob {size: 2168, type: ""}
headers = {Content-Type: "application/x-ndjson", Content-Encoding: "gzip"}
beforeSend = undefined
```
Debugging _postJson even further, I noticed that the armRequest variable was being set correctly and was defined as my config's apmRequest function. I also noticed that the promise returned from compressPayload was resolving which was leading to  this._makeHttpRequest being invoked using the result object:

```
 _postJson(endPoint, payload) {
    const headers = {
      'Content-Type': 'application/x-ndjson'
    }
    // this is defined
    const apmRequest = this._configService.get('apmRequest')
    return compressPayload(payload, headers)
      .catch(error => {
        if (__DEV__) {
          this._loggingService.debug(
            'Compressing the payload using CompressionStream API failed',
            error.message
          )
        }
        return { payload, headers, beforeSend: apmRequest }
      })
      .then(result => 
         // getting here and result.beforeSend is undefined, why???
         this._makeHttpRequest('POST', endPoint, result)
      )
      .then(({ responseText }) => responseText)
  }
```
This would lead me to believe that I should have a defined beforeSend function via the result object but this is not the case. compressPayload instead gives me a result object without a defined beforeSend property. As a result, apmRequest is never being invoked. 

By any chance could this be due my apm config object or is this unintentional?

**Comment by vigneshshanmugam** [comment]
Thanks @humiston for raising the issue and also providing tons of details, Seems like a bug and we are not passing the correct parameters to the compressPayload method. Will do a fix and update here.
