### ISSUE TITLE
XMLHttpRequests don't seem to be instrumented

### ISSUE THREAD

**Issue by ChrisTitos** [elastic/apm-agent-rum-js#1056]
Hi, I'm trying out RUM in our frontend app, but I'm running into some trouble with XMLHttpRequests.
They don't seem to generate any spans.

Fetch calls seem to work fine. But our Ajax calls that are done via either axios, or jquery (in older parts of the app), don't seem to appear.

I checked the `xhr-patch.js` file of apm-core, and I noticed that if I execute the if statement in this line in the browser console:
```
/**
   * Handle if the XMLHttpRequest object is patched on the page
   */
  if (
    !XMLHttpRequestPrototype ||
    !XMLHttpRequestPrototype[ADD_EVENT_LISTENER_STR]
  ) {
    return
  }
```
It returns true. Which I guess would imply the rest of the code isn't executed. 

I've had this behavior in both Firefox and Chrome

**Comment by vigneshshanmugam** [comment]
@ChrisTitos Thanks for raising the issue, We have tests that are run on wide amount of browsers for both Fetch and XHR requests. So I am not sure if this is an edge case or browser global objects in the case of `XMLHttpRequest` is modified by any other libraries. 

Can you send a minimal repro code to test this?

**Comment by ChrisTitos** [comment]
Hmm, strange, I tried that snippet in the console for a couple of other libraries and indeed it seems to work there. I'll try to see if there could be some other libraries messing with this.

**Comment by ChrisTitos** [comment]
Ok I found the culprit. We were using the [pace.js](https://github.com/CodeByZach/pace) library, which [incorrectly extends the XMLHttpRequest](https://github.com/CodeByZach/pace/issues/261). So it's not elastic :)

Thanks.

**Comment by vigneshshanmugam** [comment]
Glad you figured out, Thanks 👍🏽
