### ISSUE TITLE
RUM failure in APM Integration Test Suite

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-rum-js#1057]
<img width="629" alt="Screen Shot 2021-07-16 at 1 21 01 PM" src="https://user-images.githubusercontent.com/111616/125940048-073bec9b-ef7f-4487-83c0-47d4a8f3bf9e.png">

Starting on July 16, we have started seeing [failures on the APM Integration Test suite related to RUM](https://apm-ci.elastic.co/job/apm-integration-tests/job/master/956/testReport/).

Could somebody please investigate this issue? Thanks.

**Comment by vigneshshanmugam** [comment]
@cachedout 

I did a change recently in the RUM agent that to add a new header to APM server requests that runs as part of Integration tests. 
We might need to add this header to the server config - https://github.com/elastic/apm-agent-rum-js/pull/1055/files#diff-b8cd439b02c2daaa54b6f62cdf87fce19b70de0e1dea956b7bf054e775dc0f1dR46

If that does not sound good, I can revert that change and do something else for testing a feature relevant to that. Let me know your thoughts.

**Comment by cachedout** [comment]
@vigneshshanmugam Thanks. We've got this fix in here: https://github.com/elastic/apm-integration-testing/pull/1213
