### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by danilaplee** [elastic/apm-agent-rum-js#1058]
does this work with Vue 3? if i try like in the example i get an error
```
cannot read property use of undefined
```

**Comment by littlejon85** [comment]
No. The rum-vue package doesn't support Vue 3. If there's interest I can open PR and create rum-vue3 package for this purpose.

**Comment by alexbode** [comment]
+1 for rum-vue3

**Comment by AlexanderYW** [comment]
+1 for rum-vue3

**Comment by vigneshshanmugam** [comment]
@littlejon85 Do you want to add a PR to the `@elastic/apm-rum-vue` package? We can release a major that supports Vue 3

**Comment by littlejon85** [comment]
I can add it when I come back from vacation in about a week or two. Or anyone else can do it meanwhile. The conversion is very easy and takes about 10 minutes of work (plus docs and tests).
