### ISSUE TITLE
Failing APM Integration tests on 6.x branch caused by RUM Agent

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-rum-js#1063]
We are seeing the [6.x branch of the APM Integration tests fail](https://apm-ci.elastic.co/job/apm-integration-test-downstream/job/6.x/) because of [failures which appear to related to the RUM Agent](https://apm-ci.elastic.co/job/apm-integration-test-downstream/job/6.x/4386/). 

Could somebody please investigate these errors? It doesn't appear as if we'll have passing integration tests for the 6.x branch until these are resolved. Thanks!

**Comment by vigneshshanmugam** [comment]
RUM agent which is currently at `5.x` only supports stack >7.x versions, I am not sure if its worth even investigating these failures. I would skip and remove them from the pipeline. 

https://www.elastic.co/guide/en/apm/get-started/7.13/agent-server-compatibility.html#agent-server-compatibility

**Comment by cachedout** [comment]
Thanks for the response, @vigneshshanmugam 

Unfortunately, I think we're seeing these fail in other places as well. For example, we also [run APM Integration Tests in Elastic Cloud](https://apm-ci.elastic.co/job/apm-it-ec/job/master/) and these [same tests are failing against 7.13.4 stack](https://apm-ci.elastic.co/job/apm-it-ec/job/master/382/testReport/junit/tests.agent/test_rum/Tests_On_Elastic_Cloud___Matrix___STACK_VERSION____7_13_4____Run_ITs___Test_RUM___test_rum/).

Since you previously said that the 5.x agent [should support stack versions > 7.x](https://github.com/elastic/apm-agent-rum-js/issues/1063#issuecomment-889610758), should these failures be investigated?

**Comment by vigneshshanmugam** [comment]
We added a change recently to enable custom headers in the APM server - https://github.com/elastic/apm-agent-rum-js/blob/7ae7e395fc5cb45252b1fa92c6ef8675e98e0249/dev-utils/docker-compose.yml#L46

Do you think this could have triggered the test failures? There are no other major changes that could cause these failures and the errors are also not verbose.

**Comment by cachedout** [comment]
@vigneshshanmugam Yes, that looks quite likely. The commit you mention looks like it went in on July 15 and the APM ITs for the RUM Agent started failing consistently the next day.

**Comment by vigneshshanmugam** [comment]
@cachedout Do you see the issue still? - Ivan fixed it here - https://github.com/elastic/apm-integration-testing/pull/1213/

**Comment by cachedout** [comment]
@vigneshshanmugam Yes, we've seen it fail [as recently as yesterday](https://apm-ci.elastic.co/job/apm-it-ec/job/master/383/testReport/junit/tests.agent/test_rum/Tests_On_Elastic_Cloud___Matrix___STACK_VERSION____7_13_4____Run_ITs___Test_RUM___test_rum/) in the Elastic Cloud tests.

The fix [that you mention](https://github.com/elastic/apm-integration-testing/pull/1213) from @kuisathaverat just applies to clusters which are deployed via Docker which are local to the Jenkins worker running them. 

However, for the [APM Integration Tests for Elastic Cloud](https://apm-ci.elastic.co/job/apm-it-ec/), I think we need to deploy that [same change](https://github.com/elastic/apm-integration-testing/pull/1213/files#diff-99db2e84ec0f1793d9dea09793eb615b3cb0a9c8ec662380acdf530414493ae3R718) to Elastic Cloud.

The process of creating a cluster for APM ITs in EC is initiated [through a call to the Observability Test Environments set of Ansible scripts](https://github.com/elastic/observability-test-environments/blob/master/ansible/Makefile#L85). 

I think I'll need to do some digging in those script to try to find the right place to modify the configuration that we pass to an APM Server, but at the same time, I'm not even totally sure that this is _possible_ to set `apm-server.rum.allow_headers=["x-custom-header"]` in an APM Server instance in EC. For that reason, I'm going to ping @AlexP-Elastic here to ask if he might be able to verify this for us.

**Comment by vigneshshanmugam** [comment]
Thanks for the details @cachedout, If it's not possible we can revert that change in the RUM e2e tests as it does not do any harm for the RUM agent in general.

**Comment by vigneshshanmugam** [comment]
Fixed by https://github.com/elastic/apm-integration-testing/pull/1244
