### ISSUE TITLE
RUM for Angular: session is missing from  AgentConfigOptions

### ISSUE THREAD

**Issue by phkavitha** [elastic/apm-agent-rum-js#1066]
Hi,

As per the release notes of RUM v5.x, the session in transactions are available but when I try to enable it for an Angular 11.x webapp, I see that the property "session" is not defined in AgentConfigOptions. Am I missing something?

Angular-RUM
https://github.com/elastic/apm-agent-rum-js/blob/5988ad35d1553d3414dfce7ec6975f8f399f0d7e/packages/rum/src/index.d.ts#L27

session being used in other general unit tests: https://github.com/vigneshshanmugam/apm-agent-js-base/blob/86ba9f867c8029f87da00c4168ad3b846b0f6542/packages/rum/test/e2e/general-usecase/app.js#L42

**Comment by vigneshshanmugam** [comment]
@phkavitha 

It's an experimental feature and we are doing some internal testing to make it available for all customers in the future versions of the RUM agent. For now we will not expose it as its not surfaced in the UI anywhere and would only become available in future versions.
