### ISSUE TITLE
Provide a way to create Transactions separate from the current transaction

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#107]
Currently, the only way to create transactions is by calling `startTransaction` which would replace the current transaction with the new one. There should be a way to create a transaction and capture spans manually into it. There could be an issue with global APIs that we instrument (fetch, XHR), since the code that is creating a new transaction could be using those APIs (assuming the code is running in the same thread) and if so then the instrumentation captures that into the current transaction instead of the newly created one.

A possible solution is to use zones similar to https://github.com/angular/zone.js/

**Comment by vigneshshanmugam** [comment]
Addressed via #440
