### ISSUE TITLE
[Elastic APM] transaction(xxx, xxx, custom) was discarded! The page was hidden during the transaction!

### ISSUE THREAD

**Issue by sibijohn72** [elastic/apm-agent-rum-js#1075]
Hello,

We are trying to capture a long running custom transaction where the user might be inactive for a while, switch tabs/windows etc. We could not see these logs on kibana. so we turned on the debug log level and in such cases we can see that the transaction gets discarded with the message '[Elastic APM] transaction(xxx, xxx, custom) was discarded! The page was hidden during the transaction!'. How we can we disable this? Is there a config to control this behaviour?
We are using @elastic/apm-rum-angular: 2.0.0 and use chrome.

This is a repost of the issue i shared on the discussion forum. Unfortunately i did not get any response there.
https://discuss.elastic.co/t/elastic-apm-transaction-xxx-xxx-custom-was-discarded-the-page-was-hidden-during-the-transaction/282671

**Comment by vigneshshanmugam** [comment]
This is the intended behaviour and there is no config to disable this functionality. The reason being
- When the tab is backgrounded, timers becomes throttled by the browser and the performance metrics will be incorrect and would not be the accurate representation of what happens on the page. https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#policies_in_place_to_aid_background_page_performance

**Comment by sibijohn72** [comment]
I understand. Thank you for the information. I can see that this logic resides in transaction-service.js. would you be willing to accept a pr where we adapt it to do something like the following

```
if (!this._config.get('shouldCaptureUnreliableTransactions') && lastHiddenStart >= tr._start) {
          if (__DEV__) {
            this._logger.debug(
              `transaction(${tr.id}, ${name}, ${type}) was discarded! The page was hidden during the transaction!`
            )
          }
          return
        }
```

the default value for shouldCaptureUnreliableTransactions would be false so it would not affect any existing use case. we could also narrow it down to transaction type 'custom'.

**Comment by sibijohn72** [comment]
and of course this is just a gist. i am sure that there is a lot more to do. i just want to pitch the idea with this snip :)

**Comment by vigneshshanmugam** [comment]
Not really, We had a config for such use cases and moved away from it as it does not make sense to send transaction which is totally not accurate. It's better to focus on the important metrics than on the wrong metrics. Most of the front end RUM libraries follows this approach, so would stick to the existing approach on this one.

**Comment by sibijohn72** [comment]
i understand. thank you. closing the issue now.
