### ISSUE TITLE
Angular apply active option without restarting application

### ISSUE THREAD

**Issue by korser1** [elastic/apm-agent-rum-js#1083]
@elastic/apm-rum-angular  -
ApmService.init(config) accepts config with "active" property and returns ApmBase object.

If then apm.config with active = true/false is called to on/off apm service, it has no affect

**Comment by vigneshshanmugam** [comment]
Once the Agent becomes active, you cant change it back. Active only works during the initialization time, it does not support runtime modifications. You can use instrument flag to have more controls - https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#instrument
