### ISSUE TITLE
Angular implementation showing CommonJS warnings

### ISSUE THREAD

**Issue by eriktiekstra** [elastic/apm-agent-rum-js#1084]
Hi!

We're trying to implement the `@elastic/apm-rum-angular` package in our product, but we're getting a few console warnings from Angular regarding this package. 

```
/node_modules/@elastic/apm-rum-core/dist/es/opentracing/span.js depends on 'opentracing/lib/span'. CommonJS or AMD dependencies can cause optimization bailouts.

/node_modules/@elastic/apm-rum-core/dist/es/opentracing/tracer.js depends on 'opentracing/lib/tracer'. CommonJS or AMD dependencies can cause optimization bailouts.

/node_modules/@elastic/apm-rum-core/dist/es/error-logging/stack-trace.js depends on 'error-stack-parser'. CommonJS or AMD dependencies can cause optimization bailouts.

```

I know that we can ignore those warnings as stated [here](https://angular.io/guide/build#configuring-commonjs-dependencies) but it is recommended to avoid CommonJS modules. 

Are you aware of this issue and are there any plans on fixing this? 

Edit: 
We're using v2.1.1

**Comment by swseverance** [comment]
I am seeing this behavior as well

**Comment by devcorpio** [comment]
Hello!

Currently, the packages [opentracing](https://github.com/opentracing/opentracing-javascript/blob/master/tsconfig.json) and [error-stack-parse](https://github.com/stacktracejs/error-stack-parser/blob/master/dist/error-stack-parser.js) packages are being distributed in Common.js and UMD respectively.

**Comment by ringo-anva** [comment]
Hello we get:
commonJS or AMD dependencies can cause optimization bailouts.
on these 4:
- @elastic/apm-rum-core/dist/es/opentracing/tracer.js depends on 'opentracing/lib/constants'.
- dist/es/error-logging/error-logging.js depends on 'error-stack-parser'. 
- dist/es/opentracing/tracer.js depends on 'opentracing/lib/span'.
- dist/es/opentracing/tracer.js depends on 'opentracing/lib/tracer'. 

(CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies)

We using:
    "@elastic/apm-rum-angular": "3.0.3",

This could make using the product a showstopper.

How can this be solved ?

Cheers,
Ringo.
