### ISSUE TITLE
Allow custom user-interaction transaction names through custom data-attribute

### ISSUE THREAD

**Issue by David-Development** [elastic/apm-agent-rum-js#1091]
# Problem

Right now the transaction name for `user-interaction` can be modified through the html `name` attribute (See: https://github.com/elastic/apm-agent-rum-js/issues/496#issuecomment-641956136). 

However that attribute is not applicable to all HTML elements (see https://www.w3schools.com/tags/att_name.asp) - therefore e.g. Angular will throw some exceptions if you try to bind a variable to the `name` attribute of a `div` element. 

# Proposal

It'd be even better to use a custom attribute that you can use to fully control the name of the transaction (e.g. `data-rum-name`).

I checked the source code and it looks like the only change that'd be required is to check for the custom attribute and if it doesn't exist fall back to the existing logic: 

```js
// use custom html attribute 'data-rum-name' - otherwise fall back to "tagname" + "name"-Attribute
const transactionName = target.dataset.rumName ? target.dataset.rumName : `${tagName}${additionalInfo}`;
...
const tr = transactionService.startTransaction(
  `Click - ${transactionName}`,
  USER_INTERACTION,
  {
   ...
```

Ref: https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-core/src/performance-monitoring/performance-monitoring.js

**Comment by vigneshshanmugam** [comment]
@David-Development Sounds good, Do you mind opening a PR to add the support? We could use `data-transaction-name` or use the `name` attribute.
