### ISSUE TITLE
Angular implementation showing Error

### ISSUE THREAD

**Issue by khaledayed** [elastic/apm-agent-rum-js#1115]
Hey,
I'm trying to implement the `@elastic/apm-rum-angular` package, but I'm getting a few console warnings from Angular regarding this package.

`ERROR in node_modules/@elastic/apm-rum-angular/apm.service.d.ts:28:13 - error TS1005: '=' expected.
28 import type import * as ɵngcc0 from '@angular/core';          
node_modules/@elastic/apm-rum-angular/apm.service.d.ts:29:29 - error TS1005: ';' expected
29 { AgentConfigOptions } from '@elastic/apm-rum';`

I'm using `v2.1.1`
My ecosystem: 
` @angular/core v~9.0.6,`
`typescript Version 3.6.4`
`node v16.13.0`
`npm v8.1.0`

**Comment by devcorpio** [comment]
Hi @khaledayed,

The error is caused for the typescript version. The  @elastic/apm-rum-angular 2.x uses the keyword `import type ...`.

`import type` is supported only from 3.8.x onwards. We will have a look at this and will let you know. Thanks for bringing this to our notice.

Meanwhile a possible workaround is to upgrade @angular/core to the version v9.1.x. That [version](https://stackoverflow.com/a/57216166) uses typescript 3.8.x as a dependency.
