### ISSUE TITLE
Route timing calculation 

### ISSUE THREAD

**Issue by sundarv85** [elastic/apm-agent-rum-js#1116]
Hello,

We have been getting correct route timing in our SPA app. Recently we started using [clarity](https://clarity.microsoft.com/) in our project and with this change, what we are observing is, most of the times the clarity XHR calls is also taken into the route time calculation (which is not correct, as our route change does not depend on this XHR request being sent out). Because of this our route timing values are now showing higher time.

Any suggestions on how to fix this?

**Comment by vigneshshanmugam** [comment]
@sundarv85 

We don't have a configuration to exclude spans from the transactions as we want to capture all the activity associated with SPA navigations or hard reloads. But you could remove the reported span in the transaction end event.

```js
apm.observe('transaction:end', function (transaction) {
  if (transaction.type === 'route-change') {
   // Filter out the clarity calls
    transaction.spans = transaction.spans.filter(span => span.name !== "Clarity XHR")
  }
})
```

Once the span is removed, the agent would adjust the transaction duration based on the existing spans. Please do let us know if you need anything else.

**Comment by sundarv85** [comment]
Thanks @vigneshshanmugam 

I tried this. When I add this, this sub-span `Clarity XHR` is indeed ignored from being sent in the final route-change. However, the route-change time still includes this Clarity XHR sending time. I assume that means the ignore part of `apm.observer` happens after the route timing calculation has been calculated.

> Once the span is removed, the agent would adjust the transaction duration based on the existing spans. Please do let us know if you need anything else.

It seems it does not adjust the transaction time based on the existing spans.

**Comment by devcorpio** [comment]
@sundarv85 

We have been checking the scenario you described and yes the ```apm.observe('transaction:end'``` event is triggered when the transaction finishes. That's why the timing calculation is not being adjusted as you would expect.

We will discuss about the situation you are describing and we will let you know

**Comment by vigneshshanmugam** [comment]
I had a quick look, seems like I was wrong, We adjust the transaction timing before firing the `transcation:end` event 

Details - https://github.com/elastic/apm-agent-rum-js/blob/124fb47625b0f59ce3563690a7053a70c03f056d/packages/rum-core/src/performance-monitoring/transaction-service.js#L325-L329

We could add a configuration to ignore Spans from getting captured as part of all transactions. This could behave same as `ignoreTransactions` configuration. WDYT?

**Comment by devcorpio** [comment]
Yes, it seems a thing that we could do what you are saying, things that I had in mind were:

- new configuration like the one that you are proposing (filtering out transactions with a particular name for instance)
- add a new event available to observe such as `apm.observe('transaction:ending'` and then do the needed logic, although I'm not fan of this

For me the way to go would be the configuration 👍

**Comment by devcorpio** [comment]
@sundarv85 this issue will be treated in this [one](https://github.com/elastic/apm-agent-rum-js/issues/1130) thanks for sharing this
