### ISSUE TITLE
Error with ApmVuePlugin

### ISSUE THREAD

**Issue by Soufian20** [elastic/apm-agent-rum-js#1122]
I try to use the APM Real User Monitoring JavaScript Agent  with Vue as how it is in https://www.elastic.co/guide/en/apm/agent/rum-js/master/vue-integration.html described.

 My steps: 
`(1) npm install --save @elastic/apm-rum-vue`
`(2) my main.js`
``` 
import { createApp } from 'vue'
import { ApmVuePlugin } from '@elastic/apm-rum-vue'
import App from './App.vue'
import router from './router'


createApp(App)
    .use(router)
    .use(ApmVuePlugin, {
        router,
        config: {
          serviceName: 'app-name',
          serverUrl: 'http://localhost:8200', //  apm server
          serviceVersion: ''
        }
      })
    .mount('#app')
```

Error in Browser console appears:
```
Uncaught TypeError: Cannot set properties of undefined (setting '$apm')
    at Object.install (webpack-internal:///./node_modules/@elastic/apm-rum-vue/dist/es/index.js:29)
    at Object.use (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3091)
    at eval (webpack-internal:///./src/main.js:22)
    at Module../src/main.js (app.js:1312)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:1337)
    at __webpack_require__ (app.js:849)
    at checkDeferredModules (app.js:46)
    at app.js:925
```
I can see also the error in my kibana apm dashboard
![image](https://user-images.githubusercontent.com/38558643/146450674-d735537a-7334-4c1a-8dd9-b1b3fa443083.png)

`node -v => v12.16.1`
`npm -v => 7.6.3`

my package.json
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@elastic/apm-rum-vue": "^1.3.2",
    "core-js": "^3.6.5",
    "elastic-apm-node": "^3.26.0",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "^4.5.12",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

**Comment by vigneshshanmugam** [comment]
@Soufian20 We have not published the @elastic/apm-rum-vue@2.x which should work with Vue 3 application.

**Comment by Soufian20** [comment]
sry my bad. Is there a release date for vue 3?

**Comment by PIXPOINT** [comment]
I have the same problem. The error is that when I execute `npm install --save @elastic/apm-rum-vue`, the current package is not installed. Version `1.3.2` is correct in `package.json`, but in the folder `node_modules\@elastic\apm-rum-vue` you can find the code
```js
install: function install(Vue, options) {
    var router = options.router,
    ...
```
which attempts the error, so it is only compatible with Vue 2.0. Problem with NPM Package?

**Comment by AlexanderYW** [comment]
@vigneshshanmugam when can we expect this to be released?

**Comment by vigneshshanmugam** [comment]
Doing a small test internally, will release it next week. Apologies for the delay here.

**Comment by AlexanderYW** [comment]
@elastic/apm-rum-vue@1.4.0 was released 9 days ago and includes Vue3 support for those of you who wasn't aware of it

Also changelog page isn't written yet, so there is no way of knowing without testing it :)

**Comment by vigneshshanmugam** [comment]
1.4.x was released by mistkae with support for Vue 3, I have deprecated the version in favor of `2.0.0`

For users of Vue 3, We have released @elastic/apm-rum-vue@2.x that supports it by default. 

Please refer to the docs on the usage - https://www.elastic.co/guide/en/apm/agent/rum-js/current/vue-integration.html#vue-integration. 

Thanks. Please do let us know if you run in to issues.
