### ISSUE TITLE
Inline scripts errors does not have any references.

### ISSUE THREAD

**Issue by tkiefer24** [elastic/apm-agent-rum-js#1140]
The following error on a page with (Chromium 97, I can see in the logs other browsers also affected):
![image](https://user-images.githubusercontent.com/86222048/149924520-a6d366c2-9f2b-4f6d-b57d-3550fdbef9c4.png)
is tracked as the following payload:
![image](https://user-images.githubusercontent.com/86222048/149925086-bc4aea06-20f3-4892-a29f-124fd6b577be.png)
I already tryed the error-stack-parser version 2.x to solve this issue, it does not work!
It would be good to see the filename and lineno property in the logged error message.
I hope someone can fix this.
Thanks,
Timo

**Comment by devcorpio** [comment]
Hi @tkiefer24,

After investigating I found out that the [error-stack-parser](https://github.com/stacktracejs/error-stack-parser/blob/master/error-stack-parser.js) might have a bug. 

```
        parse: function ErrorStackParser$$parse(error) {
            if (typeof error.stacktrace !== 'undefined' || typeof error['opera#sourceloc'] !== 'undefined') {
                return this.parseOpera(error);
            } else if (error.stack && error.stack.match(CHROME_IE_STACK_REGEXP)) {
                return this.parseV8OrIE(error);
            } else if (error.stack) {
                return this.parseFFOrSafari(error);
            } else {
                throw new Error('Cannot parse given Error object');
            }
        },

```

For instance:

- if the inline script error happens in Chrome, the logic executed by the library is ```parseFFOrSafari````
- if the inline script error happens in Firefox, the library throws an error and the agent is extracting the stack directly from the value of the ErrorEvent

It is something that we should handle in the agent. An example could be using the lineno,filename and colno as a fallback when creating the stackframe but is something that requires more investigation.

I will open an issue in error-stack-parser repo

Thanks for bringing this to our notice!

**Comment by tkiefer24** [comment]
@devcorpio mh.. to me it looks more than that the error-stack-parser only got the `error` property from the `ErrorEvent`, so it has not enough data that and could not extract `filename` and `lineno` information.

**Comment by devcorpio** [comment]
Hi @tkiefer24,

The [release](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/release-notes-5.x.html#release-notes-5.12.0) with the fix is now available

Cheers,
Alberto
