### ISSUE TITLE
the User-centric Metrics "Largest contentful paint (LCP)" is not correct

### ISSUE THREAD

**Issue by rainydayDY** [elastic/apm-agent-rum-js#1162]
I have a question that page-load trigger too early，if my website render too lower，the 'largest-contentful-paint' doesn't trigger, or only trigger once, but the page-load trigger, the 'largest-contentful-paint' time will not correct
`const sendPageLoadMetrics = () => { // to make sure PerformanceTiming.loadEventEnd has a value setTimeout(() => tr.removeTask(PAGE_LOAD)) }`
There's something wrong with that logic

**Comment by devcorpio** [comment]
Hi @rainydayDY,

Thanks for contacting us!

I have a couple questions about **"Largest contentful paint (LCP)" is not correct**

1. Do you mean that the LCP value is not calculated? (so no LCP entry)
2. Or do you mean that the calculated time should be different than the one being calculated?

I have a couple questions related to agent and environment:

1. What version of the RUM agent are you using?
2. Could you share with us the webpage you are debugging?


--

On the other hand, I have reproduced a case where the LCP is not being reported by the RUM agent:

If the largest content of a page is an image there are times where we are **not** reporting LCP. This particular case happens regardless of how fast the page-load triggers. And as you are mentioning seems related to the logic that you are pointing out. 
It seems we stop the performance observer from receiving any performance entry before getting the LCP. It requires further investigation.

Is this particular case related to the one you are bringing to us?

**Comment by rainydayDY** [comment]
Hi, devcorpio,
Thanks for your reply！
**（_Note: github can't upload pictures, so I posted the picture link_）**
First of all, I don't think the case you mentioned is the same as what I said, but I'm not too sure，Because, when I watched discovery on kibana, 0.06% of pageload requests were reported to LCP；

【https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/90611a9caf0d4f8e976b108968c238e3~tplv-k3u1fbpfcp-watermark.image?】
【https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/1c82f471469942cebfc8493bd5b28221~tplv-k3u1fbpfcp-watermark.image?】

The uncertain point is that our page looks like the following, there are pictures in it, and the background image can be said to be the largest part of the current page；

【https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/1997f0f66f3745f88ae47e7220f54b6b~tplv-k3u1fbpfcp-watermark.image?】

Also, what I've seen is that both lcp and fcp are not reporting at the same time；
【https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/af8d774fa59b414b85772968b5d6bf64~tplv-k3u1fbpfcp-watermark.image?】
【https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f7a543c4c50e4dd4801abe80998d62bf~tplv-k3u1fbpfcp-watermark.image?】

Answer the question "Largest contentful paint (LCP)" is not correct

1. Pageload ends when LCP has no entry on some devices
2. Some devices have LCP entry, but the timing of the calculation is wrong
3. In the above two cases, chrome is greater than 77, and LCP can be obtained

【https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/3e02eb4bffe346a48fc901b328369c7b~tplv-k3u1fbpfcp-watermark.image?】

Answer the question “agent and environment”

1. @elastic/apm-rum: "5.9.1"
2. @elastic/apm-rum-core: "5.12.1"
3. Sampling Rate：1
4. Page：Our page is embedded in webview, you should not be able to open it, but it doesn't matter, I think this situation can be reproduced in many pages

It is recommended to use a mobile phone to test when testing, it will be more accurate, I will provide some version numbers below

"Mozilla/5.0 (Linux; Android 10; M2010J19SC Build/QKQ1.200830.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.101 Mobile Safari/537.36 (mimarket; 40009999; 2083)"
'Mozilla/5.0 (Linux; Android 8.1.0; MI MAX 3 Build/OPM1.171019.019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.87 Mobile Safari/537.36 (mimarket; 40004319; 2083)'

**Comment by devcorpio** [comment]
Hi @rainydayDY ,

Thanks for all the details, I really appreciate it how detailed your response is

It is an case that will require further investigation

Thanks,
Alberto

**Comment by rainydayDY** [comment]
Hi  Alberto：
May I ask when this bug will be fixed? What do you think of this bug？
Looking forward to your reply
Thanks, my name is DongYu，董雨

**Comment by devcorpio** [comment]
Hi DongYu,

We are about to start working on this. I'll let you know once the PR is created.

Thanks,
Alberto
