### ISSUE TITLE
Need help intrumenting routes in React

### ISSUE THREAD

**Issue by p-l-l** [elastic/apm-agent-rum-js#1163]
I would like to instrument routes in my React application using CRA (v5).
I have been checking on the [documentation](https://www.elastic.co/guide/en/apm/agent/rum-js/master/react-integration.html) and had some issues.

1. It is not possible to use the ApmRoute with `react-router-dom@6.0.0`  as it throws `Uncaught Error: [ApmRoute] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>`

2. I have tried using withTransaction on the components that are used as the `element` of the Route instead,
but it does not work unless the component is lazy-loaded.

Here is an example of component
```
import { withTransaction } from '@elastic/apm-rum-react';

function Test() {
  return (
    <div>
      This is a test
    </div>
  );
}

export default withTransaction('/test', 'route-change')(Test);
```

Here is an example of the routes
```
<Routes>
  <Route path='/test' element={<Test/>} />
</Routes>
```

The agent is initialized in the index file of my App

I noticed that when the application loads, the inner function of `withTransaction` in `get-with-transaction.js` of `elastic@apm-rum-react` gets called before rendering the Component, it doesnt seem to be triggered again the rendering the component after clicking a `<Link to="/test"/>` of `react-router-dom`, so the route-change event is never sent.

Am I using the HOC the wrong way with function component ?

**Comment by devcorpio** [comment]
Hi @p-l-l 

Thanks for reaching out

When it comes to  react-router-dom@6, it is true that reports an error, with v4 and v5 there are not problems. v6 adds a new component named `Routes` which is causing the mentioned error. Our instrumentation is not working as expected with that version of react-router, thanks for bringing this to our notice! cc: @vigneshshanmugam 

With regard to the usage of `withTransaction` I have been checking and the route-change transaction is created when clicking in the link. I'm going to add here the code that I used just in case helps you:

**index.js**
```
import { render } from "react-dom";
import {
  BrowserRouter,
  Routes,
  Route
} from "react-router-dom";
import App from "./App";
import { apmBase } from '@elastic/apm-rum'
import Expenses from "./routes/expenses";

apmBase.init({
  serviceName: 'apm-server-local-react',
  serverUrl: 'http://apm-server:8200',
  logLevel: "debug"
})

const rootElement = document.getElementById("root");
render(
  <BrowserRouter>
    <Routes>
      <Route path="/" element={<App />} />
      <Route path="expenses" element={<Expenses />} />
    </Routes>
  </BrowserRouter>,
  rootElement
);
```

**app.js**
```
import { Link } from "react-router-dom";

export default function App() {
  return (
    <div>
      <h1>Bookkeeper</h1>
      <nav
        style={{
          borderBottom: "solid 1px",
          paddingBottom: "1rem"
        }}
      >
        <Link to="/invoices">Invoices</Link> |{" "}
        <Link to="/expenses">Expenses</Link>
      </nav>
    </div>
  );
}
```

**expenses.jsx**
```
import { withTransaction } from "@elastic/apm-rum-react";

function Expenses() {
    return (
      <main style={{ padding: "1rem 0" }}>
        <h2>Expenses</h2>
      </main>
    );
  }

export default withTransaction('/expenses', 'route-change')(Expenses);
```

When clicking on expenses I can see how the transaction is redefined to `route-change`:

<img width="833" alt="Screenshot 2022-02-09 at 18 42 54" src="https://user-images.githubusercontent.com/15065076/153258769-d17572fa-18e7-480c-b22a-7421bcc62350.png">

For that test I used:

`Chrome 98`
`apm-rum 5.10.2`


Let me know if this helps you

Thanks,
Alberto

**Comment by devcorpio** [comment]
Hi @p-l-l ,

You may need a XHR/fetch within a route change to make the transaction to be finished and being sent to the server.

In this github [issue](https://github.com/elastic/apm-agent-rum-js/issues/1126#issuecomment-1002872536) there is a good explanation about how route-change detection works.

Additionally, it is important to bear in mind that transactions need to have at least one span, otherwise the agent discards them.

If you don't perform network requests within your route-change, another possible workaround it could be something like this:

```
import { apm } from "@elastic/apm-rum";
import { withTransaction } from "@elastic/apm-rum-react";
import { useEffect } from 'react';


function Expenses() {
    useEffect(() => {
      const tr = apm.getCurrentTransaction()
      if (tr && tr.type === 'route-change') {
       // bear in mind that a transaction needs at least one span
        const span = tr.startSpan('route change span')

        // transaction needs duration otherwise it will be discarded
        setTimeout(() => {
          span.end()
          tr.end()
        }, 1)
      }
    })


    return (
      <main style={{ padding: "1rem 0" }}>
        <h2>Expenses</h2>
      </main>
    );
  }

export default withTransaction('/expenses', 'route-change')(Expenses);

```


On the other hand, by default the dashboard only shows "page-load" transactions, you can filter them using the dropdown in the image below:

![dashboard-transaction-types](https://user-images.githubusercontent.com/15065076/153382531-fcd8a213-0052-42fc-874b-b7478a6b2f63.png)


Let me know if this helps you

Thanks,
Alberto

**Comment by p-l-l** [comment]
Thanks @devcorpio 
That was all the informations I needed to fully understand what was going on, much appreciated!
