### ISSUE TITLE
NextJS Client Side Issue

### ISSUE THREAD

**Issue by Tanagent** [elastic/apm-agent-rum-js#1185]
Hello,
I am trying to implement routing in my NextJS application and I'm following this guide
https://www.elastic.co/guide/en/apm/agent/rum-js/current/react-integration.html#_instrumenting_your_react_application

In my `_app.tsx` file, I have the agent initialized like so:

```
const apm = initApm({
  serviceName: "test-app",
  serverUrl: "http://localhost:3000",
});
```

Since NextJS applications don't use `react-router`, I decided to instrument the application with `withTransaction`.
In my `index.tsx` file, I have a functional component that returns the homepage. I have it exported

```
function HomePage() {
  return <div>...</div>;
}
```

```
export default withTransaction("HomePage", "component")(HomePage);
```

This is the error I am receiving

```
./node_modules/@elastic/apm-rum-react/dist/es/get-apm-route.js:8:0
Module not found: Can't resolve 'react-router-dom'
null
```

I did a search and I do not believe this is a duplicate of this issue since instrumenting routing wasn't discussed https://github.com/elastic/apm-agent-rum-js/issues/363

Any help will be appreciated. Thanks!

**Comment by devcorpio** [comment]
Hi @Tanagent,

Thanks for reaching out!

In the trace of the error I'm seeing a reference to `get-apm-route.js` which corresponds to `ApmRoute`. Are you still using `ApmRoute` in your code? Bear in mind that [ApmRoute](https://www.elastic.co/guide/en/apm/agent/rum-js/current/react-integration.html#_instrumenting_application_routes) only works with react-router (as you already mentioned)
<img width="745" alt="Screenshot 2022-03-14 at 13 11 41" src="https://user-images.githubusercontent.com/15065076/158169564-96b06fec-05fb-451a-b36f-3020b265e99b.png">

`withTransaction` doesn't have any dependency with `react-router-dom` so it shouldn't be related to the error. I just set an example and no error has been reported:

```
  // index.js
import Head from 'next/head'
import Link from 'next/link'
import { init as initApm } from '@elastic/apm-rum'

const apm = initApm({
  serviceName: "test-nextjs-app",
  serverUrl: "http://localhost:8200,
});

export default function Home() {
  return (
    <div className="container">
      // ... other code ...
      <main>
        <h1 className="title">
          Read{' '}
          <Link href="/posts/first-post">
            <a>this page!</a>
          </Link>
        </h1>
  )
}
```

```
import { withTransaction } from '@elastic/apm-rum-react'

function FirstPost() {
    return <h1>First Post</h1>
}

export default withTransaction("FirstPost", "component")(FirstPost);

```

If this doesn't help you, If would be very helpful if you can provide a test repo/example


Thanks,
Alberto

**Comment by Tanagent** [comment]
Hi @devcorpio ,
Thanks for replying! 

I made a dummy repo and was able to recreate the problem from scratch that you can look at
https://github.com/Tanagent/apm-example

When we do an `npm run build`, we get this error
![image](https://user-images.githubusercontent.com/8954587/158257867-51b9db09-d27b-4afa-a557-9c480143516f.png)

The docs that were provided says that we only need `react-router-dom` when we are `ApmRoute` but this error is requesting that we install `react-router-dom` even though we are just using `withTransaction`.

**Comment by devcorpio** [comment]
Hi @Tanagent,

`@elastic/apm-rum-react` has two [peer dependencies](https://classic.yarnpkg.com/en/docs/dependency-types#toc-peerdependencies), you can see them in its [package.json](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-react/package.json#L47)

 
<img width="270" alt="Screenshot 2022-03-15 at 11 48 32" src="https://user-images.githubusercontent.com/15065076/158361647-ee3f8313-cbb7-4227-9436-83dcb559bcb1.png">

## Possible ways to solve the issue you are facing:

- If your **npm** version is <= 6 (I'm assuming is your case) you will need to install the dependencies manually. 
- NPM released [version 7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/), and one of the features added is "Automatically installing peer dependencies" 🎉 .

I tested both approaches with your project and it worked properly. 

Let me know if this helps you

Thanks,
Alberto

**Comment by Tanagent** [comment]
@devcorpio Thanks! We were hoping to not have to do any of the two options but it works on our end!

**Comment by andrewdoro** [comment]
I wrote a custom component to handle page transitions in Next.js (no need for the elastic React integration), might help others:
``` tsx
import { useRouter } from 'next/router';
import React, { ReactNode, useEffect, useMemo } from 'react';
import { afterFrame } from '@elastic/apm-rum-core';
import { ApmBase } from '@elastic/apm-rum';

const ApmTransaction = ({ children, apm }: { children: ReactNode; apm: ApmBase }) => {
  const router = useRouter();

  const transaction = useMemo(() => {
    if (!apm) return;
    return apm.startTransaction(router.asPath, 'route-change', {
      managed: true,
      canReuse: true,
    });
  }, [apm, router.asPath]);

  useEffect(() => {
    if (!transaction) return;
    afterFrame(() => transaction && (transaction as any)?.detectFinish());
    return () => {
      /**
       * Incase the transaction is never ended, we check if the transaction
       * can be closed during unmount phase
       *
       * We call detectFinish instead of forcefully ending the transaction
       * since it could be a redirect route and we might prematurely close
       * the currently running transaction
       */
      transaction && (transaction as any)?.detectFinish();
    };
  }, [transaction]);

  return <>{children}</>;
};

export default ApmTransaction;


```


then I use it in `_app.tsx`
``` tsx
<ApmTransaction>
       <Component {...pageProps} />
</ApmTransaction>
```

**Comment by idahogurl** [comment]
@andrewdoro Won't `apm` always be `undefined`? Don't you need to pass it to `<ApmTransaction>`

**Comment by andrewdoro** [comment]
@

> @andrewdoro Won't `apm` always be `undefined`? Don't you need to pass it to `<ApmTransaction>`?

I forgot adding it in the snippet, but yes you have to pass it as a prop
