### ISSUE TITLE
Query string dropped in URL groups logged http-requests

### ISSUE THREAD

**Issue by andriijas** [elastic/apm-agent-rum-js#1189]
Im terrible sorry for using the issue tracker for support but I cant figure out the answer by the documentation for the elastic apm rum js client.

apm rum client version: 5.x (latest)
kibana server version: 6.x

Looking in the http-request tree generated from the automatic instrumentation, it seems like query string is disregarded - therefor all requests to TGSWS.cfc are grouped together  as if they where the same request while in reality its something like `TGSWS.cfc?method=foo` or `TGSWS.cfc?method=bar` (yes, this is a legacy cold fusion api 😅) 

![Screenshot 2022-03-23 at 10 15 09](https://user-images.githubusercontent.com/33141/159666258-6f752ce1-396d-472e-baf0-054c182da23e.png)

On the other hand other endpoints are not grouped together, which is probably the correct since they are unique, but I cant figure out a way to do some smart kind of masking - what would be the recommended way to get:

* v2/Clinics/.../Patients
* v1/Locale/.../Alphabet

Disable automatic http instrument and go complete manual? or keep automatic and add complete manual as well?
Or somehow modify the automatic with `addFilter`? 

![Screenshot 2022-03-23 at 10 11 03](https://user-images.githubusercontent.com/33141/159667449-43214f8d-1687-4b57-9255-a49581ef139f.png)

Thanks 🙏

**Comment by devcorpio** [comment]
Hi @andriijas,

Thanks for reaching out!

At this moment the agent it's not taking into account the query string and it's something that needs an enhancement.

When in comes to the second part of your question:

The way that we recommend to do the smart kind of masking is through [addFilter](https://www.elastic.co/guide/en/apm/agent/rum-js/current/agent-api.html#apm-add-filter).

For instance, I have a local application that requests to `http://localhost:3000/100/api_test `and  `http://localhost:3000/200/api_test`. At this moment I'm seeing both listed in Kibana:

<img width="588" alt="Screenshot 2022-03-23 at 16 22 49" src="https://user-images.githubusercontent.com/15065076/159734405-4752186f-4822-4c88-9f28-e083f5b8bebe.png">

Using addFilter with the following code (it's just an example):

```
                if (payload.transactions) {
                    payload.transactions.forEach(function (tr) {
                        // a way to to strip the id from the transaction name is:
                        if (tr.type === 'http-request') {
                            const [httpMethod, url] = tr.name.split(' ')
                            const urlObj = new URL(url)
                            const pathname = urlObj.pathname // e.g. /100/api_test
                            const id = pathname.split("/")[1]

                            tr.name = tr.name.replace(`/${id}`, '/...') // for instance...
                        }
                    })
                }

                return payload
            })
```
After that what see in Kibana is:

<img width="387" alt="Screenshot 2022-03-23 at 16 26 21" src="https://user-images.githubusercontent.com/15065076/159735196-e4f4c330-40d5-4858-930c-3829020b0e73.png">

It's also true that in **trace sample** of that transaction you will see the real url in the span info:

<img width="486" alt="Screenshot 2022-03-23 at 16 28 31" src="https://user-images.githubusercontent.com/15065076/159735604-4c347338-b875-463f-9e9a-9e16ed2c7c2e.png">

and

<img width="595" alt="Screenshot 2022-03-23 at 16 28 48" src="https://user-images.githubusercontent.com/15065076/159735661-f3973eff-db19-4c58-add7-3c4868fd6abd.png">

Let me know if this helps you

Thanks,
Alberto

**Comment by andriijas** [comment]
Thanks for the thorough reply! 

The `addFilter` solution is straight forward but it will require to "reverse engineer" more or less all api calls. Do you think its more straight forward to manually log transactions? Each api call in the app is wrapped in a function so it can be extended, something like this, silly example:

```
function fetchSomethingSomething(somethingId) {
const transaction = apm.startTransaction('fetchSomethingSomething', 'http-request')

const httpSpan = transaction.startSpan('GET ${apiEndpoint}/Clinics/.../Somesson', 'external.http')
 
  return api.Fetch(
    `${apiEndpoint}/Clinics/${somethingId}/Somesson`
  ) .then((resp) => {
   
    httpSpan.end()
    transaction.end()
  }).catch(err => {
      apm.captureError(err)
     throw err;
});
}

```

**Comment by devcorpio** [comment]
@andriijas, yes, in your case if everything is wrapped and easily located in your code then doing it manually is much cleaner. I totally agree with you 

In this [link](https://www.elastic.co/guide/en/apm/agent/rum-js/master/configuration.html#disable-instrumentations) you can see how disable **fetch** and **xhr** instrumentation

Thanks,
Alberto

**Comment by devcorpio** [comment]
Hi @andriijas,

There is an additional scenario(thanks @vigneshshanmugam for pointing it out) that it would be interesting for you to know: 

If a http request call causes the browser to load a new html portion (which includes resources such as css, etc) and you want to the agent to include timing information and spans about it in the transaction, you should create the transaction with the flag **managed** set to **true**.

More info about managed transactions here: https://www.elastic.co/guide/en/apm/agent/rum-js/master/custom-transactions.html#custom-managed-transactions

Thanks,
Alberto

**Comment by andriijas** [comment]
@devcorpio Thanks!

We went with just adding a filter and managed to get the results we want by petting the cat

There are two things it does. it masks id by regex detection and put the masked url as transaction name, but keeping the real full url as it is in the context.

I believe this lets us see a good overview of transactions on the frontpage in kibana, but while doing drill down we get the correct URLs if needed.

The second part is to extract method name from legacy urls that contains ?method= 
 and append it to the transaction name,  also here keeping the url as is 

It seems like it works like intended. What does the pros say?

Thanks 🙏 

```

/* Regex to masks urls.
 * Will omit trailing s - for example /Clinics/123
 * $1 = Clinics $2 = Clinic
 */
const urlFilterMatch = new RegExp(
  new RegExp(/(([a-zA-Z]+?)s?)\/[0-9]+/, "g"),
  "g"
);

const cleanName = (name: string): string =>
  name.replaceAll(urlFilterMatch, "$1/{$2Id}");

const apmRequestFilter: FilterFn = (payload: Payload) => {
  /* 
    For each error attached to the payload
    append the requestLog to the custom context
    This makes it possible in kibana to see the 
    30 latest request to the API the user made
    before an error occured
  */
  if (payload.errors) {
    payload.errors.forEach((error: PayloadError) => {
      error.context.custom.requestLog = requestLog.slice();
    });
  }

  /*
   * Mask urls
   * For example change /clinics/123 to /clinics/{clinicId}
   */
  if (payload.transactions) {
    payload.transactions.forEach(function (tr: PayloadTransaction) {
      tr.name = cleanName(tr.name);
      tr.spans.forEach(function (span: PayloadTransactionSpan) {
        span.name = cleanName(span.name);
        if (
          span.context &&
          span.context.http &&
          span.context.http.url.includes("legacy.cfc")
        ) {
          const url = new URL(span.context.http.url);
          const method = url.searchParams.get("method");
          if (method) {
            span.name = `${span.name}/${method}`;
          }
        }
      });
    });
  }
  return payload;
};
```

**Comment by devcorpio** [comment]
Glad to see that you have managed to make it work as expected. The solution is a good one. It's true that it relies on internals of transaction/span but there are not plans to change internals and even if we do that, we would have in mind these kind of solutions and announce the breaking changes properly.

So, all good from my side

**Comment by Truffula** [comment]
Hi! I've just run into the same issue (i.e. grouping of similar spans which are actually completely different queries) but with POST requests. It would be nice to have an option to disable grouping, e.g. by adding `groupSimilarSpans` to `TransactionOptions` (a boolean, or perhaps optionally a predicate function). If it defaulted to true, it wouldn't be a breaking change, and span names could still be adjusted at the filtering stage. That way it would be easy to keep the requests separate while also maintaining the benefits of the managed transactions (e.g. distributed traces that Just Work, applying to requests from different servers) — I guess this would also be an enhancement, but a relatively simple one.

Another option (albeit a breaking change) would be to avoid grouping spans matching distributed tracing origins.
