### ISSUE TITLE
Missing: Support for Vue's <script setup>

### ISSUE THREAD

**Issue by Lightwight** [elastic/apm-agent-rum-js#1194]
### **Versions**
VueApm-Plugin (RUM-Agent): ^2.0.1
Vue: ^3.0.0

### **Problem**
I am not able to use your fantastic Apm-Plugin inside a Vue3-<[script setup](https://vuejs.org/api/sfc-script-setup.html#script-setup)>-Component because of the missing [provide mechanism](https://vuejs.org/api/composition-api-dependency-injection.html#provide).
In order to make this possible the plugin itself needs to use the [inject mechanism](https://vuejs.org/guide/reusability/plugins.html#provide-inject-with-plugins):

### **Solution**
**APM-Plugin**
`export default {
  install: (app, options) => {
      const $apm = () => { ... };
      app.provide("$apm", $apm);
  }
};`

Then I can use it inside my **Setup-Template**
`<script setup>
import { inject } from "vue";
const $apm = inject("$apm");
</setup>`

Would be nice if you can implement the support for Vue3-Setup-Templates. 
Thanks 🙏

**Comment by devcorpio** [comment]
Hi @Lightwight,

Thank you for bringing this to our notice!

We will have this in mind when defining priorities. On the other hand, would you like to add a PR to the @elastic/apm-rum-vue package?

Thanks,
Alberto

**Comment by vigneshshanmugam** [comment]
@Lightwight Have you tried with the latest `@elastic/apm-rum-vue@2.x` package? the version you pointed out `1.4.0` does not have support for Vue3.

**Comment by Lightwight** [comment]
@vigneshshanmugam @devcorpio Sorry for the late response. It was my mistake. I updated the version to **^2.0.1** (also edited in the comment) with no effect. As @devcorpio asked i am gonna add a PR to the latest package.

Thank you guys for your time :)
