### ISSUE TITLE
e2e react flaky test related to user-interaction threshold

### ISSUE THREAD

**Issue by devcorpio** [elastic/apm-agent-rum-js#1196]
# Context

A while ago it was noticed that one of the [e2e test](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-react/test/e2e/with-router/general.e2e-spec.js#L68) of the react package was behaving flakily.

The degree of flakiness varied depending on where its execution was triggered, that is: locally or in the pipeline

Executing it locally tends to fail more than in the pipeline, although the two links below are an example of failures that took place in the pipeline: (there are more instances)

- https://apm-ci.elastic.co/job/apm-agent-rum/job/apm-agent-rum-mbp/job/main/28/execution/node/1513/log/
- https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/apm-agent-rum-mbp/pipelines/PR-1146/runs/19/nodes/1254/steps/1546/log/?start=0

To locate the error search for **'ManualComponent'** on the logs

## Why we didn't create the issue back then:

Back then there were two reasons that caused not to focus on this:

- the pipeline retries until 3 times, and **most of the time** the pipeline does not get stuck for this.
- we just came of updating all the [e2e dependencies](https://github.com/elastic/apm-agent-rum-js/pull/1118) and we decided that to spend more time on debugging something that was not blocking the pipeline was not the right investment of time

## Why we are creating the issue now:

- Because while working of the LCP [issue](https://github.com/elastic/apm-agent-rum-js/pull/1190) that test required changes too (adapt it to new logic).  Unfortunately, the was failing often and it was being a bit painful to figure out if the failure was coming for the change of logic or for the known flakiness.
- The reason behind the flakiness has been found 🎉 

## Why is the test flaky:

Context: the test is checking that if the react router loads a component lazily (dynamically) we are getting the proper spans

**The problem lies on timings:** 

The click transactions have a 300ms threshold, during that period among other things they can:

1. (this is the one to "blame") capture **resource** and user timing spans (non blocking spans,: e.g. the transaction will be finished even if there is a resource loading in progress).
2. capture interesting things such as xhr/fetch requests (blocking spans, meaning: transaction will not be finished until request is done)
3. Have their name and type redefined. E.g. a route-change happens after the click

When loading a lazy loaded component a JS file needs to be downloaded. Sometimes the duration of the file loading is greater than the transaction threshold. This is important for the test data because **instead of having one transaction with 3 spans** it has **two/three different transactions** and the spans shared between them, so the assertions fail.

## Beyond the flakiness

This is easily reproducible using the networking throttling:

Note: screenshots are from the test application we are using in the E2E

**without throttling:**

You will only see one event being sent

https://user-images.githubusercontent.com/15065076/161753183-70dc0ecc-9a12-4247-b7df-3891ded07b1d.mov

**with throttling:**

You will see **more than one event** being sent

https://user-images.githubusercontent.com/15065076/161753211-de754a11-39a1-4ac5-813a-3836a1694c38.mov

# Discuss

Changing the threshold from 300ms to 600ms makes the tests pass all the time. But I understand that we chose 300ms a while ago for particular reasons.  

And if we come back to the throttling thingy... probably we are not going to find the perfect threshold that will match all the cases

So, possible actions:

- increase threshold from 300 to 600
- increase the threshold only when testing (although we would be losing the benefit of giving a better experience with slow networks)
- [...]

What do you think @vigneshshanmugam ?

**Comment by vigneshshanmugam** [comment]
Thanks for the detailed writeup Alberto, Just want to understand a bit more before we decide the next steps.

> When loading a lazy loaded component a JS file needs to be downloaded. Sometimes the duration of the file loading is greater than the transaction threshold. This is important for the test data because instead of having one transaction with 3 spans it has two/three different transactions and the spans shared between them, so the assertions fail.

If the same resource timing spans are added as part of both transactions, Are we truncating them to be included as part of those transactions or the transactions end is adjusted based on those timings?

**Comment by devcorpio** [comment]
> If the same resource timing spans are added as part of both transactions, Are we truncating them to be included as part of those transactions or the transactions end is adjusted based on those timings?

I didn't explain properly that part. In this particular scenario the truncate logic is not affecting wrongly. I'm going to explain it more properly:

**<ins>Case 1 (the correct/expected one)</ins>:**

When clicking in the menu item "Manual" the next steps take place:

1.  a new click transaction ```Click - a, user-interaction``` is created
2. there is a `route-change` that redefines the current transaction from ```Click - a, user-interaction``` to ```Click - a, route-change```
3. The react ManualComponent is loaded. Hence, another redefinition goes on, this time from ```Click - a, route-change``` to ```ManualComponent, component```
4. that new component uses `fetch` to retrieve data.json
5. **transaction ends**

In this scenario we have 3 spans: 

1. `resource` type (which corresponds to to the script containing the react component)
2. `external` type (which corresponds to the retrieve of data.json file within the react component)
3. `app` type (which corresponds to `performance.measure('manual-component-mounted'` of the react component logic)

Since the script loads within the 300ms threshold, the span created due to fetching data.json is also included in the transaction.

**<ins>Case 2 (the incorrect/unexpected one. Easily reproducible when playing with throttling tool)</ins>:**

When clicking in the menu item "Manual" the next steps take place:

1.  a new click transaction ```Click - a, user-interaction``` is created
2. there is a `route-change` that redefines the current transaction from ```Click - a, user-interaction``` to ```Click - a, route-change```
3. **HERE first difference**: the script loading time ****exceeds** the 300ms threshold**, so when it finishes:
4. **transaction ends** (with only one span)
5. At this point, the React component loads and the ```ManualComponent, component``` is created
6. that new component uses `fetch` to retrieve data.json
7. **transaction ends** (with only one span)

Then, in this scenario we have 2 transactions which contain 1 span each one

1. Transaction 1 ( `resource` type span)
2. Transaction 2( `external` type span)

The delay in the the script loading made the difference.

Btw, in the second scenario the `app` type span is not even captured 🧐 

--
Hopefully this is clearer than before. Otherwise in this week meeting we can speak about it

**Comment by vigneshshanmugam** [comment]
Ahh that make sense, I see it now, So As you have pointed out the `300ms` threshold is the source of the bug and flakiness. Hmmm, right now I cant think of the consequences that would happen if we increase the reuse threshold for click transactions. Maybe it should be fine. 

> Btw, in the second scenario the app type span is not even captured

This is not an issue, Because the `performance.mark` happened during the previous transaction, so the `app` span timeframe would be between the previous `Click` and `ManualComponent` transaction which is why it got skipped.

**Comment by devcorpio** [comment]
In the last meeting we agreed to leverage the transaction [redefine logic](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-core/src/performance-monitoring/transaction-service.js#L149) to also override the reuseThreshold. 

Following this strategy, we will end up having the default threshold set: 5000ms
