### ISSUE TITLE
Enable/disable config not working?

### ISSUE THREAD

**Issue by raed667** [elastic/apm-agent-rum-js#1198]
I'm using version `5.10.2`, I'm trying to init the agent with disabled config like this:

```js

import { init } from '@elastic/apm-rum';
        
const agent = initApm({
            serverUrl: 'http://localhost',
            serviceName: 'foobar',
            transactionSampleRate: 0.1,
            serviceVersion: version,
            flushInterval: 2000,
            enable: false,
            instrument: false,
        });
```

When I check if the agent is active or enabled I get true : 

```js
agent.isActive() // true
agent.isEnabled() // true
```

Am I missing something very obvious here or is this a bug?

**Comment by devcorpio** [comment]
Hi @raed667,

Have you discovered what was happening? 

Thanks,
Alberto

**Comment by raed667** [comment]
hi @devcorpio thanks for your prompt response !

I thought I did have it solved, but it doesn't seem to be so, i'll re-open the issue. 

Basically, what I'm trying to do it this: 

I have a toggle in my app, that allows user to enable/disable telemetry at any point in time. 

So I thought i could initialize `apm` with something like the following: 

```js
import { init } from '@elastic/apm-rum';

const agent = init({
            serverUrl: 'http://localhost/',
            serviceName: 'foobar',
            transactionSampleRate: 0.1,
            serviceVersion: version,
            flushInterval: 2000,
            enable: false,
        });
```

And when the user toggles the telemetry on, I can enable it like this: 

```js
 agent.config({
            active: true,
        });
```

However it doesn't seem to have the desired effect ?

**Comment by devcorpio** [comment]
Hi @raed667,

Thanks for using Elastic agent!

The config option that specifies if the agent should be active or not is `active` (you are using `enable`). More info [here](https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#active)

Apart from that, at present this config option it's only taken when _initialising_ the agent. That means that the subsequent attempts to modify it after the initialisation are not going to work (even using config method as you are doing).

Having that limitation in mind, something that might help you with your scenario is:

reload the page every time that someone toggles the enable/disable telemetry. The url of that reload should include a query parameter (e.g. https://yourwebsite.com/?rum=true/false) and use the value of that parameter when initialising the agent.

Hope this helps

Thanks,
Alberto

**Comment by raed667** [comment]
Thanks for the clarification @devcorpio !
