### ISSUE TITLE
Unable to upload sourcemaps to /api/apm/sourcemaps endpoint

### ISSUE THREAD

**Issue by fsalazarh** [elastic/apm-agent-rum-js#1203]
We recently updated the Elastic Cloud APM agent to [8.1.2](https://www.elastic.co/guide/en/apm/guide/8.1/apm-quick-start.html) and we are unable to `POST` sourcemaps to `/api/apm/sourcemaps`.

The full URL of our APM endpoint with path to upload sourcemaps accord to v8.1 [documentation](https://www.elastic.co/guide/en/apm/guide/8.1/source-map-how-to.html#source-map-curl): 

`https://ba045e7d3aa248adb6370b76169e5853.apm.us-west-2.aws.cloud.es.io:443/api/apm/sourcemaps`

and the curl test to upload sourcemaps: 

```
curl -X POST "https://ba045e7d3aa248adb6370b76169e5853.apm.us-west-2.aws.cloud.es.io:443/api/apm/sourcemaps" \
-H 'Content-Type: multipart/form-data' \
-H 'kbn-xsrf: true' \
-H 'Authorization: ApiKey ${APM_API_KEY}' \
-F 'service_name="pd-frontend"' \
-F 'service_version="510c4247-local"' \
-F 'bundle_filepath="build/static/js/main.8ba56bfa.chunk.js.map"' \
-F 'sourcemap=@build/static/js/main.8ba56bfa.chunk.js.map'
```

And the response is:
```
{
  "error": "404 page not found"
}
```
The flags of our apm config file are:

```
apm-server.rum.enabled: true
apm-server.rum.source_mapping.enabled: true
apm-server.rum.allow_origins: ['*']
```

The strange thing is that the interaction events from our web-app is sending successfully through the same url, as the image show:

![image](https://user-images.githubusercontent.com/8340890/163833247-614eb8ce-61ab-4087-84bf-b50bd4db9f77.png)

So, I suspect that the endpoint to upload sourcemaps is not enabled, but i don't know why and how to fix it. 

Please help.

**Comment by devcorpio** [comment]
Hi @fsalazarh,

The new endpoint is exposed by Kibana. In [this](https://www.elastic.co/guide/en/apm/guide/8.1/source-map-how-to.html#source-map-rum-upload) part of the documentation it is explained.

So instead of using APM endpoint you should be using your Kibana endpoint. 

Recently, we updated one of the [tests](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum/test/integration/upload-sourcemaps.spec.js) related to sourcemap. There you can see how kibana url is the one being used now.

Thanks,
Alberto

**Comment by devcorpio** [comment]
Hi @fsalazarh,

Have you managed to upload the sourcemaps?

**Comment by fsalazarh** [comment]
Hi @devcorpio, 

Yes, thanks to your response. Now we are using Kibana URL with `/api/apm/sourcemaps` and works as expected.

I recommend that they can be a little more explicit in the changes that must be made between version 7 and version 8 to upload the sourcemaps.

Thanks!
