### ISSUE TITLE
Unknown client IP is coming from the agent

### ISSUE THREAD

**Issue by suraj-dot-gupta** [elastic/apm-agent-rum-js#1259]
The ip address is not matching with the actual ip address of the system from where events are triggering.
Seems to be some private ip.

**Comment by devcorpio** [comment]
Hi @suraj-dot-gupta,

Thanks for reaching out!

RUM agent does not handle anything related to client IP.

> Seems to be some private ip.

I do believe that you are facing the same situation this user faced a while ago:

https://discuss.elastic.co/t/private-ip-addresses-are-logged-in-as-client-ip/236531

Let me know if the solution exposed in the link above helps you to solve the issue you have

Cheers,
Alberto

**Comment by suraj-dot-gupta** [comment]
Thanks @devcorpio for helping me out.
I got it now from where the IP was coming.
