### ISSUE TITLE
First paint of page

### ISSUE THREAD

**Issue by 741439599** [elastic/apm-agent-rum-js#1262]
We  want to collect the first paint of page,but how to calculate it

**Comment by devcorpio** [comment]
Hi @741439599,

Thanks for using the RUM agent!

The agent calculates [First Contentful Paint](https://developer.mozilla.org/en-US/docs/Glossary/First_contentful_paint) [automatically](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/supported-technologies.html#user-centric-metrics) so you don't need it by yourself.

That metric is attached to the **page-load** transaction. You can see that info in the details of a specific transaction on the APM UI.

<img width="977" alt="Screenshot 2022-07-26 at 11 02 10" src="https://user-images.githubusercontent.com/15065076/180968449-c6ece5f9-4b8e-4e2a-aa20-b51d863b99bd.png">

You also can look for that info in Kibana discover:

<img width="291" alt="Screenshot 2022-07-26 at 11 06 06" src="https://user-images.githubusercontent.com/15065076/180968752-6e505801-2a0a-410d-b65e-bb61fefa17dc.png">

Apart from that, In the [User Experience](https://www.elastic.co/guide/en/observability/current/user-experience.html) page you can see all key user experience metrics.


Thanks,
Alberto

**Comment by 741439599** [comment]
Thanks,I add the following code in the captureObserverEntries method of metrics.js
`const fpEntry = list.getEntriesByName(FIRST_PAINT)[0]
  if (fpEntry) {
    const fp = parseInt(
      unloadDiff >= 0 ? fpEntry.startTime - unloadDiff : fpEntry.startTime
    )
    result.marks.firstPaint = fp
  }`

**Comment by 741439599** [comment]
> Hi @741439599,
> 
> Thanks for using the RUM agent!
> 
> The agent calculates [First Contentful Paint](https://developer.mozilla.org/en-US/docs/Glossary/First_contentful_paint) [automatically](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/supported-technologies.html#user-centric-metrics) so you don't need to do it manually. Just make sure that you are not disabling the [instrumentation](https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#disable-instrumentations) related to **page-load**
> 
> The agent will attach FCP to the transaction created while the page is loading. This transaction is commonly known as "page-load transaction". You can see all the data attached via APM UI.
> 
> <img alt="Screenshot 2022-07-26 at 11 02 10" width="977" src="https://user-images.githubusercontent.com/15065076/180968449-c6ece5f9-4b8e-4e2a-aa20-b51d863b99bd.png">
> 
> You also can look for its info in Kibana discover:
> 
> <img alt="Screenshot 2022-07-26 at 11 06 06" width="291" src="https://user-images.githubusercontent.com/15065076/180968752-6e505801-2a0a-410d-b65e-bb61fefa17dc.png">
> 
> Apart from that, on the [User Experience](https://www.elastic.co/guide/en/observability/current/user-experience.html) page you can see all key user experience metrics, too.
> 
> Thanks, Alberto



> Hi @741439599,
> 
> Thanks for using the RUM agent!
> 
> The agent calculates [First Contentful Paint](https://developer.mozilla.org/en-US/docs/Glossary/First_contentful_paint) [automatically](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/supported-technologies.html#user-centric-metrics) so you don't need to do it manually. Just make sure that you are not disabling the [instrumentation](https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#disable-instrumentations) related to **page-load**
> 
> The agent will attach FCP to the transaction created while the page is loading. This transaction is commonly known as "page-load transaction". You can see all the data attached via APM UI.
> 
> <img alt="Screenshot 2022-07-26 at 11 02 10" width="977" src="https://user-images.githubusercontent.com/15065076/180968449-c6ece5f9-4b8e-4e2a-aa20-b51d863b99bd.png">
> 
> You also can look for its info in Kibana discover:
> 
> <img alt="Screenshot 2022-07-26 at 11 06 06" width="291" src="https://user-images.githubusercontent.com/15065076/180968752-6e505801-2a0a-410d-b65e-bb61fefa17dc.png">
> 
> Apart from that, on the [User Experience](https://www.elastic.co/guide/en/observability/current/user-experience.html) page you can see all key user experience metrics, too.
> 
> Thanks, Alberto
I add the following code in the captureObserverEntries method of metrics.js
`const fpEntry = list.getEntriesByName(FIRST_PAINT)[0]
  if (fpEntry) {
    const fp = parseInt(
      unloadDiff >= 0 ? fpEntry.startTime - unloadDiff : fpEntry.startTime
    )
    result.marks.firstPaint = fp
  }`

**Comment by 741439599** [comment]
Thanks，I add below code in captureObserverEntries function of metrics.js
` const fpEntry = list.getEntriesByName(FIRST_PAINT)[0]
  if (fpEntry) {
    const fp = parseInt(
      unloadDiff >= 0 ? fpEntry.startTime - unloadDiff : fpEntry.startTime
    )
    result.marks.firstPaint = fp
  }`

**Comment by devcorpio** [comment]
Hi @741439599,

The agent does not report First Paint (FP) because the performance industry have focused on [these](https://web.dev/user-centric-performance-metrics/#important-metrics-to-measure) user-centric metrics.  That's why we only want to report [FCP](https://web.dev/fcp/).

If you want to include **first paint** with the **page-load** transaction, you could leverage the [addLabels](https://www.elastic.co/guide/en/apm/agent/rum-js/master/transaction-api.html#transaction-add-labels) API and add a code similar to this one to your website:

```
window.addEventListener('load', function () {
    const loadTransaction = elasticApm.getCurrentTransaction()
    if (loadTransaction) {
         const firstPaint = performance.getEntriesByName("first-paint")[0]

        loadTransaction.addLabels({ "first-paint": firstPaint.startTime })
    }
})

```
You can see that data on the transaction detail section:

<img width="650" alt="Screenshot 2022-07-28 at 21 41 38" src="https://user-images.githubusercontent.com/15065076/181623923-da14ae1c-ac8b-417b-a864-ffeacc86c7e1.png">

What is more, if you want to filter all the transactions with your new label, what you can do is to write this query in Kibana Discover:

<img width="533" alt="Screenshot 2022-07-28 at 21 44 59" src="https://user-images.githubusercontent.com/15065076/181624175-f6fe36f6-b6b3-46cc-8f64-57d1742449a9.png">



Cheers,
Alberto
