### ISSUE TITLE
Browser name is not coming after the event is triggered

### ISSUE THREAD

**Issue by suraj-dot-gupta** [elastic/apm-agent-rum-js#1265]
Hi @devcorpio  , browser name is coming for some applications inuser_agent.name.
does agent handle anything related to the browser ?

**Comment by devcorpio** [comment]
Hi @suraj-dot-gupta,

The RUM agent does not handle User-Agent (UA) headers. That is something that the browser does automatically.

Let me know if I'm understanding correctly, there are transactions which not contain the User-Agent information, is that right?

The most likely reasons for having an empty agent.name are mentioned in the following two links

- https://security.stackexchange.com/questions/195076/can-i-assume-that-an-empty-user-agent-will-always-be-a-robot
- https://community.cloudflare.com/t/blocking-empty-user-agent-string/80589/2

Thanks,
Alberto

**Comment by suraj-dot-gupta** [comment]
> Hi @suraj-dot-gupta,
> 
> The RUM agent does not handle User-Agent (UA) headers. That is something that the browser does automatically.
> 
> Let me know if I'm understanding correctly, there are transactions which not contain the User-Agent information, is that right?
> 
> The most likely reasons for having an empty agent.name are mentioned in the following two links
> 
> * https://security.stackexchange.com/questions/195076/can-i-assume-that-an-empty-user-agent-will-always-be-a-robot
> * https://community.cloudflare.com/t/blocking-empty-user-agent-string/80589/2
> 
> Thanks, Alberto

Thanks Alberto,
yeah that is correct, i was not getting user agent in some transactions.

**Comment by devcorpio** [comment]
Hi @suraj-dot-gupta,

Do you need thing anything else from our side? or should I close the issue?

Thanks,
Alberto
