### ISSUE TITLE
miss resource timing when buffer is full

### ISSUE THREAD

**Issue by zhaoShijuan** [elastic/apm-agent-rum-js#1285]
https://w3c.github.io/timing-entrytypes-registry/#registry
According to the link above, we can find that the max-buffer-size of resource timing is 250. 

Once the browser's resource timing buffer is full, we can't capture the latest resource timing. The list of resource timing has not been updated.

So, do we need to solve this problem in the RUM agent?

**Comment by devcorpio** [comment]
Hi @zhaoShijuan,

Thanks for such a great question!

Yes, according to the resource timing [spec](https://www.w3.org/TR/resource-timing-2/#sec-extensions-performance-interface) the **minimum number** (the one they recommend at least) is 250.

> So, do we need to solve this problem in the RUM agent?

That is something that we would need to consider.  It's fair to mention that is not currently on the team's roadmap

--

Despite so, the max-buffer-size can be configured outside of the agent realm given that [performance](https://developer.mozilla.org/en-US/docs/Web/API/Performance) is a browser API.

On [this](https://developer.mozilla.org/en-US/docs/Web/API/Performance/setResourceTimingBufferSize#examples) link you can find examples. (good ones btw)

Depending on your case, you might want to set directly a high value by default, for instance:

```
<!DOCTYPE html>
<html>
    <head>
          <script>
                if (typeof performance.setResourceTimingBufferSize === "function") {
                      performance.setResourceTimingBufferSize(YOUR_VALUE_HERE);
                }
          </script>
    </head>
    <body>
        ...
    </body>
</html>
```

Thanks,
Alberto

**Comment by zhaoShijuan** [comment]
Thanks,I have solved the problem.
If possible, I'd like to add a configuration to solve this issue and listen in the code to periodically remove excess resource timings.
