### ISSUE TITLE
improve naming strategy for user-interaction transactions

### ISSUE THREAD

**Issue by devcorpio** [elastic/apm-agent-rum-js#1286]
# Context

Currently, users can set a custom name for user-interaction transactions via the [data-transaction-name ](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/supported-technologies.html#user-interactions)attribute.

For instance:

`
<button data-transaction-name="add to cart">cart icon</button>
`

Clicking on that button would generate a transaction with the name **Click - add to cart**

# To improve

The current technique does not work well with a nested html structure:

```
<button data-transaction-name="my transaction name">
  <span>Some text</span>
  <svg>button icon...</svg>
</button>
```

The user would expect to see **Click - my transaction name** but instead the transaction's name that they will see is either **Click - span** or **Click - svg**

There are workarounds like setting **data-transaction-name** in each node, but that can be cumbersome and even affect the performance of the website since the payload might be bigger. 

Not only that, some libraries generate extra html code dynamically making then impossible or **pretty difficult** to modify. Just for illustration, when using [Material UI](https://mui.com/) it's common for a developer to write code like this one: 

`<DeleteIcon data-transaction-name="delete" />`

But what we see in the browser is a nested structure:

```
<svg ... data-transaction-name="DeleteSltd">
      <path d="..."></path>
</svg>
```

Causing then the naming issues commented above.

# Why is it important to improve this?

This issue has been reported multiple times by users and customers and for quite a while. [This](https://elastic.slack.com/archives/C02N6H8HPM2/p1654248897066909) slack thread is just an example of those reports.

**Comment by nicolasguilhem** [comment]
In addition, many frameworks like Angular and React generate code dynamically (like the example in description with Material UI).

Would be a great feature.

As a suggestion, looking recursivly in parent of target for attribute `data-transaction-name` in https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-core/src/common/observers/page-clicks.js#L77 should do the job ?

**Comment by devcorpio** [comment]
it has been released: https://www.elastic.co/guide/en/apm/agent/rum-js/current/release-notes-5.x.html#release-notes-5.13.0
