### ISSUE TITLE
Add support for Interaction Next Paint (INP)

### ISSUE THREAD

**Issue by devcorpio** [elastic/apm-agent-rum-js#1293]
# Summary

[INP](https://web.dev/inp/) is a metric whose goal is to measure responsiveness throughout the page lifecycle.

> Chrome usage data shows that 90% of a user's time on a page is spent after it loads, Thus, careful measurement of responsiveness throughout the page lifecycle is important. This is what the INP metric assesses.

To strategy followed by Google to measure this on the field is to rely on the `visibilitystate` event. The logic that decides if the metric should be reported is performed every time the page's visibility state changes to hidden. Due to that fact, it's important to keep in mind that the metric can be reported multiple times on the same page.

The nature of this new metric doesn't **seem** to fit perfectly with any of the existing transactions on the agent. Since the **main** goal of this metric is to measure the responsiveness after the page's load we cannot attach this information to the **page-load** transaction.

**Possible** approaches to tackle this:

- Create a new type of transaction for this
- Maybe it's time to revisit the [custom metrics feature](https://github.com/elastic/apm-agent-rum-js/issues/197)
- [... more ideas ...]

Please, feel free to add comments, ideas, etc.

CC: @kyungeunni @vigneshshanmugam

**Comment by paulb-elastic** [comment]
INP to replace FID as a core web vital metric in March 2024 https://web.dev/inp-cwv/

**Comment by paulb-elastic** [comment]
Some useful links:
- https://developer.chrome.com/blog/inp-tools-2022/
- https://web.dev/inp/#measure-inp-in-javascript
- https://web.dev/inp/#in-the-lab

**Comment by StuGray86** [comment]
Do you have any plans for dealing with this? Google are rolling this out in March, so it would be good to see some plans around how Elastic RUM will deal with this.

**Comment by RobDTech** [comment]
We are an Enterprise Retail customer, this metric is key to all Retailers and the lack of visibility on this metric is worrying. Please can you indicate if this is something that is coming in the next release?

**Comment by devcorpio** [comment]
Hi @StuGray86 @RobDTech,

A new version of the agent was released, please see the [release notes](https://www.elastic.co/guide/en/apm/agent/rum-js/current/release-notes-5.x.html#release-notes-5.16.0) for more details.

Thanks,
Alberto
