### ISSUE TITLE
Allow parent transaction id in `captureError`

### ISSUE THREAD

**Issue by xirdneh** [elastic/apm-agent-rum-js#1312]
When using `captureError` the event created gets assigned the [current transaction](https://github.com/elastic/apm-agent-rum-js/blob/1c341a4bc9e10699039bb8a934c0175cb72a8de8/packages/rum-core/src/error-logging/error-logging.js#L112) but this clashes when a transaction related to an automatically instrumented event is active at the same time as a custom transaction.

When this happens there's no way to use `captureError` and get that error event linked to the custom transaction and it automatically gets linked to the managed transaction that's active. It causes issues because I'm trying to create a custom transaction when there's a page load and if there are any errors to show those errors in that transaction but every error is linked to the page load automatically created by the agent.

I believe the `captureError` signature can change to accept an `options` object and the parent trace id can be set in the [error event context](https://github.com/elastic/apm-agent-rum-js/blob/1c341a4bc9e10699039bb8a934c0175cb72a8de8/packages/rum-core/src/error-logging/error-logging.js#L120)

**Comment by devcorpio** [comment]
Hi @xirdneh,

Thanks for using the RUM agent!

I agree that `captureError` functionality should be improved to also cover custom transactions. Thanks for pointing it out!

One way that might help you to achieve what you want is:

- disable [page-load](https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#disable-instrumentations) instrumentation
- create a [custom managed transaction](https://www.elastic.co/guide/en/apm/agent/rum-js/master/custom-transactions.html#custom-managed-transactions) with the type page-load (bear in mind that you will need to finish it manually, too)
- then, using **captureError** will assign the transaction that you have created

I understand that you can find drawbacks to this workaround.

--
Will have this issue in mind when redefining team priorities.

Thanks,
Alberto

**Comment by xirdneh** [comment]
Thanks @devcorpio, yes we thought about this solution but haven't decided if it's what we want.

What we're doing for now is trying to add the same labels to the custom transaction and the page load transaction. When an error happens on the custom transaction at least we can search for that error based on the shared labels and we add a `hasError` boolean variable to the custom transaction to show that an error happened.

**Comment by xirdneh** [comment]
BTW, a solution for this is to create managed transactions.
Unmanaged custom transactions don't get errors attached to them.
