### ISSUE TITLE
Tracestate is not properly appended when there is already a tracestate

### ISSUE THREAD

**Issue by philippkahr** [elastic/apm-agent-rum-js#1334]
I have the following few pieces:

NextJS, instrumented using the NodeJS agent
NextJS => showing the Frontend instrumented using React-RUM + RUM JS
Tram, Bus, Metro => a Python flask service that is just simulating a tram ride (waiting at stops and so on).

My UI looks like this:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/12175559/214663479-2708fda7-c50c-4ec2-8a24-da2285c8fd11.png">

`Create new travel` creates a unique id for all travel related things.

If I now click on `Bus 1`:

```js

  const handleTravel = async () => {
    setTravelstate(true);
    setTravelid(`tef=${uuid()}`)
  }

  const handleCardClick = async (card, description) => {
    apm.startTransaction(`Click - ${description}`, "user-interaction", { managed: true })
    const activeTransaction = apm.getCurrentTransaction()
    activeTransaction.addLabels({"http.request.headers.Tracestate": travelid})
    setLoading(true);
    myHeaders.append('tracestate', travelid);
    try {
      switch (card[0]) {
        case "b":
          setDes(`Boarding Bus ${card[1]}`)
          setDes(`On Bus ${card[1]}`)
          await fetch(`http://bus.localhost:9000/buses/${card[1]}/drive`, { method: 'POST', headers: myHeaders });
          setDes(`Leaving Bus ${card[1]}`)
          await new Promise(r => setTimeout(r, 2000));
          break;
```

As you can see, it's nothing exotic that is happening here. I am using the Tracestate header to inject information about trace. In this case it is a unique id to identify a customer journey.

Nonetheless my backend service e.g. Bus 1, written in python flask:

sees this header arriving:

```
bus_1                   | Traceparent: 00-f2dbb6f20cef9508b54c86c168ac37e3-fb938da05a67835d-01
bus_1                   | Tracestate: tef=432c671b-1018-021a-ef9a-acac1930e5e1, es=s:1
```

As you can see that is an issue and as soon s I enable the APM agent for Flask it breaks, because there is a `space` after `, ` before the `es`.

I am not sure why the JS agent adds a space to the header?

**Comment by philippkahr** [comment]
Interesting, we don't return ` data` we do this: https://github.com/philippkahr/apm-agent-rum-js/blob/98722ec348cabee75f6aebe268782cb3121bfa23/packages/rum-core/src/common/utils.js#L131

hmm. Sadly not an easy fix for me :D. Someone with more JS knowledge needs to take this.

**Comment by philippkahr** [comment]
For anyone following this. It does not seem like this issue stems from the JS agent as the spec allows a `a=b, c=d` and the python agent should be able to deal with the `space` character.

It appears, that we are not testing that, at least in python. https://github.com/elastic/apm-agent-python/blob/7b2de881090877c9b0819e96a840aa4c92119deb/tests/utils/test_disttracing_header.py#L142

**Comment by devcorpio** [comment]
thank you @philippkahr for making this visible. I'm closing the ticket since the solution needs to be done in other agents (e.g. Python)
