### ISSUE TITLE
sendCredentials configuration does not work

### ISSUE THREAD

**Issue by kes2464** [elastic/apm-agent-rum-js#1335]
https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#send-credentials

sendCredentials configuration is documented but not working currently.

It seems like there was a fix https://github.com/elastic/apm-agent-rum-js/pull/1243, but it has never been released.

Is there any plan for a release?

Thanks!

**Comment by devcorpio** [comment]
Hi @kes2464 

Thanks for reaching out!

The feature is [released](https://www.elastic.co/guide/en/apm/agent/rum-js/master/release-notes-5.x.html#release-notes-5.12.0). What is not released is the update of the types definition file.

Given that we don't have yet a date for the next release, what you can do to avoid the typescript compilation error is to add the comment `// @ts-ignore` mentioned [here](https://github.com/elastic/apm-agent-rum-js/issues/1320#issuecomment-1328942566)

Cheers,
Alberto

**Comment by kes2464** [comment]
Thanks @devcorpio. Adding `// @ts-ignore` worked!
