### ISSUE TITLE
How to upload source maps from a create-react-app (CRA) project?

### ISSUE THREAD

**Issue by cassis163** [elastic/apm-agent-rum-js#1337]
I tried but failed to upload a source map with:
```
curl POST "{$KIBANA_URL}/api/apm/sourcemaps" \
    -H 'Content-Type: multipart/form-data' \
    -H 'kbn-xsrf: true' \
    -H 'Authorization: ApiKey ${API_KEY}' \
    -F 'service_name=pos-screen' \
    -F 'service_version=${GIT_COMMIT_HASH}' \
    -F 'bundle_filepath=@build/static/js/main.${SOURCE_MAP_VERSION}.js' \
    -F 'sourcemap=@build/static/js/main.${SOURCE_MAP_VERSION}.js.map' \
```
However, I believe that my source map is not compatible with the APM server as I get a 400 error. It did actually upload some files though. The documentation states that "To be compatible with Elastic APM, source maps must follow the [source map revision 3 proposal spec](https://sourcemaps.info/spec.html)."
```
{
    "statusCode":400,"error":"Bad Request",
    "message":"Invalid value {\"type\":\"Buffer\",\"data\":[TON OF NUMBERS]} supplied to : merge/0: {body: { service_name: string, service_version: string, bundle_filepath: string, sourcemap: pipe(pipe((string | stringFromBufferRt), JSON), ({ version: number, sources: Array<string>, mappings: string } & Partial<{ names: Array<string>, file: string, sourceRoot: string, sourcesContent: Array<string> }>)) } }/body: { service_name: string, service_version: string, bundle_filepath: string, sourcemap: pipe(pipe((string | stringFromBufferRt), JSON), ({ version: number, sources: Array<string>, mappings: string } & Partial<{ names: Array<string>, file: string, sourceRoot: string, sourcesContent: Array<string> }>)) }/bundle_filepath: string","attributes":{"_inspect":[]}
}
```
I noticed that it might be fixed by applying some configuration to Webpack, but I am reluctant to do that since I am using CRA. create-react-app has Webpack and more all configurated under the hood and I really do not want to run `npm run eject` for the sake of just adding a few lines to my Webpack configuration.

**Comment by devcorpio** [comment]
Hi @cassis163,

That's right, the source map should meet revision 3 proposal spec.

You can find here a good example of how to upload a sourcemap: https://discuss.elastic.co/t/uploading-sourcemaps-from-aix-webserver/303526/15?u=alberto_delgado

Hope that helps you!

Thanks,
Alberto

**Comment by cassis163** [comment]
I realized that I was uploading a file instead of a file path ('bundle_filepath')... Thanks for sending me an example of how to implement this from a web server though!
