### ISSUE TITLE
ngcc is removed in Angular 16

### ISSUE THREAD

**Issue by stefannikolei** [elastic/apm-agent-rum-js#1345]
When i install my dependencies i see see following warning when targeting Angular 15:

Processing legacy "View Engine" libraries:
- @elastic/apm-rum-angular [module/esm2015] (https://github.com/elastic/apm-agent-rum-js.git)

So i think that there will be problems with Angular 16 because the ngcc Compiler got removed. 

See --> https://github.com/angular/angular/blob/main/CHANGELOG.md#compiler (https://github.com/angular/angular/pull/49101)

**Comment by stefannikolei** [comment]
Any Updates on this. All developers who wanna update to Angular V16 will be blocked by this. We rather wait for this to be resolved or must abandon elastic as our RUM Monitoring. :(

**Comment by stefannikolei** [comment]
Angular V16 is released. But no words from elastic 😰

**Comment by drewpost** [comment]
Hello to everyone following this issue. Apologies for the slow replies. I can confirm that we intend to deliver this support with an update coming to our RUM-JS agent this summer.

**Comment by ArthurIbias** [comment]
![image](https://github.com/elastic/apm-agent-rum-js/assets/37701365/12bd5ac3-e55f-449a-8402-3a7bc3a3154c)

Are there any plans to update this module with compatibility for Angular v16+?

**Comment by aikrez** [comment]
@drewpost Can we have a more precise timeline than 'this summer' as that could be months from now.
The company I consult for is blocked by this for upgrading their applications.

**Comment by drewpost** [comment]
> @drewpost Can we have a more precise timeline than 'this summer' as that could be months from now.
> The company I consult for is blocked by this for upgrading their applications.

It's about as accurate as I can be at the moment. My best guess would be July BUT that could shift.

A bit of context: The people working on this are also the same team who are delivering our new synthetics product which is going GA in the 8.8 stack release. We anticipate there will be work reacting to things from that release but the plan is that there will be bandwidth to tackle this RUM work in June. Whilst we have stack release cycles and the teams working tend to organise around these, the RUM-JS agent can be released outside of the normal stack releases. It's out plan to ship this updated agent as soon as the work is done to minimise any further delay. 

I hope that helps with the planning. If there's any updates to that schedule either way, I'll update this issue.

**Comment by devcorpio** [comment]
Hi everyone,

The PR with the changes is now merged.

Will add a new comment here once we release the new version of the angular package

Thanks,
Alberto

**Comment by hm-00** [comment]
what happened here?   a revert on th PR?

**Comment by alexsukhodolsky** [comment]
@devcorpio is there a timeline set for the release? We upgraded recently to angular 16 and are running blind without RUM enabled.

**Comment by kralphs** [comment]
C'mon, guys.... this day has been coming for around 3 years. There's really no excuse to have this on the back burner. Gonna be pretty upset if we have to disable APM or delay an Angular upgrade because of this.

**Comment by paulb-elastic** [comment]
Thank you all for your patience, we will be able to share details of a release within the next few weeks

**Comment by devcorpio** [comment]
Hi everyone,

The angular package has just been released with the Ivy changes and it's already available:

https://www.npmjs.com/package/@elastic/apm-rum-angular/v/3.0.0

Shortly we will update the release notes pages informing of all the released changes (including the ones belonging to RUM core agent)

thanks again for your patience.

Cheers,
Alberto
