### ISSUE TITLE
Breakdown Timings are reported in milliseconds not microseconds

### ISSUE THREAD

**Issue by simonhearne** [elastic/apm-agent-rum-js#1360]
Breakdown timings are [reported as](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-core/src/performance-monitoring/breakdown.js#L145) millisecond values in the `span.self_time.sum.us` field.

These values should be microseconds to match the [APM field definitions](https://www.elastic.co/guide/en/apm/server/current/exported-fields-apm-transaction-metrics.html#_self_time).

**Comment by drewpost** [comment]
I can confirm that we intend to remedy this issue with an update coming to our RUM-JS agent this summer.

**Comment by devcorpio** [comment]
This has been released: https://www.elastic.co/guide/en/apm/agent/rum-js/current/release-notes-5.x.html#release-notes-5.13.0
