### ISSUE TITLE
An Ivy distribution library version

### ISSUE THREAD

**Issue by daniellrsouza** [elastic/apm-agent-rum-js#1363]
Any idea when there will be a new version with compatibility to the Ivy compiler?

![image](https://user-images.githubusercontent.com/21343507/230494511-794f8d3b-b3bc-4b2b-b79a-d82fbd588dcc.png)

**Comment by n4imLess** [comment]
I'd consider this a duplicate of #1345. With Angular 16 on the horizon we need an Ivy distribution anyways.

**Comment by devcorpio** [comment]
as mentioned [here](https://github.com/elastic/apm-agent-rum-js/issues/1345#issuecomment-1640658765) the new version has been released
