### ISSUE TITLE
Bug fix with respect to User Sessions

### ISSUE THREAD

**Issue by Siddharth-KP-ML** [elastic/apm-agent-rum-js#1366]
1. Option for **session** is not exposed in the agent configuration
2. Add session details for all types of transactions. Currently, it is enabled only for Page load type of transaction

**Comment by NicklasWallgren** [comment]
@Siddharth-KP-ML Please open a MR, we need this as well.

**Comment by devcorpio** [comment]
Hi all,

Thanks for using our RUM agent.

There are no plans in the short/mid-term to add sessions to the RUM agent.

Once there are plans to do we will let you know

Alberto
