### ISSUE TITLE
Custom serializer for Unhandled promise rejection: <object> 

### ISSUE THREAD

**Issue by aizerin** [elastic/apm-agent-rum-js#1423]
I want to send more details when unhandled promise rejection occurs with an object as a rejection reason. But the problem is that I'm not able to modify it somehow. This function [logPromiseEvent](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-core/src/error-logging/error-logging.js#L174) will just throw it away.

It would be nice to have a function like https://www.elastic.co/guide/en/apm/agent/rum-js/current/agent-api.html#apm-add-filter to alter a promise payload.

I can create PR for this change if you think that it will be nice to have it.

currently, I'm using this ugly workaround:

```javascript
if (typeof window !== 'undefined') {
  const originalAddEventListener = window.addEventListener;
  window.addEventListener = (type, fn) => {
    if (type === 'unhandledrejection' && fn.toString().includes('logPromiseEvent')) {
      originalAddEventListener(type, (event) => {
        let modifiedEvent = event;
        if (isPlainObject(event.reason) && !event.reason?.message) {
          modifiedEvent = {
            reason: {
              message: 'some custom message',
              serializedData: JSON.stringify(event.reason),
            },
          };
        }
        fn(modifiedEvent);
      });
    } else {
      originalAddEventListener(type, fn);
    }
  };
}
```

**Comment by devcorpio** [comment]
Hi @aizerin,

Thanks for using the RUM agent!

For further clarification, I would like to ask you a few questions:

- What are you seeing in Kibana UI if don't apply the workaround? I mean, what information are you seeing?
- What information is your workaround adding/modifying?

Additionally, could you share a snippet where you throw the kind of error you are mentioning? and showing us how things differ with and without the workaround? Something like "current behaviour", "expected/wished behaviour", for instance.

That would help us to better understand the scenario you are describing. 

Thanks,
Alberto

**Comment by aizerin** [comment]
Hi,
this is the current behavior. I can see unhandled promise rejection in Kibana but I cannot find any helpful information about it.
![current](https://github.com/elastic/apm-agent-rum-js/assets/18553162/aedab0d5-8d3e-46a8-bdb9-5c038cb9f047)

with the workaround I can have more detailed informations.

I can set custom message based on data

<img width="1375" alt="image" src="https://github.com/elastic/apm-agent-rum-js/assets/18553162/c886c2bf-95ca-4f51-b390-aa913d956e9f">

And I can see serialized object in metadata of error.

<img width="1032" alt="image" src="https://github.com/elastic/apm-agent-rum-js/assets/18553162/6f8e2fb0-3a57-4e23-a821-05d0e6a5b4d4">

And you can use this code which will give you unhandled promise rejection.

```javascript
const promise = () => new Promise((resolve,reject) => {
    setTimeout(() => {
         reject({foo: 'bar'})
    }, 100)
})

promise();
```

**Comment by devcorpio** [comment]
Hi @aizerin,

Apologies for the delay!

I was thinking about this:

`I want to send more details when unhandled promise rejection occurs with an object as a rejection reason.`

Do you have control over those rejections? I mean, are you adding those rejects in your codebase? or are third-party libraries the ones doing that?

I'm asking this because if the object you reject has this format:

```
  const errorLikeObj = {
        message: "This is a mandatory field"
        foo: "bar"
        anotherCustomName: "rum",
        name: "MyCustomError
  }
```

**Comment by devcorpio** [comment]
Hi @aizerin,

Apologies for the delay!

I was thinking about this:

> I want to send more details when unhandled promise rejection occurs with an object as a rejection reason.


Do you have control over those rejections? I mean, are you adding those rejects in your codebase? or are third-party libraries the ones doing that?

I'm asking this because if the object you reject has the format of the one below, you wouldn't need that workaround:

```
  const errorLikeObj = {
        message: "This is a mandatory field",
        foo: "bar",
        anotherCustomName: "rum",
        name: "MyCustomError"
  }

const promise = () => new Promise((resolve,reject) => {
    setTimeout(() => {
         reject(errorLikeObj)
    }, 100)
})

promise();```


Screenshot of the generated event:
<img width="1357" alt="Screenshot error" src="https://github.com/elastic/apm-agent-rum-js/assets/15065076/68ce9318-7ceb-4065-a496-98f8134cdafb">

**Comment by aizerin** [comment]
Hi, 
it's ok. Unfortunately I don't have control about every rejection. Thats why I need to have my own post processor.

Thanks,
Lukas

**Comment by devcorpio** [comment]
Hi @aizerin,

There is a PR in progress. https://github.com/elastic/apm-agent-rum-js/pull/1428

You will see there the approach we have decided to follow

Cheers,
Alberto

**Comment by devcorpio** [comment]
Hi,

There is a new version version of the RUM agent: https://www.elastic.co/guide/en/apm/agent/rum-js/current/release-notes-5.x.html#release-notes-5.15.0

Cheers,
Alberto
