### ISSUE TITLE
Incorrect page-load transaction duration for unsampled transactions

### ISSUE THREAD

**Issue by YauhenChakhlou** [elastic/apm-agent-rum-js#1430]
## Description

Hi. While investigating the PLT metric of our application, we've found that average PLT metrics differ significantly between **sampled** and **unsampled** transactions. Example:

1. Sampled: PLT average - **3.5 sec**
2. Unsampled: PLT average - **2 sec**
3. Both: PLT average - **2.3 sec**

So, the difference is significant and almost stable for different periods of time. After deeply investigating for some time, I've found that the exact value for unsampled transactions comes from the **rum-agent**. 

## Investigation
It seems like user agent, in case of **unsampled** page-load transactions, reports very short transaction.duration times - and in a lot of cases it is even smaller, than **domComplete** metric from the dev-tools itself (logically impossible)

For now, I've found the following cause: [capture-navigation.js](https://github.com/elastic/apm-agent-rum-js/blob/9785834cb1f48b5a461ff4f8b21f4a914f4f6c3f/packages/rum-core/src/performance-monitoring/navigation/capture-navigation.js#L72)

It looks like the **_start** time of a page-load transactions is set to **zero** inside ```captureNavigation()``` function

```javascript
const trStart = 0
transaction._start = trStart
```

But in case of the **unsampled** transaction, there is a preliminary **return** from that function, as it is supposed to not capture timings for such transactions:
```javascript
if (!transaction.captureTimings) {
  return
}
```

So, for unsampled ones, the ```transaction._start``` remains set, as from beginning, somewhere near the **agent initialisation time**.

I am **_assuming_**, that unsampled transactions are **_supposed_** to be included in PLT metrics calculations by **_default_**, both by documentation and general code logic: [https://www.elastic.co/guide/en/apm/guide/current/sampling.html#_sampled_data_and_visualizations](https://www.elastic.co/guide/en/apm/guide/current/sampling.html#_sampled_data_and_visualizations)

>Real User Monitoring (RUM) traces are an exception to this rule. The Kibana apps that utilize RUM data depend on transaction events, so non-sampled RUM traces retain transaction data — only span data is dropped

## Possible solution

A straightforward solution would be:

```javascript
if (!transaction.captureTimings) {
  if (transaction.type === PAGE_LOAD) {
    transaction._start = 0
  }
  return
}
```

I've created a basic pull request for reference: #1431 

Please verify, if I am correct with my assumptions; 
Thanks,
Yauhen.

**Comment by devcorpio** [comment]
Hi @YauhenChakhlou,

Many thanks for spotting this! Also, we really appreciate the well-detailed the issue description is, thanks for that, too.

We just created the PR with the fix: https://github.com/elastic/apm-agent-rum-js/pull/1435

Cheers,
Alberto

**Comment by devcorpio** [comment]
Hi,

There is a new version version of the RUM agent: https://www.elastic.co/guide/en/apm/agent/rum-js/current/release-notes-5.x.html#release-notes-5.15.0

Cheers,
Alberto

**Comment by YauhenChakhlou** [comment]
Hi Alberto,

Thanks for reacting quickly and even providing a new release with a fix!

I want to add, that while investigating this issue, I think, found **another** place, where some discrepancy can happen when comparing sampled and unsampled transactions (affected by resource and xhr spans). This is much **harder** to reproduce  and thus probably of **_much less importance_**. 

I'll try soon to describe it in another issue, so you can verify if it is a problem at all.

Thanks,
Yauhen

**Comment by devcorpio** [comment]
Hi @YauhenChakhlou,

Much appreciated!

Thanks,
Alberto
