### ISSUE TITLE
Ability to update transactionSampleRate from transaction level

### ISSUE THREAD

**Issue by geekysam7** [elastic/apm-agent-rum-js#1448]
Hi Apm team,
We've a use case where we would like to update `transactionSampleRate` from transaction level. We'll ideally do it once only but we need a holistic way to do it. 

For now we're doing something like (agent version 5):
```js
elasticApmInstance.serviceFactory.instances.ConfigService.config.transactionSampleRate = transactionSampleRate; // fetched from some api
```

Why do we need this?
We inject the script at top level and fetch some properties per user level where we're defining the sampleRate for the user. This way we can update sampling rate after injecting the script.

**Comment by vigneshshanmugam** [comment]
If the script is injected at the top differently for each user, Cant you do that as part of the initialization phase 
```
elasticApm.init({
  transactionSampleRate: 1
})
```

This would do the exact same thing as you are already doing.

**Comment by geekysam7** [comment]
We would like to do it post initialisation. Injecting and initialisation is done at one place and then we're updating from an api or let's say we have a trigger point to update 'transactionSampleRate'. For that case if there's an api to do so. Otherwise do you think the above approach should not cause any problems?

**Comment by vigneshshanmugam** [comment]
Gotcha, there is no such API for that unfortunately as we would like to approach sampling in a higher level (Session, Visits) and not tuned based on a user.

It will work as long as we have the core ConfigService unchanged, but I cannot promise that it will stay forever the same way. But given we have not planned for a breaking change, It would continue to work and we will document breaking changes if we plan to roll out a major version. 

To be more safer, you could use this API instead which is used by the `init` under the hood. 
```js
  elasticApm.config({transactionSampleRate: 1})
```

Please do let us know if you need more information. Thanks

**Comment by geekysam7** [comment]
Thanks @vigneshshanmugam, this is what I was looking for. 

Cheers 🎉

**Comment by vigneshshanmugam** [comment]
Closing as its solved,Please do let us know if you need anything else :)
