### ISSUE TITLE
@elastic/apm-rum causes bundling issue with @web/dev-server

### ISSUE THREAD

**Issue by gabrielslach** [elastic/apm-agent-rum-js#1486]
I installed the rum package with npm.
I run my app locally with @web/dev-server. Now, when importing this library, I get the following error.
<img width="455" alt="image" src="https://github.com/elastic/apm-agent-rum-js/assets/18163766/def142d5-f1c0-4450-b928-3eb166a0ce83">

This is my config.
<img width="996" alt="image" src="https://github.com/elastic/apm-agent-rum-js/assets/18163766/8dbe0636-8479-4c30-957b-d98407ba1d54">

But now when I add these, it just produce additional errors.
<img width="456" alt="image" src="https://github.com/elastic/apm-agent-rum-js/assets/18163766/18a3d119-95e4-4ccd-b80a-b35b087bf1e1">

**Comment by devcorpio** [comment]
Hi @gabrielslach,

Thanks for exposing your case.

We are not aware of the web-dev-server specifics. Despite so, I would like to provide you with a workaround that I tested personallu, this is the content of my `web-dev-server.config.mjs` file:

```
import { fromRollup } from '@web/dev-server-rollup';
import rollupCommonjs from '@rollup/plugin-commonjs';
import rollupReplace from '@rollup/plugin-replace';

const commonjs = fromRollup(rollupCommonjs);
const replace = fromRollup(rollupReplace);

export default {
  plugins: [
    replace({
      "process.env.NODE_ENV": "'development'",
      "import { createTracer":  "var createTracer = function (){ /* noop */} //",
      preventAssignment: false
    }),
    commonjs(),
  ],
};
```

<img width="518" alt="Screenshot 2024-03-13 at 13 53 18" src="https://github.com/elastic/apm-agent-rum-js/assets/15065076/e05810f4-5157-454a-ac89-82a00a0902c9">


`noop.ts` belongs to opentracing which is not maintained anymore for us, so you can get rid of it like I'm doing in the snippet:

```
import { createTracer":  "var createTracer = function (){ /* noop */} //
```

Not sure about your context specifics, maybe you will want to add the process.env.NODE_ENV thingy as well.

But at least with that config file setup, RUM works, the screenshot below corresponds to a beacon:

<img width="372" alt="Screenshot 2024-03-13 at 13 51 51" src="https://github.com/elastic/apm-agent-rum-js/assets/15065076/b75a595a-4f38-4b55-a735-5c95401cb2d4">


Cheers,
Alberto

**Comment by gabrielslach** [comment]
Thank you @devcorpio, I just realized that I provided the wrong snippet of my config. Nevertheless, your fix works!
This fix is conflicting with the web-mocks. (_@web/mocks/browser.js_) So I had to limit the replace action to @elastic**.

![image](https://github.com/elastic/apm-agent-rum-js/assets/18163766/6fb4bf56-d987-4a09-a047-5705451f73d2)
