### ISSUE TITLE
[APM-CI][Rum] Add Code coverage report to PRs

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#153]

**Comment by vigneshshanmugam** [comment]
Have used https://codecov.io/ before and its super easy to set it up, Plus the bot does update the PR with the coverage diff which is cool

**Comment by alvarolobato** [comment]
@observablt-robots can we prioritize this issue please?

**Comment by v1v** [comment]
Glad to share https://github.com/elastic/apm-agent-rum-js/pull/180 has been merged and therefore we do have the setup in place to move forward and get rid of any sensitive credentials in the repo

**Comment by vigneshshanmugam** [comment]
@v1v Should agent devs integrate the coverage mechanism in the repo and Jenkins would take care of running the codecov for us?

**Comment by jahtalab** [comment]
The code coverage can already be used locally (it uses instanbul and karma to generate the report). 

@v1v , Do you think we can use the existing setup on jenkins or are you planning to use a separate service?

**Comment by vigneshshanmugam** [comment]
> The code coverage can already be used locally (it uses instanbul and karma to generate the report).

Yes, I checked that already. We had to fix a small issue to make it work. I have a working PR which sets up the codecov as well. https://github.com/elastic/apm-agent-rum-js/pull/322

@v1v Have to run `npm run coverage` on the main repo to create the files for coverage reports
