### ISSUE TITLE
Missing functionality in captureError

### ISSUE THREAD

**Issue by jul1ans** [elastic/apm-agent-rum-js#1553]
Hi there,

currently the capture error method only supports one parameter, the error object
https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum/src/apm-base.js#L319 

Every extra field in the error object will be handled as a custom field. 
Now I want to add some labels to the error because I need them for indexing.

Like described here, the captureError method should have a second options parameter where I can put custom labels to it
https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum/src/apm-base.js#L319

Unfortunately the javascript / typescript implementation of the function doesn't support this.

Are there any plans to extend the funcitonality, or what is the alternative way if we want to add custom labels or custom fileds which can be indexed?

Thank you in advance

**Comment by david-luna** [comment]
Hi @jul1ans 

> Like described here, the captureError method should have a second options parameter where I can put custom labels to it
https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum/src/apm-base.js#L319

The link points to the codebase where it shows the method only accept one parameter. The docs also defines one single parameter for `apm.captureError()`([link](https://www.elastic.co/guide/en/apm/agent/rum-js/current/agent-api.html#capture-error)).

> Every extra field in the error object will be handled as a custom field.

that's the error context and yes, you can add extra fields to the error and they will be sent as part of the context.

According to the API docs only transactions and spans can have labels. Could you tell me what's the goal you want to achieve?
docs references:
- [Transaciton API](https://www.elastic.co/guide/en/apm/agent/rum-js/current/transaction-api.html#transaction-add-labels)
- [Span API](https://www.elastic.co/guide/en/apm/agent/rum-js/current/span-api.html#span-add-labels)

**Comment by jul1ans** [comment]
Hi @david-luna 
thank you for your response.

Sry I posted the wrong link in the second section.

I wanted to point here:
https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-capture-error

Regarding this docs page, the error object should support a second options parameter. 

We want to create custom grafana boards where we can filter for specific errors which have a special label (for example all errors with a custom label "foo").

When we add this "foo" label as custom field, we can not filter for it in the board because it's not indexed.

**Comment by david-luna** [comment]
Hi @jul1ans 

You're pointing the `Node.js Agent`'s documentation and not the `RUM Agent`'s. Although both are written in JavaScript they are meant to run in complete different runtimes, server and browser respectively. And they have completely different implementations.

The `captureError` docs for RUM agent are the ones I linked in my previous comment and there is no gap between docs and implementation. This is [the link](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/agent-api.html#capture-error) for the record.

So this is a new feature request. Unfortunately the RUM agent does not have any new features on the roadmap.

As a workaround you can transform document by applying ingest pipelines. I'm not an expert in the matter but I think is possible to set a label from the context fields. Here is the link https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html

**Comment by simonhearne** [comment]
@jul1ans you can overload the Error object with custom properties, I have used the following to capture custom metadata with errors:
```
err = new Error('Error modal opened');
elasticApm.captureError(Object.assign(err,{"event":"modal_opened","modalId":1,"modalSeverity":"ERROR","modalTitle":"Whoops!"}));
```
By default these `error.custom.*` fields are not mapped but you can configure that in the relevant index template, e.g. mapping to `keyword`:
```
{
  "template": {
    "mappings": {
      "dynamic_templates": [
        {
          "custom_error_keywords": {
            "path_match": "error.custom.*",
            "mapping": {
              "type": "keyword"
            }
          }
        }
        ...
```
You could then create your Grafana visualisations (or Kibana Lens visualisations) based on these fields. Example below from discover:
![Image](https://github.com/user-attachments/assets/cb704852-438d-42a0-bd3f-d3f9eea3b2d3)
![Image](https://github.com/user-attachments/assets/4e2ab191-92ef-4607-8df3-1e8a08a3f5c9)

**Comment by jul1ans** [comment]
@david-luna thank your for the clarification.

@simonhearne thank you for the input. I'll try this in my board. 

Ticket can be then closed because feature is not available
