### ISSUE TITLE
Add the ability to run e2e tests without using saucelabs

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#176]
possible solutions (selenium, puppeteer, https://www.cypress.io/)

**Comment by kuisathaverat** [comment]
IIRC UI people are using jest+puppeteer

**Comment by jahtalab** [comment]
[Webdriver recently added devtools service](https://webdriver.io/blog/2019/09/16/devtools.html) which can be used to run tests against chrome headless. [devtools-service docs](https://webdriver.io/docs/devtools-service.html).
