### ISSUE TITLE
Add config option to disable auto instrumentation

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#192]
This option needs to disable automatically creating spans and transactions but the user should be able to create transactions and spans manually (or through the OpenTracing bridge). See https://github.com/elastic/apm/issues/49 for more detail.

relevant discuss issues:
* https://discuss.elastic.co/t/custom-transaction-for-single-page-applications-route-changes/190585/

**Comment by vigneshshanmugam** [comment]
Better to work on this after this PR is merged. https://github.com/elastic/apm-agent-rum-js/pull/216

**Comment by jahtalab** [comment]
We should align on the name of the config option with [this](https://github.com/elastic/apm/issues/85) as much as possible.

**Comment by jahtalab** [comment]
We might want to provide enough granularity for disabling specific instrumentations
