### ISSUE TITLE
Fix publish script

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#211]
Bugs:
- Fix the version check script
- ~~Need to add `--access public` to npm publish command (through lerna)~~
- ~~lerna should prompt for 2fa authentication OTP (currently it fails) before each package publish~~

Enhancements:
- The publish scripts should pause before committing the changes for the release, so that we can edit changelog if necessary
- We should check the required env variables before running the actual publish script (currently only `GITHUB_TOKEN`)
- ~~Check if there’s a user logged in for npm~~
- ~~run `release-github` in the same script (#275)~~

**Comment by jahtalab** [comment]
@vigneshshanmugam any thoughts?

**Comment by vigneshshanmugam** [comment]
Lerna issue on 2fa https://github.com/lerna/lerna/issues/1091, There is a branch with the PR for the fix.

**Comment by vigneshshanmugam** [comment]
Prompts for 2FA is fixed in lerna 3.14.0 - https://github.com/lerna/lerna/releases/tag/v3.14.0,
