### ISSUE TITLE
avoid ending page load transaction prematurely 

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#223]
With the recent addition of the new TASK API #194, We have added a check when a task is completed to check if the transaction has ended. With the result of this check `detechFinish` which is called during `removeTask`, We are closing the page load transaction prematurely. 

code where its broken - https://github.com/elastic/apm-agent-rum-js/blob/829ffd79b62e8c2dbfe1509050ccff676c9587a8/packages/rum-core/src/performance-monitoring/transaction.js#L150-L156

As a result of that, most of our resource timing and navigation timing information is lost and our marks is missing lots of useful information. 
<img width="226" alt="Screenshot 2019-03-20 at 15 48 02" src="https://user-images.githubusercontent.com/3902525/54693992-d6bc8e80-4b27-11e9-8f8f-5bb207bd47cf.png">

**Comment by jahtalab** [comment]
I think the mark issue is note related to this I've explained why that happens here: https://github.com/elastic/apm-agent-rum-js/issues/221
