### ISSUE TITLE
Provide an analysis of the final bundle size

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#228]
Currently the bundle size [check fails on travis](https://travis-ci.org/elastic/apm-agent-rum-js/jobs/509429962#L582). We should do a detail analysis of the bundle (webpack-bundle-analyzer can help) and provide the report in this issue.

- [x] Provide the report from webpack-bundle-analyzer here
- [x] Are there any immediate steps we can take to reduce the size of bundle?
- [x] Update the check bundle size test if necessary

**Comment by jahtalab** [comment]
There's an unrelated [failure](https://travis-ci.org/elastic/apm-agent-rum-js/jobs/509480226#L574) of the bundle size check at the moment. We should fix that first.

**Comment by vigneshshanmugam** [comment]
The failure about unauthorised is a known issue because of our own forks and secure tokens.

**Comment by jahtalab** [comment]
But the failure is happening on the main repo's master branch. Is there any way we can avoid that?

**Comment by vigneshshanmugam** [comment]
The reason it fails is because bundle size is trying to add a comment to a PR, but instead its not a PR and its a regular master build. This is why I mentioned that we should not run bundlesize check on master branch.

**Comment by vigneshshanmugam** [comment]
Seems to be bundlesize issue, Track it here https://github.com/siddharthkp/bundlesize/issues/93

**Comment by vigneshshanmugam** [comment]
For now i have deleted the bundlesize token in the travis env to get rid of this error. https://travis-ci.org/elastic/apm-agent-rum-js/jobs/509480226#L574

**Comment by vigneshshanmugam** [comment]
Analyzer report. 
<img width="1400" alt="Screenshot 2019-03-27 at 11 54 40" src="https://user-images.githubusercontent.com/3902525/55070737-33b7c780-5087-11e9-934d-593abc1fb46f.png">

**Comment by vigneshshanmugam** [comment]
I did open few PR's to get some immediate wins on the bundle size, Closing this issue in favor of #159. 

Please follow the linked PR's from the other issue.
