### ISSUE TITLE
Remove trailing from serverUrl

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#248]
If the `serverUrl` is set with a trailing slash the requests made to the APM server would fail the CORS check because the APM server responds with 301 for request that look like `http://localhost:8001///intake/v2/rum/events`. 

We should remove the trailing slash from the serverUrl. 

Related: elastic/apm-agent-rum-js#86

**Comment by vigneshshanmugam** [comment]
Closed by #216
