### ISSUE TITLE
Capture console logs when running tests

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#266]
Failures such as [this](https://github.com/elastic/apm-agent-rum-js/issues/240) are quite difficult to debug since it only happens occasionally on saucelabs (not locally) and to make things more complicated saucelabs doesn't capture console logs. 

We can implement some of these solutions to make debugging a bit easier:
- We can print console logs into the DOM, they would show up in the video of the running test captured by saucelabs. This even works in legacy browser.
- We can capture logs and store them in elasticsearch along with build and test session identifiers so that they can be search discovered quickly. We should be careful not to interfere with the running test.

**Comment by vigneshshanmugam** [comment]
I am not in favor of complicating our stack by introducing elasticsearch for the test pipeline. We could leverage other solution. Going to investigate a bit on this today.
