### ISSUE TITLE
Use window.addEventListener instead of window.onerror

### ISSUE THREAD

**Issue by palci12** [elastic/apm-agent-rum-js#267]
Hi. We use apm-agent in many different applications. Some have their own onError listener in window.onerror. When apm-agent starts it overwrites previous onError listener and vice-versa. 
Isn't it better to use window.addEventListener('error', fn) instead of window.onerror? 
Maybe make it configurable?

**Comment by vigneshshanmugam** [comment]
Thanks for creating the issue, Since 4 we dropped the support for IE 10 and lesser. Its safe to use addEventListener as suggested. Have opened the PR for the same.
