### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by TerrenceMiao** [elastic/apm-agent-rum-js#285]
A Next.js / ReactJS app, with "@elastic/apm-rum": "^4.0.2", on the client side, browser window is defined. In line:

```
apm.setInitialPageLoadName("bills");
```

error thrown:

```
node_modules/@elastic/apm-rum-core/dist/lib/index.js:28
import ErrorLogging from './error-logging';
^^^^^^

SyntaxError: Unexpected token import
```

**Comment by jahtalab** [comment]
Thanks for reporting the issue @TerrenceMiao. We have identified the problem and we will release a new version to address it soon.

**Comment by jahtalab** [comment]
We have released version `@elastic/apm-rum@4.1.1` which should resolve this issue. Please feel free to reopen if the issue persists.

**Comment by melfebulu** [comment]
ERROR in build.js from UglifyJs
Unexpected token: punc (}) [./node_modules/@elastic/apm-rum-core/src/common/utils.js:91,0][build.js:668,4]

**Comment by melfebulu** [comment]
but is ok if use old //import {init as initApm} from 'elastic-apm-js-base'

**Comment by jahtalab** [comment]
Thanks for reporting the issue, I've created #426 to address this!
