### ISSUE TITLE
iphone5 is not work

### ISSUE THREAD

**Issue by caowenhai888** [elastic/apm-agent-rum-js#291]
iphone5 is not work

Can you support it?

thanks very much！

![image](https://user-images.githubusercontent.com/863177/59504241-1996c400-8ed5-11e9-88d6-84e33177826d.png)

**Comment by vigneshshanmugam** [comment]
Hi @caowenhai888 

Thanks for creating the issue, The agent relies on the Navgation timing API available in the browser to instrument the web application. The API is only available from iOS 8 and above. We cannot support the browser versions below that due to this limitation. 

Hope it makes sense.

**Comment by caowenhai888** [comment]
thanks very much！
