### ISSUE TITLE
replace browserresponsive check in favor of page visibility checks

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#295]
+ Right now we have a scheduled timer running in the background when the agent is started and we check the browser being responsive before the transaction is sent to the APM server.

+ Also that check s run for page-load transaction which we don't even use it for discarding the transaction. It's effectively not useful in many cases. 

+ Instead of this expensive algo, we can simply use the https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API to look for the visibility state and ignore the transaction.

**Comment by jahtalab** [comment]
We need to cover two use-cases:
- If the user moves away from the tab (or to a separate application) and the browser throttles the execution of that tab.
- If the operating system that is running the browser affects the browser that it won't be responsive
