### ISSUE TITLE
CONTRIBUTING docs incorrect/incomplete

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-rum-js#298]
I'm trying to follow the CONTRIBUTING docs to run the tests, running the steps verbatim.

The docs say to run:

```
$ git clone git@github.com:elastic/apm-agent-rum-js.git && cd apm-agent-rum-js
$ npm install
$ npm run bootstrap
```

The `npm run bootstrap` command fails. @jahtalab says that this should be changed to `npx lerna bootstrap`, and that we should be able to get rid of the explicit `npm install` too, as [lerna bootstrap](https://github.com/lerna/lerna/tree/master/commands/bootstrap) takes care of that.

So next I ran `npx lerna bootstrap`, followed by `npm test`. This resulted in a bunch of failed integration tests, apparently because there's I had APM Server running on localhost. That bit is missing from the docs.

I started up a stack with apm-integration-testing, and re-ran `npm test`. Now I'm getting one integration test failure:

```
Failures:
1) integration-test should run integration test
  Message:
    Failed: Integration test failed, error: null, response: 500, body: Chromium revision is not downloaded. Run "npm install" or "yarn install"
  Stack:
    Error: Failed: Integration test failed, error: null, response: 500, body: Chromium revision is not downloaded. Run "npm install" or "yarn install"
        at Request.fail [as _callback] (/home/andrew/projects/apm-agent-rum-js/packages/rum/test/integration/integration-test.spec.js:38:11)
        at Request.self.callback (/home/andrew/projects/apm-agent-rum-js/node_modules/request/request.js:185:22)
        at emitTwo (events.js:126:13)
        at Request.emit (events.js:214:7)
        at Request.<anonymous> (/home/andrew/projects/apm-agent-rum-js/node_modules/request/request.js:1161:10)
        at emitOne (events.js:116:13)
        at Request.emit (events.js:211:7)
        at IncomingMessage.<anonymous> (/home/andrew/projects/apm-agent-rum-js/node_modules/request/request.js:1083:12)
        at Object.onceWrapper (events.js:313:30)
        at emitNone (events.js:111:20)
3 specs, 1 failure
Finished in 0.055 seconds
Integration tests failed: Jasmine tests failed
```

That appears to be related to Puppeteer, and I'm not sure how to resolve that.

**Comment by axw** [comment]
Trying this again. I uninstalled puppeteer, and then ran `npx lerna bootstrap`. Now tests fail because puppeteer isn't installed. Should it be a dev dependency?

**Comment by axw** [comment]
Reinstalling puppeteer manually gets me past that, so I suppose I must have had a botched package install. Not sure easy it is to get into that state, and if it's worth mentioning how to deal with it in contributing...

Next problem:

```
Sauce connect Error Error: Could not start Sauce Connect. Exit code 1 signal: null
    at ChildProcess.<anonymous> (/home/andrew/projects/apm-agent-rum-js/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:559:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

Is that expected, or should the Sauce tests only be run by "npm test" under certain conditions?

**Comment by vigneshshanmugam** [comment]
> Trying this again. I uninstalled puppeteer, and then ran npx lerna bootstrap. Now tests fail because puppeteer isn't installed. Should it be a dev dependency?

Puppeteer is already a dev dependency. I am not sure how that is missed through bootstrap. I could not reproduce it locally even after clean install

Regarding the sauce labs error, We have to set `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` to launch the test. I will update the `contributing.md` to handle this. But users can still run unit and integration tests without any issues.

**Comment by axw** [comment]
> Puppeteer is already a dev dependency. I am not sure how that is missed through bootstrap. I could not reproduce it locally even after clean install

:man_facepalming: I uninstalled locally which removed it from package.json. Anyway it was fine after reinstall as I mentioned above, so let's just ignore this for now. Probably something funky with my machine.

> Regarding the sauce labs error, We have to set SAUCE_USERNAME and SAUCE_ACCESS_KEY to launch the E2E test. I will update the contributing.md to handle this. But users can still run unit and integration tests without any issues.

Sure. But should "npm test" run the sauce labs tests at all if those env vars are not set? Maybe just skip them with a message?
