### ISSUE TITLE
Copy transaction/span context for Error.context

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-rum-js#309]
See https://github.com/elastic/apm-dev/issues/390

**Comment by vigneshshanmugam** [comment]
We already populate the context information for the error object with all available context data from the active transaction, browser metadata and config context that is set through the API. 
https://github.com/elastic/apm-agent-rum-js/blob/0ca1e5f97fd4204d6e93d099a9e10b01217bf920/packages/rum-core/src/error-logging/error-logging.js#L70

**Comment by vigneshshanmugam** [comment]
The error context still does not include the current transaction context information. I have reopened the issue to address this.
