### ISSUE TITLE
Investigate supporting chained exceptions

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#311]
We might need to provide an API for the user to pass multiple Errors. But we need to investigate the possible solutions first.

More detail: https://github.com/elastic/apm/issues/40

**Comment by vigneshshanmugam** [comment]
Closing as its not applicable for JS and both RUM and Node.js agent does not support chained exceptions https://github.com/elastic/apm/issues/40#issuecomment-509576055
