### ISSUE TITLE
addLabel() on span and transaction

### ISSUE THREAD

**Issue by eliaskardel** [elastic/apm-agent-rum-js#315]
I am running the latest version of all components elastic search, Kibana, APM Server, RUM JS agent.

![image](https://user-images.githubusercontent.com/25151768/60958540-d0386980-a306-11e9-80f9-9e3ebab12602.png)

The addLabel() function doesnt give me anything on the other side. I switched on debug in the agent and saw my labels in the developer console. However they seem to not end up in eleastic search.

Code Snipped:

           const transaction = apm.startTransaction('transaction1', 'custom')
            const httpSpan = transaction.startSpan('span2', 'custom')
            httpSpan.addLabels({'test_label' : 'test_label'})
            httpSpan.end()
            transaction.end()

**Comment by vigneshshanmugam** [comment]
@eliaskardel Thanks for creating the issue. It seems to be bug in the mapping of tags-> labels that we introduced while deprecating the API. We will do a fix and release a new version.

**Comment by eliaskardel** [comment]
Thanks for that! Will that fix be released immidiately? I am currently blocked by this.

**Comment by vigneshshanmugam** [comment]
@eliaskardel We released [4.3.0](https://github.com/elastic/apm-agent-rum-js/blob/master/CHANGELOG.md#430-2019-07-11) which fixes this issue. Please let us know if you need any help. Thanks in advance.
