### ISSUE TITLE
[docs] Add supported technologies to the agent doc

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#320]
Few sections that I can think of to include in the docs. 
+ [ ] Different Browser Timing API (Navigation, User, Resource, Paint) that agent supports currently and the caveats in each of them
     - [ ] Caveats like Resource timing info wont be available completely for CORS requests if `Timing-Allow-Origin` header is not present.
    - [ ] User timing spans less than 60ms are discarded. 
+ [x] Frameworks support like React, Angular, Vue, Ember etc. 

Please feel free to edit and add more if I have missed something. /cc @bmorelli25

**Comment by bmorelli25** [comment]
@vigneshshanmugam, can we close this issue? It looks like a lot of this content exists on the [supported technologies](https://www.elastic.co/guide/en/apm/agent/rum-js/current/supported-technologies.html) page.

**Comment by vigneshshanmugam** [comment]
@bmorelli25 Thanks, Yeah let's close this.
