### ISSUE TITLE
Fix file paths in Code coverage reports

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#333]
Currently there are a couple of issues with code coverage report:
- [x] The diff calculation of the code coverage seems wrong, e.g. with adding tests it reports a decrease in the coverage elastic/apm-agent-rum-js#328
- [ ] The file path are wrong in the code coverage report, [example](https://codecov.io/gh/elastic/apm-agent-rum-js/pull/328/src/packages/rum-react/src/get-apm-route.js)

**Comment by vigneshshanmugam** [comment]
First item is not an issue - check this https://github.com/elastic/apm-agent-rum-js/pull/330#issuecomment-512635419

**Comment by jahtalab** [comment]
Is there any way to speed up the code coverage report on the PRs, at the moment it takes a while before there's a report on the PR.

**Comment by vigneshshanmugam** [comment]
Jenkins takes a while to upload the data to code coverage there is actually a wait time involved till the whole Jenkins job is successful, @v1v Can you help here?

**Comment by vigneshshanmugam** [comment]
Okay found it, we can upload code cov as soon as its ready and does not need to wait for CI. 
https://github.com/elastic/apm-agent-rum-js/blob/master/codecov.yml#L3. I am pushing a fix now.
