### ISSUE TITLE
React router with lazy components is not listing errors in Production mode in kibana

### ISSUE THREAD

**Issue by rodrigoslino** [elastic/apm-agent-rum-js#335]
Hi guys! I got something...
React router with lazy components is not listing errors in Production mode in kibana, so I made a example of code to show you with each image example. The last image example shows not working.

In my example I edited some code of repository https://github.com/adamquan/carfront

@jahtalab @adamquan  I worked with your code. 

- React router without lazy is listing errors in Development mode (npm start) - **Works great**
![image](https://user-images.githubusercontent.com/24231369/61421522-cce04780-a8dd-11e9-81eb-aa90c66c50c5.png)

![image](https://user-images.githubusercontent.com/24231369/61421578-031dc700-a8de-11e9-840d-b05c23b661c0.png)

- React router without lazy is listing errors in Production mode (npm run build) - **Works great**
![image](https://user-images.githubusercontent.com/24231369/61421684-7fb0a580-a8de-11e9-838b-ed902aae547c.png)

![image](https://user-images.githubusercontent.com/24231369/61421708-99ea8380-a8de-11e9-8e55-a79592957db1.png)

- React router with lazy is listing errors in Development mode (npm start) - **Works great**
![image](https://user-images.githubusercontent.com/24231369/61426304-5436b680-a8f0-11e9-8b93-9d21bac45940.png)

![image](https://user-images.githubusercontent.com/24231369/61421855-53e1ef80-a8df-11e9-9b68-a7772047a024.png)

- React router with lazy is **not** listing errors in Production mode (npm run build) - **Not Working properly**
![image](https://user-images.githubusercontent.com/24231369/61422134-b38cca80-a8e0-11e9-8c12-e0d73b540f8a.png)

![image](https://user-images.githubusercontent.com/24231369/61422155-ddde8800-a8e0-11e9-9412-af1f4dacc9a8.png)

Can anybody help me, pls?

**Comment by vigneshshanmugam** [comment]
@rodrigoslino  Thanks for creating the issue. Seems like react lazy in production mode logs the error and does bubble up the error event to the window. This is the reason why the agent could not capture the error event by subscribing to window `onerror` listener. You can check React's Behaviour by logging inside global error listeners 

```js
window.addEventListener("error", () => console.log("window error"));

window.addEventListener("unhandledrejection", () =>
  console.log(`Promise rejection`)
);
```

+ In dev - you would see both of the logs in console
+ In production, none of our logs would be printed.
