### ISSUE TITLE
NextJS + React (server-side rendered) Issues

### ISSUE THREAD

**Issue by armenr** [elastic/apm-agent-rum-js#363]
We're running into an issue with APM-RUM. It's pretty straight forward, I'm sure I must be missing something, personally, but any help would be appreciated.

Stated in reductionist terms:

```
_document.js is server-side only and is used to change the initial server-side rendered document markup.

_app.js is client-side only and is used to initialize pages.
```

When I run the app, I get the following log in my shell/terminal:
`APM: Platform is not supported!`

The following code is nested within the code block for the `render()` method within the _app.js page of our NextJS codebase.

```
    if (isClient()) {
      const apm = initApm({
        serviceName: 'NEXT-REACT',
        serverUrl: 'REDACTED_ADDRESS:443',
        metricsInterval: 1,
        transactionSampleRate: 1,
      });
    }
```

To be even more detailed - 

We are using a custom server.js file with this nextJS setup, and in that setup, we also use APM (not RUM) on that server. The server serves the NextJS Server-Side rendered application.

Any help or guidance would be much appreciated! Thank you :)

**Comment by vigneshshanmugam** [comment]
@armenr Thanks for trying out APM and RUM. I believe the client side code is somehow getting initialised in the wrong environment where it fails to pass the platform check. If you can provide me with a test repo/example that would be great. Also how does the `isClient` function look like?

**Comment by armenr** [comment]
@vigneshshanmugam - I got you! Let me pull that together for you, and I'll post back with everything I can possibly provide.

**Comment by devyolawo** [comment]
@armenr @vigneshshanmugam I see the same in my logs for an angular server side rendered app. Looks like it has nothing to do with a client side check. The log statement is placed in the bootstrap() function that gets called on import: https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum/src/index.js

**Comment by vigneshshanmugam** [comment]
@devyolawo Oh yeah thats true, we should probably not even try to run bootstrap on unsupported environments which should remove the noise. Will open a PR to address this. Thanks for finding the root cause :)
