### ISSUE TITLE
Route change not captured for without xhr requests

### ISSUE THREAD

**Issue by sharanraj124** [elastic/apm-agent-rum-js#372]
We are using elastic RUM agent for Ionic and we see the route change being captured when there is a XHR request happening.

However, when there are no XHR requests between the route changes, then we do not see a route change being captured.

Is this intended behavior? Or is it a bug

**Comment by vigneshshanmugam** [comment]
@sharanraj124 The transactions for route-change events should be captured even if there are no XHR requests in the current route-change. Can you share a minimal repro of the issue or set `debug: true` in the initialisation and check what you see in the console logs. 
```js
elasticApm.init({
   // all configs,
  debug: true
})
```

**Comment by sharanraj124** [comment]
@vigneshshanmugam I suppose this [code in performance-monitoring.js](https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-core/src/performance-monitoring/performance-monitoring.js#L241) is the reason for discarding the transaction when there is no span.

    if (tr.spans.length === 0) {
      if (__DEV__) {
        this._logginService.debug(
          `Transaction was discarded! Transaction does not include any spans`
        )
      }
      return false
    }

By default when there is only a route change, there is no span (or XHR).. hence I suppose it is getting discarded. Is my understanding correct?

**Comment by vigneshshanmugam** [comment]
@shahzad31 Yes thats correct. 

 Right now transaction only captures XHR and Fetch spans, we planned to add support for capturing other span types as well https://github.com/elastic/apm-agent-rum-js/issues/268 which might help identify whats happening in the route-change event. 

Please share your thoughts as well.

**Comment by vigneshshanmugam** [comment]
Closing as we have added support for RT as well for route-changes. Let us know if you run in to any issues.
