### ISSUE TITLE
add support for Largest Contentful Paint(LCP) in timeline

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#376]
+ Add support for LCP in addition to the already available marks as part of the page-load transaction. https://github.com/elastic/apm-agent-rum-js/blob/c743f701a1cd65104612461fd19f36faceba5ed4/packages/rum-core/src/common/utils.js#L384-L399

Spec draft - https://wicg.github.io/largest-contentful-paint/
Blog post - https://web.dev/largest-contentful-paint/
Available from chrome 77

**Comment by jahtalab** [comment]
We should also consider if reporting LCP as a span instead is feasible or not!

**Comment by vigneshshanmugam** [comment]
Depends on #478
