### ISSUE TITLE
disable `history` instrumentation on framework specific integrations

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#380]
+ Once the apm agent kicks in, It starts listening to history state transitions and would create automatic resuable transactions whenever there is a `pushstate` event. 

+ On framework specific integrations like React, Angular etc. When there is a route change, we would create a new transaction when the underlying route component path gets changed which also depends on the same history state change. 

As a result, we use the previous transaction and redefine it with the path. We could avoid creating the history transaction in the first place by passing `disableInstrumentations: ['history']` in the init method and let the framework specific integration do the necessary job. 

It is not a huge issue, instead a small optimisation enhancement when we know the user is anyways using our framework integration code.

**Comment by jahtalab** [comment]
The history patch creates the transaction to make sure we capture the route change from its earliest point possible. sometimes even with the use of a framework the lifecycle of the route change starts before the framework broadcast the route change event, this has been an issue with earlier versions of opbeat!

**Comment by vigneshshanmugam** [comment]
Hmmm, do you have any specific case in mind? I did create an issue because both of them create a pushstate event so its a matter of small time mostly in milliseconds before the framework integration kicks in.

**Comment by jahtalab** [comment]
There was similar issue with the order of execution of event handlers in Angular, since the order might not be guaranteed even if we register our event listener for the route change, some other event listener might be get execute earlier!
