### ISSUE TITLE
How to end transaction during window.unload?

### ISSUE THREAD

**Issue by eliaskardel** [elastic/apm-agent-rum-js#402]
Hi guys, 

I would like to measure how much time a user has spent on the page and if he has clicked the submit button. 

`document.querySelector('xxx').onsubmit = function(e){
  window.submitted = true
  }
  
  window.unload = closingCode;
  window.onbeforeunload = closingCode;
  
  function closingCode(){
    stop()
    document.body.onunload       = "";
    document.body.onbeforeunload = "";
  }
  
  function stop(){
    window.in_page_transaction.addLabels({'submitted': submitted})
    window.in_page_span.end()
    window.in_page_transaction.end()
    return null;
  }`

That transaction never reaches the server. If I test it in an environment where the page does not reload after submit, it works. Is that related if the request to the apm server are synchronous or asynchronous, is there anything I can configure here to make it work? 

Thanks

**Comment by vigneshshanmugam** [comment]
We use XMLHttpRequest in async way which means that if you are trying to send the transaction to the APM server during `onbeforeunload ` event, There is no guarantee that the event would reach the server and browsers does not wait for the response. 

You can read more about it https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon#Description, We also have an issue that would address this scenario #195

**Comment by jahtalab** [comment]
Closing this. Please feel free to reopen if #195 doesn't cover your use-case.
