### ISSUE TITLE
ending automatic transactions in a graceful way 

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#404]
Our transaction end detection logic for all transactions type except `page-load` is a bit eager now and might fail to capture spans that happen in the frames that happen after the nextTick. 

During the route-change events, there are multiple ways users would be invoking external API calls, can be sync, concurrent/parallel or even lazy load some components based on the API calls. Right now our framework integrations rely on the internal lifecycle events of the respective frameworks and tries to end the transaction as soon as the component is mounted to the DOM. 

With this approach, we might be able to only capture only the API calls that are requested during the component mounting and might fail to capture calls that are done after the component is mounted to the DOM. 

### Solution 
+ Instead of closing the transaction as soon as the children components are mounted or when the route change navigation is done, We could actively wait and listen for few frames (for now we can listen for 5 successive ticks/animation frames) and decide if we want to close the transaction. 
+ If there are no calls within those 5 ticks, we close the transaction immediately and send it to the APM server. 
+ If there are any spans, assume a call happens on the 3rd frame, then we schedule another 5 frames and end the transaction accordingly. 
+ In order to reduce the noise in the transaction, our transaction would always get time shifted to the last active transaction. Ex - if there are 2 spans that happens in the 2nd tick after the transaction start, we end the transaction with the end time of the longest span and send it to the server. 
+ With our filtering logic, transaction without any spans will not be reported to the server.

**Comment by anotheri** [comment]
jfyi, seems related: `@elastic/apm-rum-react` and particularly `ApmRoute` doesn't work properly with [React.Lazy function](https://reactjs.org/docs/code-splitting.html#reactlazy), b/c it finishes transaction w/o any span although they go right below, see debug console log screenshot: https://take.ms/cPa3l

**Comment by vigneshshanmugam** [comment]
@anotheri Thanks for trying out the react package. I am surprised that it does not work for React.Lazy since we have an E2E test which catches the spans inside the transaction for the lazy route. Could you please provide an example of how you are using the lazy component with react package? 

E2E test I was referring to https://github.com/elastic/apm-agent-rum-js/blob/38d2f6af8d8d12f4ac5fca71729700b2b1ef1748/packages/rum-react/test/e2e/with-router/general.js#L105-L108

**Comment by anotheri** [comment]
@vigneshshanmugam thank you for quick answer. 

My example is pretty straightforward (based mostly on react docs example):
```
import React, { lazy, Suspense } from 'react';
import { Router, Route, Switch } from 'react-router-dom';
import { ApmRoute } from '@elastic/apm-rum-react';
import LoadingSpinner from './components/shared/LoadingSpinner';

const LazyPage = lazy(() => import('./containers/LazyPage'));

export default () => (
  <Router>
    <Suspense fallback={<LoadingSpinner />}>
      <Switch>
        <ApmRoute path="/lazy" component={LazyPage} exact />
      </Switch>
    </Suspense>
  </Router>
);
```

There are more routes and components for sure, but you've got the idea i believe. And as far as i can see in that **E2E test: it doesn't use `ApmRoute` for lazy component**, but it uses native react-router `Route` with [manually wrapped into `withTransaction` function component](https://github.com/elastic/apm-agent-rum-js/blob/38d2f6af8d8d12f4ac5fca71729700b2b1ef1748/packages/rum-react/test/e2e/components/manual-component.js#L60).

Is that the only way to work with `React.lazy` function?

**Comment by anotheri** [comment]
UPD: and I can confirm that `withTransaction` wrapper works as expected with `React.lazy` function.

**Comment by vigneshshanmugam** [comment]
Had a quick look, it seems like a bug and I will create a new issue to track it. Thanks a lot @anotheri for providing lot of details :)

**Comment by vigneshshanmugam** [comment]
Had a discussion with @jahtalab and we have agreed for wait for couple of frames and adjust the transaction end timings to previous time if no interesting events occur within the waited frames.
