### ISSUE TITLE
Replace Selenium for e2e testing with Headless Chrome (WebdriverIO works with Headless Chrome)

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#41]

**Comment by vigneshshanmugam** [comment]
@hamid Can we close this issue? since we migrated away from selenium and using saucelabs for e2e currently?

**Comment by vigneshshanmugam** [comment]
Done already with webdriver. Other minor info can be tracked here https://github.com/elastic/apm-agent-rum-js/issues/176
