### ISSUE TITLE
custom transaction post onload must not get redefined after route change. 

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#411]
+ After the page-load transactions are reported to the APM server, if there are tasks that happens after `onload`, They are grouped under `Unknown` and `Custom` transactions. 

+ On SPA, if there is a transition to new page, the previous transaction gets redefined with new path as transaction name and `custom` as transaction type which is wrong since we are capturing the post onload spans/tasks inside the new page view. 

+ Instead we should empty the transaction queue and report them to the server immediately or queue them to get posted along with the new route change transaction.

**Comment by vigneshshanmugam** [comment]
Can be solved by #334

**Comment by jahtalab** [comment]
The Transaction created by the startSpan method should be with type `temporary` instead of custom

**Comment by jahtalab** [comment]
We should improve the reusability logic for this to be resolved!

**Comment by jahtalab** [comment]
Just had a call , in transaction service we should change the startSpan method to manually create a reusable transaction with the type `temporary` and at the end of the transaction we should check the type and if it's still `temporary` we should discard it.

We might need to change the addTask method as well to either use the current transaction or create a temporary transaction.

We should also reduce the reusability threshold to 3 seconds (or we can experiment with different values to find the best trade-off)

**Comment by jahtalab** [comment]
We should also introduce the type priority, e.g. `page-load` type takes priority over `route-change`. The priority would be something like: `['page-load','route-change','custom','temporary']`
