### ISSUE TITLE
Fix Code coverage report's file path

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#417]
Currently the code coverage report posted in PRs (e.g in #412) doesn't show the report correctly and the error message is that file path is wrong.

**Comment by jahtalab** [comment]
@v1v , @kuisathaverat Is there anything that can be done in regards to this?

**Comment by kuisathaverat** [comment]
@jahtalab it is something that happens randomly and only on PRs for some reason CodeCov does not calculate correctly the base commit to comparing. It is an issue in CodeCov, so we do not have too much to do here, however, I remember that we change something in the dotnet agent to improve the behavior https://github.com/elastic/apm-agent-go/issues/384#issuecomment-452622602 we can do the same
https://github.com/elastic/apm-agent-dotnet/blob/master/codecov.yml

on other agents the comments on PRs are disabled
https://github.com/elastic/apm-agent-nodejs/blob/master/.codecov.yml
