### ISSUE TITLE
Elastic APM agent ends the current transaction as soon as it encounters an ajax call

### ISSUE THREAD

**Issue by jaisusasi** [elastic/apm-agent-rum-js#421]
I am starting a custom transaction and a custom span and it ends immediately if there is an ajax call in the code. 

 rumTransactionLaptopUpload = elasticapm.startTransaction("test name", "testtype");rumSpanLaptopUpload = elasticapm.startSpan('Start', "span type");
//when i consolelog the transaction, it shows{ended:true}
 $.ajax({
                url: "/job",
                type: 'POST',
                data: {
                    data: {
                        "type": "test"
                    }
                },
                success: function (data) {
                   //show/hide elements in the page and invoke another method which invokes a REST API 
                },
                error: function (xhr, textStatus, errorThrown) {
                  //do something
                }
            });

Any thoughts

**Comment by jahtalab** [comment]
Thanks for reaching out @jaisusasi,

We have the issue #334, to address this problem. In the mean time, you should be able to use our experimental task API to avoid the transaction being ended early. Something like:

```
var tr = elasticapm.startTransaction("test name", "testtype")
var taskId = tr.addTask()

// ....

tr.removeTask(taskId)
```

As long as the transaction has active tasks it won't be ended automatically unless either the task is removed or the `Transaction.end()` is called.

Please subscribe to #334 for updates regarding this problem. Closing this one.
