### ISSUE TITLE
Provide flags for capturing various types of timing

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#434]
Following elastic/apm-agent-rum-js#423 and #412, we should provide flags in transactions that controls capturing of various timings:

* Navigation timings 
* Resource timings
* Agent marks
* User timings
* Soft navigation
* ~~break down metrics~~ -> Decided to use the break down metrics config option

We can provide one flag for all or multiple flags. These flags should be disabled by default and only explicitly enabled for transactions if necessary. Note that this means that in custom transactions these flags will remain in their default state which is disabled!

**Comment by vigneshshanmugam** [comment]
Already done, the flag is `captureTimings` which is enabled only for `page-load` and `route-change` which are managed transactions.
