### ISSUE TITLE
[docs]: Provide explanation for automatically created spans

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#435]
The RUM agent automatically adds some spans to transactions. We should detail what they are and what the time for those spans signifies. Some of these spans:

* Navigation timing spans
* Resource timing spans

**Comment by roncohen** [comment]
cc @bmorelli25

**Comment by vigneshshanmugam** [comment]
We already have an issue which talks about adding docs for both navigation and resource timing as part of supported technologies document https://github.com/elastic/apm-agent-rum-js/issues/320

**Comment by vigneshshanmugam** [comment]
NT and RT information are covered already https://www.elastic.co/guide/en/apm/agent/rum-js/current/supported-technologies.html#page-load-metrics, We will track the other metrics in #320. Closing this issue
