### ISSUE TITLE
'apm-rum-angular' ApmService is not initialized with router and route in production build of Angular 7

### ISSUE THREAD

**Issue by railsstudent** [elastic/apm-agent-rum-js#437]
I cloned https://stackblitz.com/edit/angular-router-basic-example-grz785 demo, upgraded angular version to 7 and apm-rum-angular to 0.1.1 to satisfy devironment environment at work.

Run ng build --prod to build project and serve the production build by http-server.  "Uncaught TypeError: Cannot read property 'events' of undefined" error message is logged in console log.

After further investigation,   undefined router and undefined route is passed to the constructor of ApmService. (https://github.com/elastic/apm-agent-rum-js/blob/28df070ed4001d1e3ee3fcb929364e5960339793/packages/rum-angular/src/apm-service.ts#L43)

this.router.events throws error since this.router is undefined.
(https://github.com/elastic/apm-agent-rum-js/blob/28df070ed4001d1e3ee3fcb929364e5960339793/packages/rum-angular/src/apm-service.ts#L65)

Test repo: https://github.com/railsstudent/apm-rum-angular-routing-failed

Please kindly help!

**Comment by vigneshshanmugam** [comment]
@railsstudent Apologies for the delay. Had a quick look, seems like an issue with our distribution file. Will get back with more details and update here.
