### ISSUE TITLE
Improving instrumentation of API calls (AJAX & Fetch)

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#441]
Our XMLHttpInstrumentation currently instruments most of the cases except for two scenarios
+ When the request times out, we dont listen for `timeout` events
+ When the request errors, `error` event

Also both our Fetch and XHR instrumentations depend on our custom end Task API logic which figures out when the particular fetch/ajax has ended. One of the issue with this is the timings calculated from those does not correctly reflect the picture and might create misinterpretation to the users. I have explained in detail on this issue elastic/apm-agent-rum-js#145 

To capture it on the correct way, We can still inject the trace context propagation headers as we need it to send the headers to backends agents. But we can always rely on the Resource Timing API data instead of manually calculating using the Task API. We can keep the Task API as it can be useful for checking the transaction ended logic and only change the timings calculation.

**Comment by jahtalab** [comment]
@vigneshshanmugam , Let's discuss using the Resource timing approach a bit more in detail, It seems to me that getting the resource timing of a particular xhr with only relying on the URL does not guarantee uniqueness!

**Comment by vigneshshanmugam** [comment]
Ofcourse the entries are just arrays and they just get added to the Performance Entries array as soon as the request finishes and there are couple of scenarios where the performance entry might not be available due to
+ request aborts
+ CORS 
+ Resource entries buffer being full

So to do it correctly, we have to get the entry as soon as the call finishes and compare the end times and use the max of our current end vs the responseEnd. Also with the use of resource timing infomation, we can also calculate the transfer size and encoded/decoded body size which is already supported for the page load navigation transaction.

**Comment by jahtalab** [comment]
Querying (and filtering) the timings every time a XHR finishes could be a very expensive operation. 
I don't think we should do it right after the request finishes. There's a possibility to perform this operation before sending the transaction but even that has its draw backs, e.g. performance implications and the uniqueness issue.

We should also consider patching the necessary APIs to improve XHR timings!

**Comment by vigneshshanmugam** [comment]
We don't need to query/filter, There is an API for that `performance.getEntriesByName(xhr/fetch url)` which is just a lookup of the entry and we can use that. 

> We should also consider patching the necessary APIs to improve XHR timings!

It wont work since the responses are streams and you would have to clone the stream in memory which would create memory leaks since we have to buffer the whole response. The only smooth way to get the correct data is already provided by the browser and it's using Resource timing API.

**Comment by vigneshshanmugam** [comment]
Timeouts case is already fixed by #871 and task issue is covered by #145
