### ISSUE TITLE
[Bug] Wrong origin check for relative URLs

### ISSUE THREAD

**Issue by andryianets** [elastic/apm-agent-rum-js#444]
For API calls in our application we're using relative urls: 
```
fetch('api/packages/getAll', {...}).
```

For that calls 'elastic-apm-traceparent' header is missing.

After research, we found out that origin is not correct for those calls:

<img width="507" alt="Screen Shot 2019-09-28 at 23 58 44" src="https://user-images.githubusercontent.com/18569848/65829440-45845c80-e2ae-11e9-80b4-4b8fd13b69a5.png">

checkSameOrigin(...) returns false for such kind of urls (not absolute).

https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-core/src/performance-monitoring/performance-monitoring.js#L140

Now we're using a "hacky" tmp solution:

```
initApm({
    ...
    distributedTracingOrigins: ['https://api'],
     ...
});
```

**Comment by vigneshshanmugam** [comment]
@andryianets Thanks for reporting the issue, Will have a look in sometime and open a PR to fix the same.
