### ISSUE TITLE
[docs]: Document starting managed custom transactions

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#455]
We should document how to create managed custom transactions. The following snippet could be used:

```
apm.startTransaction('name','type', {managed:true})
```

**Comment by vigneshshanmugam** [comment]
Also we should add these points
+ Managed transactions would be reused
+ They will replace the current active transaction if there is one
+ All timings would be captured for that transactions (Resource timings)
+ breakdowns would be captured for them if the `breakdownMetrics` config is set to true.
