### ISSUE TITLE
Issue when installing older version of APM

### ISSUE THREAD

**Issue by praveenkumar1106** [elastic/apm-agent-rum-js#462]
I have installed APM version [4.4.2](https://github.com/elastic/apm-agent-rum-js/releases/tag/%40elastic%2Fapm-rum%404.4.2) but apm-rum-core is installed as newer version and causing breakage due to this [changeset](https://github.com/elastic/apm-agent-rum-js/commit/ef34ccc1f8d8784f31d7ee2e5fb9ba9aac3439d4#diff-b509913a9c4e3babfe69a8c5a3af092cL113)

apm-rum-core has the old registerGlobalEventListener missing and using older version of apm-rum breaks the app. I have updated the dependency version to fix this issue. But this needs to be fixed to avoid future breakages.

**Comment by vigneshshanmugam** [comment]
Marking this as not fixable, installing `apm-rum` would always use the fresh version of `apm-rum-core` and controlling the version of either one would result in breaking the code.
