### ISSUE TITLE
Cyclic Dependency with Angular Router

### ISSUE THREAD

**Issue by deefactorial** [elastic/apm-agent-rum-js#463]
when I add ApmService to providers like example:
```js
  providers: [{
    provide: ApmService,
    useClass: ApmService,
    deps: [Router]
  }],
```
I get:
```sh
ERROR in : Error: Provider parse errors:
Cannot instantiate cyclic dependency! Router ("[ERROR ->]"): in NgModule AppModule
```

**Comment by deefactorial** [comment]
I had to use this ugly work around to get it to work:

```
    service: ApmService;
    constructor(private readonly injector: Injector) { }
    setupAPM(): void {
        const resolvedProviders = ReflectiveInjector.resolve([ApmService]);
        const childInjector = ReflectiveInjector.fromResolvedProviders(resolvedProviders, this.injector);
        this.service = childInjector.get(ApmService);
   }
```
[source](https://stackoverflow.com/questions/41432388/how-to-inject-service-into-class-not-component)

**Comment by benelliott** [comment]
I'm not really sure why they suggest that config. I can get it to work fine without specifying anything in my `providers` and just doing `@Inject(ApmService) apmService: ApmService` in my module constructor.

**Comment by deefactorial** [comment]
I can still confirm this error is present on the latest version 5.6.1
when using `@Inject(ApmService) apmService: ApmService` 
![image](https://user-images.githubusercontent.com/4856696/97497475-c2598e00-1927-11eb-8195-4e901cf29916.png)

**Comment by vigneshshanmugam** [comment]
@deefactorial We published the RUM Angular integration v2 Alpha which includes support for Angular 9 and also fixed the relevant cyclic deps issues. 

```
npm install @elastic/apm-rum-angular@alpha
```

Docs here - https://github.com/elastic/apm-agent-rum-js/blob/cc4aba03d7f843e40f7256ee5a73fb74d4c18c9a/docs/angular-integration.asciidoc
