### ISSUE TITLE
Capture user interactions

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#496]
* We should capture user interactions such as clicks, scrolls, mouse and keyboard (and their delays)
* We should investigate the best way to report and visualize this information (report as part of the active transactions or create a transaction or report aggregated counts and delays )

Todo: 
- [ ] Add documentation

Related:
* https://github.com/elastic/apm-agent-rum-js/issues/407

**Comment by jahtalab** [comment]
Focusing on click event for now, it can either result in a new transaction or in an action that results in some type of task (e.g. XHR), we probably don't need to capture the click callback as a span.
We should use the DOM element to drive the transaction name.

we can also capture aggregate timing for the event handlers like:
```
{
  click: {
   count: 2,
   totalTime: 50
}
}
```

**Comment by alexandreservian** [comment]
Hi, at my work we use apm rum. But I dont know how to use **user-interaction** in the buttons. Example: I had many times to click a button dispach one feach for apiRest. In other test, this same button dispach a new transaction and one span. My question is. How do I use correctly  **user-interaction**. And How do I define the name of button EX: "Click - buy-cards'
