### ISSUE TITLE
Support disabling route changes with disableInstrumentations config option

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#499]
Users can remove the framework specific integration to not capture route changes, however, having this option would make configuration easier.

Alternatively we can consider disabling all transactions of a certain type, maybe even in the same config option. example: `disableInstrumentations: ['route-change', 'page-load','other-transaction-type']`

Related:
* https://discuss.elastic.co/t/disableinstrumentations-for-route-change/208598

**Comment by vigneshshanmugam** [comment]
closing as duplicate #678
