### ISSUE TITLE
Release version 5.0.0

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#501]
- [x] Document breaking changes and [upgrade guide](https://github.com/elastic/apm-agent-rum-js/issues/671) (and supported apm server versions) https://github.com/elastic/apm-agent-rum-js/pull/694
- [x] Update Agent/Server compatibility chart: https://github.com/elastic/apm-server/pull/3451
- [x] Review open breaking change issues
- [x] Release version 5.0.0 
- [x] Create 5.x branch
- [x] Add 5.x branch to the doc build: https://github.com/elastic/docs/pull/1769
- [x] Set current on docs to 5.x: https://github.com/elastic/docs/pull/1769

**Comment by jahtalab** [comment]
@bmorelli25 this is our release plan for version 5.0.0, just FYI.

**Comment by bmorelli25** [comment]
5.0 docs are now live on the web: https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/index.html 🎉
