### ISSUE TITLE
easy optimisation wins on Transaction service 

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#522]
+ browserResponsive interval should not be started by default as soon as the transaction is created since we dont want it to run anyways on `page-load` transactions
+ options can be created only when there is an active transaction https://github.com/elastic/apm-agent-rum-js/blob/4732c73bd8513621170f7d647d2d10ffa09cbe57/packages/rum-core/src/performance-monitoring/transaction-service.js#L42-L44

**Comment by jahtalab** [comment]
It seems these were addressed in one of the refactoring on TransanctionService. Please feel free to comment if you think something is missing.
