### ISSUE TITLE
Investigate the Failed sending transactions warning in travis logs

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#526]
Even though these are logged the tests pass. We should make sure the tests fail in this case.

example: https://travis-ci.org/elastic/apm-agent-rum-js/jobs/624100471#L645

**Comment by vigneshshanmugam** [comment]
It seems like this issue has already been fixed and not seen in the recent PR's https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/apm-agent-rum-mbp/branches/PR-866/runs/5/nodes/1585/steps/1835/log/?start=0
