### ISSUE TITLE
Manual instrumentation for React App broken when using latest 4.x agent

### ISSUE THREAD

**Issue by bvader** [elastic/apm-agent-rum-js#532]
@jahtalab as Requested

Manual instrumentation for React App seems to be broken when using same code with latest agent. 

To reproduce the following components are all configured to run on `localhost`, there is a React front end and two backing Java services. Distributed tracing is set up etc. 

In order to use this test harness the application expects the ELK stack and APM server are expected to be on `localhost` with no security. 

Steps to reproduce. 

1 Have an ELK stack with APM server with no security and no secret token running on localhost

You can do that yourself or use the docker compose found [here](https://gist.github.com/bvader/9665fa7b3bd69457517e41a7c28b4725) and copy the contents into `elastic-apm-compose.yml`

Then run
`TAG=7.5.0 docker-compose -f elastic-apm-compose.yml up`

2 Install and run `car-value-estimator`

```
git clone https://github.com/bvader/car-value-estimator.git
cd car-value-estimator
./run-with-apm.sh
```

3 in another terminal install and run `cardatabase`

```
git clone https://github.com/bvader/cardatabase.git
cd cardatabase
./run-with-apm.sh
```

4 In another terminal install and run the `carfront` React application. Ignore all the warnings I am a React rookie but it will work. Note this is using the previous version of the RUM agent `elastic-apm-js-base`

```
git clone https://github.com/bvader/carfront.git
cd carfront
./install-pkgs.sh 
npm start
```

This is will start and app that looks like this.... 

<img width="1476" alt="Screen Shot 2019-12-15 at 7 24 27 PM" src="https://user-images.githubusercontent.com/15572155/70877052-c0d1e200-1f70-11ea-93c8-d6460876ca31.png">

Start Chrome Developer Tools...and Add a Car or Two
<img width="765" alt="Screen Shot 2019-12-15 at 7 31 19 PM" src="https://user-images.githubusercontent.com/15572155/70877263-a51b0b80-1f71-11ea-84d7-ad760fb2d63a.png">

You should be able to navigate To `Kibana -> APM->Services-> car-front-end -> Transactions -> Add Car `and see a full Distributed Trace for the `Add Car` transaction 
<img width="820" alt="Screen Shot 2019-12-15 at 7 36 27 PM" src="https://user-images.githubusercontent.com/15572155/70877432-4609c680-1f72-11ea-956a-41a3f21a82f8.png">

and the console should look something like this and you can see 

```
Before Start Transaction
logging-service.js:83 TransactionService.startTransaction Transaction {options: {…}, name: "Add Car", type: "Add Car", id: "16e77990dfdcafae", traceId: "cc5781f48903c98af40f1e6af7e11b49", …}
Carlist.js:24 Before Add Car Start Transaction
logging-service.js:83 TransactionService.startSpan POST http://localhost:8080/api/cars external.http
logging-service.js:83 TransactionService.startSpan GET http://localhost:8080/api/cars external.http
Carlist.js:106 Before End Transaction
logging-service.js:83 TransactionService transaction finished Transaction {options: {…}, name: "Add Car", type: "Add Car", id: "16e77990dfdcafae", traceId: "cc5781f48903c98af40f1e6af7e11b49", …}
logging-service.js:83 TransactionService.add Transaction {options: {…}, name: "Add Car", type: "Add Car", id: "16e77990dfdcafae", traceId: "cc5781f48903c98af40f1e6af7e11b49", …}
```

5 Stop the react app and edit `src/rum.js`.  Comment out the first line and uncomment the second line, this will use the new agent 

```
// import { init as initApm } from 'elastic-apm-js-base'
import { init as initApm } from '@elastic/apm-rum'
```

install the new agent package and start the app again

```
npm install @elastic/apm-rum --save
npm start
```

Add another Car or two. 
<img width="756" alt="Screen Shot 2019-12-15 at 7 42 47 PM" src="https://user-images.githubusercontent.com/15572155/70877655-49ea1880-1f73-11ea-8c54-ffdf223cab1f.png">

Go to` Kibana -> APM->Services-> car-front-end -> Transactions -> Add Car ` note that the traces for the RUM are missing however the transaction for the backend services are there 
`Services -> cardatabase-> Transactions-> CarController#save` 

Also Observe that the console that `startTransaction()` appears to be called but the transaction id that is started **9a29faabad5380a5** is not the transaction id that the tasks are apparently being added to **2996ef61d0d009de** , and `Transaction.end() ` does not seem to be actually executed  even though it was called ad executed with the previous agent version. 

```
Before Start Transaction
logging-service.js:58 [Elastic APM] startTransaction(9a29faabad5380a5, Add Car, Add Car)
Carlist.js:24 Before Add Car Start Transaction
backend.js:6 [Elastic APM] addTags deprecated, please use addLabels
r @ backend.js:6
log @ logging-service.js:58
addTags @ apm-base.js:165
addCar @ Carlist.js:26
AddCar._this.handleSubmit @ AddCar.js:22
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:265
executeDispatch @ react-dom.development.js:571
executeDispatchesInOrder @ react-dom.development.js:596
executeDispatchesAndRelease @ react-dom.development.js:695
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:704
forEachAccumulated @ react-dom.development.js:676
runEventsInBatch @ react-dom.development.js:844
runExtractedEventsInBatch @ react-dom.development.js:852
handleTopLevel @ react-dom.development.js:5030
batchedUpdates$1 @ react-dom.development.js:21469
batchedUpdates @ react-dom.development.js:2247
dispatchEvent @ react-dom.development.js:5110
(anonymous) @ react-dom.development.js:21526
unstable_runWithPriority @ scheduler.development.js:255
interactiveUpdates$1 @ react-dom.development.js:21525
interactiveUpdates @ react-dom.development.js:2268
dispatchInteractiveEvent @ react-dom.development.js:5086
logging-service.js:58 [Elastic APM] startSpan(POST http://localhost:8080/api/cars, external.http) on transaction(2996ef61d0d009de, Unknown)
logging-service.js:58 [Elastic APM] addTask(task1) on transaction(2996ef61d0d009de, Unknown)
logging-service.js:58 [Elastic APM] startSpan(GET http://localhost:8080/api/cars, external.http) on transaction(2996ef61d0d009de, Unknown)
logging-service.js:58 [Elastic APM] addTask(task2) on transaction(2996ef61d0d009de, Unknown)
Carlist.js:106 Before End Transaction

```

**Comment by jahtalab** [comment]
Thanks for opening the issue @bvader , I've created a [pull request](https://github.com/adamquan/carfront/pull/3) which should fix this issue please pull these changes into your repo once it is merged.

Will close this one, feel free to reopen if the issue persists.
