### ISSUE TITLE
7.6 feature freeze manual test

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#543]
As the 7.6 feature freeze approaches, we should test the new features to make sure they work properly end-to-end (from the agent to APM UI)

Features to test:
- [Capture XHR request as transactions](https://github.com/elastic/apm-agent-rum-js/issues/60)
  - [x]  APM UI
  - [x]  APM Server
- [Add destination to spans for Service Maps and SIEM feature](https://github.com/elastic/apm-agent-rum-js/issues/490) 
  - [x]  APM UI -> not available at the moment
  - [x]  APM Server

**Comment by vigneshshanmugam** [comment]
tested the ServiceMaps feature on APM cluster, Both Resource and XHR calls are shown correct. Closing the issue.
