### ISSUE TITLE
Strange behavior with time units

### ISSUE THREAD

**Issue by RchrdMgwtz** [elastic/apm-agent-rum-js#560]
I just found the issue that the time units in the waterfall chart in Kibana aren't consistent sometimes. As you can see in the picture, the whole transaction takes about 3 ms, during some HTTP requests are taking more than 100 ms. 

![UnitBug](https://user-images.githubusercontent.com/44870549/71904429-5b83a200-3166-11ea-8ee0-1be72b22963f.PNG)

To reproduce the bug: I created a new Angular app using `ng new` and instrumented my application according to the [reference](https://www.elastic.co/guide/en/apm/agent/rum-js/4.x/angular-integration.html). After reloading the page several times, I got this bug.

**Comment by vigneshshanmugam** [comment]
@RchrdMgwtz Thanks for checking our Elastic RUM. The whole transaction takes about 2997 ms (approx 3 seconds) and HTTP requests are in orders of ms, Can you explain a bit on which spans you are referring to?

**Comment by RchrdMgwtz** [comment]
Oh, shame on me! I just got confused with the "," in the number, thougt that it was a float value. (because in german language you use a "," instead of "."). Sorry for wasting your time.

**Comment by vigneshshanmugam** [comment]
Ahh, I totally get you on the `,` vs `.` separation. No worries :)
