### ISSUE TITLE
🚨🐛 initApm active:false is still sending to the server messing up production data

### ISSUE THREAD

**Issue by nuragic** [elastic/apm-agent-rum-js#566]
Hello,

We have a JS app that's configured like this :

```js
import { apm, init as initApm } from '@elastic/apm-rum';
// ...
initApm({
  serverUrl: '...',
  serviceName: '...',
  serviceVersion: '...'
  active: IS_PRODUCTION, // this is ONLY true when deployed in prod
  environment: 'production',
});
// ...
```

@elastic/apm-rum version is 4.5.0

Even if we are on our local environment doing stuff, and `active === false` we see that errors are sent to the production environment!

We're currently doing a temporary hack to change the `serverUrl` as well to avoid any local logs to be mixed with production logs, but please, give this one some priority, it's really failing a basic expectation.

Thanks! 🙏

**Comment by vigneshshanmugam** [comment]
Thanks for creating the issue, Seems weird. Could you please set debug: true and paste the debug logs? We don't even register the error event listeners when the agent is inactive. 

Are you using the captureError API directly for capturing errors?

**Comment by nuragic** [comment]
Thanks for the quick response!

>Are you using the captureError API directly for capturing errors?

Uhmm yeah I'm using it in some cases, e.g. (react component):

```jsx
componentDidCatch(error) {
  apm.captureError(error);
}
```

> Could you please set debug: true and paste the debug logs? 

What do you mean by `debug: true` ? Perhaps `logLevel: 'debug'` option on the `initApm()`? If so, I've tried but I'm not sure which logs I'd have to copy paste… I haven't seen any related logs on the console...

**Comment by vigneshshanmugam** [comment]
That explains it, Currently `active` flag does not seem to respect the custom API methods, seems like a bug, Will fix it in the next release. Thanks for filing the issue. 

> What do you mean by debug: true ? Perhaps logLevel: 'debug' option on the initApm()? If so, I've tried but I'm not sure which logs I'd have to copy paste… 

yeah `logLevel`: 'debug', its okay we are able to pinpoint to the issue.

**Comment by nuragic** [comment]
Ahh ok cool! Thanks!
