### ISSUE TITLE
Fix building docs locally

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#570]
Even though running locally `./scripts/build_docs.sh`  succeeds, it produces htmls that don't render correctly. The issue seems to be with some missing files:

![image](https://user-images.githubusercontent.com/6134122/72436507-e422c380-37a0-11ea-9aba-a877335b48b4.png)

cc @bmorelli25

**Comment by bmorelli25** [comment]
Hi @jahtalab. I'm assuming you're using `npm run build-docs`? I'm not able to replicate this exact bug. Can you please confirm that your local clone of the elastic/docs repo is up to date?

While testing this however, I did find a separate bug with the docs build script. Maybe the two are related and I just don't see it? Regardless, I've opened https://github.com/elastic/apm-agent-rum-js/pull/573 to address this.

**Comment by jahtalab** [comment]
Hi @bmorelli25, I removed the docs repo locally and the script cloned it automatically so I assume it is up to date. I'll test with that fix to see if the issue is resolved.

**Comment by jahtalab** [comment]
@bmorelli25 , I tested with the new changes but after a few tries and minutes of working (with high cpu usage) it got stuck. I now removed `PREVIEW=1 ` part which resolved the cpu issue but I still have the problem described in this issue.

Just to clarify, this is my process for building docs:
* run `npm run build-docs`
* Make a static http server for the resulting html files, `npm run serve build/html_docs/apm-agent-rum-js/`
* Load `localhost:8000` in the browser

Does that look reasonable?

**Comment by bmorelli25** [comment]
Dang, I still can't replicate. With the latest updates, your step 2 and 3 shouldn't be necessary. `npm run build-docs` should automatically start a server and open `http://localhost:8000/guide/index.html` in the browser. Let's zoom tomorrow if you're still around when I start my day.

**Comment by bmorelli25** [comment]
Fixed in https://github.com/elastic/apm-agent-rum-js/pull/573... Or maybe not, but it is fixed now!
