### ISSUE TITLE
Provide the possibility to run release script without actually publishing (dry-run)

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#598]
This is needed to create an approval stage for [moving the release to CI](https://github.com/elastic/apm-agent-rum-js/issues/518)

cc @v1v , @vigneshshanmugam

**Comment by vigneshshanmugam** [comment]
When you mean dry run, you would like to restore the state of previously tagged changes before we click the approve button? Is that right? 

@v1v Does `lerna version --no-push` work here?

**Comment by v1v** [comment]
I guess we can close this issue as it's now solved with the current merged PR:
- https://github.com/elastic/apm-agent-rum-js/pull/602


#### How does it look like?
- The release from the CI requires two manual steps:
  1 - Build from the Jenkins UI the master branch and select the `release` input parameter from the UI form.
  2 - Approve the release.

The step `2` is the one that actually runs a dry-run release, it's up to the release manager (the one that clicks on the approval) to decide whether to release or abort the release.

If that's what you meant I think we can close this issue

**Comment by vigneshshanmugam** [comment]
I think the current state looks good for now, we can obviously improve on the current tooling once we do few releases.

**Comment by v1v** [comment]
I'll then close it and we can open it again if required or create a new one for the new followups if any :)
