### ISSUE TITLE
Automatically create transactions for AJAX requests

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-rum-js#60]
Currently, only those XHR Requests, which are within a manually created transaction are recorded.

In some frameworks, like JSF you have very little control over the JavaScript so manually creating transactions for button clicks which initiate AJAX requests is not viable. Even if the developer has direct control over the ajax requests, instrumenting a big application would be a lot of effort.

I propose that the RUM agent should automatically create a transaction for XHR Requests in case there is no currently active one. This would make the auto-instrumentation cover more of the application without the user having to programmatically add tracing logic to their application. That, in turn, makes it easier to adopt the RUM agent.

In terms of distributed tracing, it would also bring visibility into where in the frontend a backend request was initiated and how much time the network interaction took.

**Comment by jahtalab** [comment]
Related: https://github.com/elastic/apm-agent-rum-js/issues/461
