### ISSUE TITLE
Not all targets contain the getAttribute function

### ISSUE THREAD

**Issue by kodermax** [elastic/apm-agent-rum-js#622]
Version 4.8.0
![image](https://user-images.githubusercontent.com/590985/74525003-2cb0d680-4f31-11ea-9fb1-857a1ef805ea.png)
![image](https://user-images.githubusercontent.com/590985/74525040-40f4d380-4f31-11ea-8137-02381282e861.png)

**Comment by bjorngi** [comment]
![Selection_109](https://user-images.githubusercontent.com/2196936/74526255-477c4e80-4f23-11ea-8640-1017b59cdeda.png)

Same issue.
 "@elastic/apm-rum": "^4.8.0",
 "@elastic/apm-rum-react": "^0.3.5"

**Comment by atrunelle** [comment]
I was having this issue with `"@elastic/apm-rum-vue": "^0.3.1",` but seems fixed in `"@elastic/apm-rum-vue": "^0.3.2",`

**Comment by vigneshshanmugam** [comment]
We have already fixed the issue https://github.com/elastic/apm-agent-rum-js/pull/625 and released a patched version. Could you try with `@elastic/apm-rum": "4.8.1"` and let us know if it fixes your issue.

**Comment by jahtalab** [comment]
The bug is fixed with version `4.8.1`. Please reopen if there is still an issue.

**Comment by ignatisD** [comment]
If you are getting this issue (`TypeError: target.getAttribute is not a function`) using `@elastic/apm-rum-angular`, it is fixed at version `0.4.3` (which uses `@elastic/apm-rum": "4.8.1"`).
