### ISSUE TITLE
Support multiple services

### ISSUE THREAD

**Issue by rgauny** [elastic/apm-agent-rum-js#654]
We have a micro-frontend in which each team has minified individually and we utilize through an import map. 

Currently the rum agent only supports 1 service which makes it really difficult to divide up manually.

Trying to determine the best strategy here. Typically a thread local would carry the scope for the txn. The possible solutions I have seen are utilizing the zonejs api or creating an apm filter and looking at the stacktrace which seems a bit hacky..

Any ideas?

**Comment by jahtalab** [comment]
Thanks for reaching out @rgauny ,

As you mentioned there's no way set multiple service names with a single agent instance. I would suggest to utilise our [`transaction.addLabels`](https://www.elastic.co/guide/en/apm/agent/rum-js/current/transaction-api.html#transaction-add-labels) to add labels to transactions and filter based on these labels in the UI.

Please let me know which solution works for you.

**Comment by geekysam7** [comment]
Hi @hmdhk, I would like to understand the best way to handle this.

If I understand you correctly then according to you, we we should create custom transactions for this, store it in state somewhere by adding unique label to each transaction. And to end it we get the transaction by filtering out by label? 

Or should we create separate instance for each service? Any ideas will be helpful

**Comment by devcorpio** [comment]
Hi @geekysam7,

Let me know if this comment helps you to have a better idea: 

https://github.com/elastic/apm-agent-rum-js/issues/1197#issuecomment-1094921928

Cheers,
Alberto
