### ISSUE TITLE
Add a note about configuring CORS to getting started

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#66]
if APM server is deployed in an origin different to the page's origin. The browser will make an OPTIONS request to the APM server prior to making the original POST request.

* We should explain why this process is necessary (we can reference https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
* We should also mention that users need to configure the `allow_origins ` in their APM server configuration (by default the APM server allows all origins). 
* We can reference [APM Server - RUM configuration](https://www.elastic.co/guide/en/apm/server/current/configuration-rum.html)
* We should also mention which cross-origin headers are sent and received (browser <--> apm server), this is useful for configuring proxies.
* We should mention that the preflight request will fail if RUM endpoint is disabled on the APM server.

It might make sense to add a guide to the docs and reference it in the getting started.

Any thoughts on this @bmorelli25, @vigneshshanmugam ?

**Comment by vigneshshanmugam** [comment]
@bmorelli25 Do you have time to help with the doc update?

**Comment by bmorelli25** [comment]
Sure, I can help
