### ISSUE TITLE
Exclude/ignore URLs?

### ISSUE THREAD

**Issue by nuragic** [elastic/apm-agent-rum-js#665]
Hello,

I can't find any option in the docs, so my question is: how can I disable the agent sending transactions for certain URLs like e.g. the google analytics one? Right now (by default config) each time an event is sent to the google analytics service via HTTP, another request is made by the agent to report that request... I would expect something like this in the config object:

`excludeOrigins: ['analytics.google.com', 'whatever.org', 'etc…']`

But that option doesn't exist! 😅 Is there anything in place in order to do this?

Thanks!

**Comment by vigneshshanmugam** [comment]
Thanks for using the agent . if you already know the transaction name. You can use this `ignoreTransactions` option to not report these to the server.  
https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#ignore-transactions

**Comment by nuragic** [comment]
Hey thanks for answering! The problem is that I'm not creating custom transactions, it's an automatic one (http-request)... so I don't know the name. 

In general it's good to track all HTTP requests... however, there're origins that we trust, so we don't want to track those requests...

**Comment by vigneshshanmugam** [comment]
When you mean by trused domains (assuming they are third party providers), you can still use the `ignoreTransactions` config since transaction names for third party API calls always have the full URL in the name. 

### Example: 
+ API call to GA -> `GET www.google-analytics.com/event/`
+ API call to same origin -> `GET /event`

**Comment by nuragic** [comment]
Ahh ok, now I see! Got it! Many thanks!

**Comment by Frintrop** [comment]
Hi .. i tried that with reg exp but it looks like apm is ignoring my regexp.
I tried
, ignoreTransactions: ['POST https://recorder.sessionstack.com*','PUT https://recorder.sessionstack.com*']

or 
 ignoreTransactions: ['POST https://recorder.sessionstack.com.*','PUT https://recorder.sessionstack.com.*']

or
ignoreTransactions: [POST https://recorder.sessionstack.com.*,PUT https://recorder.sessionstack.com.*]

or
ignoreTransactions: [.*recorder.sessionstack.com.*]

**Comment by vigneshshanmugam** [comment]
@Frintrop You have to pass in RegExp object and not string. Check the documentation here https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#ignore-transactions

```js
const config = {
   ignoreTransactions: [new RegExp('')]
}
```

**Comment by Frintrop** [comment]
THx. Yes. Solved it.

Von: Vignesh Shanmugam <notifications@github.com>
Antworten an: elastic/apm-agent-rum-js <reply@reply.github.com>
Datum: Montag, 15. Juni 2020 um 12:09
An: elastic/apm-agent-rum-js <apm-agent-rum-js@noreply.github.com>
Cc: Andre Frintrop <andre.frintrop@objectiveit.de>, Mention <mention@noreply.github.com>
Betreff: Re: [elastic/apm-agent-rum-js] Exclude/ignore URLs? (#665)


@Frintrop<https://github.com/Frintrop> You have to pass in RegExp object and not string. Check the documentation here https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#ignore-transactions

const config = {

   ignoreTransactions: [new RegExp('')]

}
