### ISSUE TITLE
Configuration document error?

### ISSUE THREAD

**Issue by Rhuaer** [elastic/apm-agent-rum-js#675]
The [doc](https://www.elastic.co/guide/en/apm/agent/rum-js/4.x/configuration.html#disable-instrumentations) tells me I can set `disableInstrumentations: ['user-interaction']` to stop agent sends user click transaction to apm server.

But it didn't work. When I clicked the page, agent always created user click transaction and sent it to apm server.

When I set `disableInstrumentations: ['eventtarget']`, logService from agent didnt report any user click transaction.

I think the code [here](https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-core/src/common/instrument.js#L45) maybe get something wrong.

**Comment by jahtalab** [comment]
Thanks for reaching out @Rhuaer 

`disableInstrumentations: ['eventtarget']` is the correct way to disable the user interactions, I will make sure that we fix the documentation. Furthermore, I have create [this issue](https://github.com/elastic/apm-agent-rum-js/issues/678) to revise `disableInstrumentations`  to make it simpler to use.
