### ISSUE TITLE
fcpEntry[0] can be undefined if 'first-contentful-paint' is missing from performance.getEntriesByType('paint')

### ISSUE THREAD

**Issue by bjorngi** [elastic/apm-agent-rum-js#680]
@elastic/apm-rum-core version: 4.10.0
OS: Ubuntu 19.10
Browser: Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

After update to 4.10.0 we get an console.error when entering our web application (see below)
```
capture-navigation.js:203 Uncaught (in promise) TypeError: Cannot destructure property 'startTime' of 'fcpEntry[0]' as it is undefined.
    at getFirstContentfulPaint (capture-navigation.js:203)
    at getPageLoadMarks (capture-navigation.js:217)
    at captureNavigation (capture-navigation.js:277)
    at transaction-service.js:248
```

If `performance.getEntriesByType('paint')` only contain 'first-paint' and NOT 'first-contentful-paint' `fcpEntry` will give and empty array and therefor `fcpEntry[0]` will be undefined. This will cause the error when trying to look up `startTime` of undefined.

https://github.com/elastic/apm-agent-rum-js/blob/5e0c9a2acbd8460de5dbbf7827311e0d0f845047/packages/rum-core/src/performance-monitoring/capture-navigation.js#L267

**Comment by jahtalab** [comment]
Fixed by #681
