### ISSUE TITLE
Could not inject distributed tracing header to the request origin XX  from the current origin XX

### ISSUE THREAD

**Issue by wajika** [elastic/apm-agent-rum-js#686]
![123 20200306133725](https://user-images.githubusercontent.com/17058349/76055833-af1c3b80-5faf-11ea-8a82-ae0d7e019a41.png)

rum agent config
![11115834639264200](https://user-images.githubusercontent.com/17058349/76055880-df63da00-5faf-11ea-98dc-e58e9027b362.png)

what should I do？

**Comment by jahtalab** [comment]
Thanks for opening the issue @wajika , the correct config option is `distributedTracingOrigins`, camelCase instead of PascalCase. 

Let me know if this solves the issue, closing for now.
