### ISSUE TITLE
RUM-Agent slows down startup since Angular 9

### ISSUE THREAD

**Issue by Flaxline** [elastic/apm-agent-rum-js#693]
Following situation:
There's an Angular Application with some Protractor e2e-Tests, whose execution is monitored by apm-rum (with a custom implementation of route-monitoring).
These tests and their monitoring worked fine with Angular 8.x and apm-rum agent 4.8.

Since a recent Update to Angular 9 (and later also to apm-agent 4.9), an active monitoring slows down the application to a point where the Protractor Tests fail due to script timeouts. (Does not happen when monitoring is inactive, and did not happen before the updates) - which is now worked around with increased timeouts. 

But the data on RUM server still show very similar durations for page-load transactions, and do not at all reflect any changes in a slower start of the application.

What could case the Application to have such a noticably slower startup when monitoring is enabled, than before?
Thanks for your help!

**Comment by vigneshshanmugam** [comment]
@Flaxline Thanks for bringing that to the attention. We don't have a test suite at the moment to confirm it. Do you have a test application/repository where we can have a look?

**Comment by Flaxline** [comment]
@vigneshshanmugam 
First, thank you for answering and sorry for the delay.
As I can't share the actual code where the issue came up, I tried to recreate the situation in a rather stripped setup: https://github.com/Flaxline/monitoring-slowdown-issue

During creation, I noticed that the issue didn't occur until I added the custom route-monitoring to the project. But as this was already used in the actual application with Angular 8, it still shouldn't be an issue?

So the example does things very similar to the application mentioned in the issue itself. 
It also throws the same timeout error:

> 1) workspace-project App should display welcome message
>  - Failed: script timeout
    (Session info: chrome=80.0.3987.132)
    (Driver info: chromedriver=79.0.3945.16 [...]

The error that may be thrown afterwards, and in the configuration with increased timeouts, is not a problem in the actual app as I can use an existing APM-setup there:

> 4)
>   - Expected [ Entry({ level: WARNING, message: 'http://localhost:4200/vendor.js 64987:23 "[Elastic APM] Failed sending transactions!" Error: http://localhost:8200/intake/v2/rum/events HTTP status: 0
>       at ApmServer._constructError (http://localhost:4200/vendor.js:64041:12)

As stated above, we now work around the issue with increased timeouts, but it'd be nice to know why there's a slowdown since Angular 9.

**Comment by vigneshshanmugam** [comment]
@Flaxline We published the RUM Angular integration v2 Alpha which includes support for Angular 9. Would you be able to test it and let us know if it fixes your problem. 

```
npm install @elastic/apm-rum-angular@alpha
```

You have to make small changes to the initialization code. Docs here - https://github.com/elastic/apm-agent-rum-js/blob/cc4aba03d7f843e40f7256ee5a73fb74d4c18c9a/docs/angular-integration.asciidoc

Please let us know if it fixes your problem.
