### ISSUE TITLE
debug log problem

### ISSUE THREAD

**Issue by Rhuaer** [elastic/apm-agent-rum-js#695]
I use angulr rum agent in my project. I want to show debug log at runtime when I build the project with production mode.

But it doesn't work.

```javascript
if (__DEV__) {
  this._logger.debug(
    `transaction(${tr.id}, ${name}, ${type}) is ignored`
  )
}
```

I think `__DEV__` is always false when i build my project with production mode.
How can i solve this problem?

**Comment by vigneshshanmugam** [comment]
To minimize the noise on production environment, RUM agent will remove all code blocks that are inside the `DEV` flag, You can build your project with NODE_ENV flag set to something other than `production` to keep the dev logs. 

https://github.com/elastic/apm-agent-rum-js/blob/7de5169922dba2cc1e8b6b67c0f98a6b0dee7e71/packages/rum-core/src/env.js#L26
