### ISSUE TITLE
Provide typescript definition

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#70]
There are multiple benefits of providing typings for the users. First generally IDEs have support for typing files and can provide auto-completion even in JS code. It also helps users identify and fix issues related to the API changes.

- [x] Documentation
- [x] Tests to check the definition with actual typescript compiler

Postponed:
- [ ] Run the tests in Jasmine

**Comment by StevenYuysy** [comment]
Is there any progress?

**Comment by jahtalab** [comment]
Had a call with @vigneshshanmugam , We decided to postpone running tests in jasmine. We'll reconsider in the future. A possible solution might be to move the apm-rum package to typescript which also can generate the definition types.
