### ISSUE TITLE
Support path array

### ISSUE THREAD

**Issue by dobesv** [elastic/apm-agent-rum-js#702]
For `path`, react-router accepts "Any valid URL path or array of paths that path-to-regexp@^1.7.0 understands.".  But `ApmRoute` expects a string.

I suppose supporting an array of paths would require checking which path actually matched, which is a bit of a pain the way that `ApmRoute` is currently doing things.

I think it would be better if there was another component which just created a transaction while mounted, e.g.

```
<Route>
   <ApmTransaction name={path} type="route-change">
      ...
   </ApmTransaction>
</Route>
```

This would make it easier to use Apm in other routing systems besides react-router as well as helping solve this current issue.

**Comment by dobesv** [comment]
Here's a class that implements the idea above:

```
import { apm } from '@elastic/apm-rum';
import React, { Component, ReactNode } from 'react';

export interface ApmTransactionProps {
  children: ReactNode;
  name: string;
  type: string;
}

declare module '@elastic/apm-rum' {
  class Transaction {
    detectFinish(): void;
  }
}

const startTransaction = (name: string, type: string) =>
  apm.serviceFactory.getService('ConfigService').isActive()
    ? apm.startTransaction(name, type, {
        canReuse: true,
        managed: true,
      })
    : null;

export default class ApmTransaction extends Component<ApmTransactionProps, {}> {
  /**
   * We need to start the transaction in constructor because otherwise,
   * we won't be able to capture what happens in componentDidMount of child
   * components since the parent component is mounted after child
   */
  transaction = startTransaction(this.props.name, this.props.type);

  componentDidMount() {
    /**
     * React guarantees the parent CDM runs after the child components CDM
     */
    if (this.transaction) {
      this.transaction.detectFinish();
    }
  }

  componentWillUnmount() {
    /**
     * It is possible that the transaction has ended before this unmount event,
     * in that case this is a noop.
     */
    if (this.transaction) {
      this.transaction.detectFinish();
    }
  }

  /**
   * If props change we need to start a new transaction before rendering
   * or mounting any children.
   */
  UNSAFE_componentWillUpdate(nextProps: ApmTransactionProps) {
    if (
      nextProps.name !== this.props.name ||
      nextProps.type !== this.props.type
    ) {
      this.transaction?.detectFinish();
      this.transaction = startTransaction(this.props.name, this.props.type);
    }
  }

  render() {
    return React.isValidElement(this.props.children) ? (
      this.props.children
    ) : (
      <>{this.props.children}</>
    );
  }
}

```

**Comment by jahtalab** [comment]
Hi @dobesv , 

Thanks for reaching out.

This seems like something that can be done via `withTransaction` method. This method effectively warps the original component and creates a transaction when mounted. You can find more information on [instrumenting individual components](https://www.elastic.co/guide/en/apm/agent/rum-js/current/react-integration.html#_instrumenting_individual_react_components) part of our docs. 

Does this help in your case?

**Comment by dobesv** [comment]
@jahtalab 

It won't handle multiple paths on a route.

It is hard to use when you have a custom Route component wrapper.

**Comment by vigneshshanmugam** [comment]
Moving back the milestone to `7.8` as it's already done and PR can be merged.
