### ISSUE TITLE
Breaks in older browsers / browsers without performance API

### ISSUE THREAD

**Issue by dobesv** [elastic/apm-agent-rum-js#707]
If the browser doesn't provide the `performance` API, you get an error on page load:

![image](https://user-images.githubusercontent.com/327833/76796735-50ae4480-6789-11ea-8c8d-0644762b0f85.png)

It seems like the check there should check for both `window` and `performance`.

**Comment by vigneshshanmugam** [comment]
Did you try with the latest release [`4.9.1`] (https://www.elastic.co/guide/en/apm/agent/rum-js/current/release-notes-4.x.html#release-notes-4.9.1), We released a fix that should address this issue. https://github.com/elastic/apm-agent-rum-js/pull/681

**Comment by dobesv** [comment]
I didn't have that version yet, I'll try it.  But looking at the code, I don't think it will help, since the code assumes `performance` is defined.  See #708 for a possible fix.

**Comment by jahtalab** [comment]
@dobesv , what browser/version are you seeing this error on?

**Comment by vigneshshanmugam** [comment]
@dobesv We have checks in place when we use the functions from `performance` object, so that check shouldn't be required IMO. Can you share the original stack trace and also test with the latest version? Plus browser version also helps as pointed out by @jahtalab

**Comment by dobesv** [comment]
@vigneshshanmugam The error is `performance is not defined`.  iOS Safari 8

**Comment by dobesv** [comment]
The problem is that the variable `performance` is not actually available - not that the property of that object are being accessed.

**Comment by vigneshshanmugam** [comment]
@dobesv Thanks for the details, Indeed seems to be a bug. Even though we don't support that browser officially, I am happy to land the fix and not break those versions as its the way to go.
