### ISSUE TITLE
CI: The test process should adjust the pipeline according to changes in the PR

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#715]
Sometimes depending on the changes made in a PR, there is no need to run all the checks for it. As a first step, if a PR only contains changes to doc files then only the docs build should run and nothing else.

@elastic/observablt-robots , a similar change was recently introduced for kibana, can we also do this?

**Comment by cachedout** [comment]
It seems like we should be able to achieve this with a combination of a dedicated docs build stage that [only runs when certain files are changed ](https://jenkins.io/doc/book/pipeline/syntax/#when) and a [post section in that stage ](https://jenkins.io/doc/pipeline/tour/post/)that bails out of the pipeline after it's done.

@kuisathaverat and @v1v do you have other/better ways to achieve this?

**Comment by vigneshshanmugam** [comment]
Other systems solve this by following this pattern `[skip ci]`. At-least Travis supports this patter. Can we do something similar for Jenkins?

**Comment by v1v** [comment]
We got something lighter for the apm-server, the build will happen always
but all the stages that are not required to be launched for the docs are
skipped.

In fact we got something similar but the other way around for the benchmark
in the apmagent rum. :)


Not sure how it has done for the Kibana, but the above approach could be
done pretty quickly.

What do you think?

Cheers

**Comment by jahtalab** [comment]
@v1v , that sounds good! Are the skipped checks still visible in the PR?

**Comment by v1v** [comment]
> @v1v , that sounds good! Are the skipped checks still visible in the PR?

Yes, with a gray color in the CI Pipeline, but they won't be visible in the GitHub PR checks

**Comment by v1v** [comment]
> @kuisathaverat and @v1v do you have other/better ways to achieve this?

@cachedout, that's what we've done for other cases, see:
- https://github.com/elastic/apm-server/blob/174985dcebae11cf41c91be5fceb3a2622ca8d25/Jenkinsfile#L78-L79 to look for the changelist
- https://github.com/elastic/apm-server/blob/master/Jenkinsfile#L98-L104 for the when logic in each stage
