### ISSUE TITLE
Lint check stay on unreported when there is only changes on docs

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-rum-js#726]
we recently made a change to the ci that only runs docs builds if there are only docs changes in the PR, but this causes some items on the checklist to have unreported status. 

![image](https://user-images.githubusercontent.com/5400788/77650743-2ec47700-6f6c-11ea-81c3-cad5d2fbef62.png)

Also, Integration Test stage ran but we don’t need that on docs changes to be clear both Lint and Integration Test should not appear on the checklist

**Comment by kuisathaverat** [comment]
this is because the lint stage is marked as mandatory, so because there is only changes on docs the check is not reported but GitHub waits for it because it is mandatory.

<img width="793" alt="Screenshot 2020-03-26 at 14 17 43" src="https://user-images.githubusercontent.com/5400788/77651092-95e22b80-6f6c-11ea-8179-8351f5f2fc7f.png">

The solution is to nor require the lint check or execute always the lint stage. I think that run the lint stage always is fair because is quick.

**Comment by vigneshshanmugam** [comment]
> I think that run the lint stage always is fair because is quick.

++
