### ISSUE TITLE
Unable to upload sourcemap to Elastic Cloud Server

### ISSUE THREAD

**Issue by footyapps27** [elastic/apm-agent-rum-js#727]
I am using the `apm-agent-rum-js` for app analytics & error reporting in my app.

For error reporting, I am unable to upload source maps to the **Elastic Cloud Server**.
**@elastic/apm-rum version: 5.0.0**

My curl request is:

`
curl -v https://{actualUrl}.aws.cloud.es.io:443/v1/sourcemaps -X POST \
  -F sourcemap="main.3d28df832297ff6d63a8.esm.js.map" \
  -F service_version="0.0.0" \
  -F bundle_filepath="http://localhost:4200/main.3d28df832297ff6d63a8.esm.js" \
  -F service_name="{serviceName}" \
  -H "Authorization: Bearer {bearerToken}"
`

{bearerToken} = APM Server secret token

I have placed this script in the same file as dist output.

I keep getting `{
  "error": "404 page not found"
}`, though the connection was successfully established.

**Comment by footyapps27** [comment]
@vigneshshanmugam 

Please confirm if this is the correct way to upload source maps.

**Comment by vigneshshanmugam** [comment]
@footyapps27 The APM Server upload urls seems to be wrong from your script. 

It should be **https://{actualUrl}.aws.cloud.es.io:443/assets/v1/sourcemaps**

**Comment by vigneshshanmugam** [comment]
Please reopen if you see any issues.

**Comment by footyapps27** [comment]
@vigneshshanmugam Works.
Thank you for your help. :)
