### ISSUE TITLE
Anguar Package Format

### ISSUE THREAD

**Issue by chriscarpenter12** [elastic/apm-agent-rum-js#757]
I had opened a [PR which was closed](https://github.com/elastic/apm-agent-rum-js/pull/746) to address multiple issues with the Angular library namely using the `ng` cli to create a package following the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview). The `ng` cli creates an output that contains a `*.metadata.json` file which Angular uses for AOT compilation which is currently missing. It was a work in progress. It was a start at adding an actual Angular structure to the `rum-angular` lerna package. 

It was also meant to address multiple other issues. Like proper [e2e tests](https://github.com/elastic/apm-agent-rum-js/issues/450), and [protractor timeout issues](https://github.com/elastic/apm-agent-rum-js/issues/693) which you can't test because you don't have an Angular app defined. The few apps we've tested adding the APM Angular library cause all our Protractor tests to timeout.

As well as fixing improper service usage/declaration. The current documentation has users define the `ApmService` in the app module providers with a router dependency. This is not correct for an Angular library. While it works you should not have to define it like this since you're using `providedIn: 'root'` in the `Injectable`. Which lead to odd [issues like this](https://github.com/elastic/apm-agent-rum-js/issues/463).

This:
```
@NgModule({
  ...
  providers: [{ provide: ApmService, useClass: ApmService,deps: [Router]}]
  ...
})
export class AppModule {
  constructor(@Inject(ApmService) service: ApmService) {
    // API is exposed through this apm instance
    const apm = service.init({...})
  }
}
```
becomes this
```
@NgModule({
  ...
  imports: [ApmModule]
  ...
})
export class AppModule {
  constructor(service: ApmService) {
    // API is exposed through this apm instance
    const apm = service.init({...})
  }
}
```

I defined a task list of outstanding things that needed addressed, but it was a start to fix these things.

**Comment by vigneshshanmugam** [comment]
@chriscarpenter12  Sorry for the delay in responding and Thanks for the detailed information and for the PR as well. Lots of good points in there. I really like the idea of the `ApmModule` as it would address the improper use of Angular Dependency Injection. May be we can isolate each problems and solve it individually

1. Keep the existing build setup((using Babel (Typescript) and Webpack)) and we expose `ApmModule` from the Agent and not via `ng` CLI as it bring in lots of unnecessary changes like folder restructuring and deps which is not worth to pursue.

2. Can we add an exta build step and  generate the `*.metadata.json`  and types using `ng` and check-in inside the source. Would that help solve the AOT problem? 

3. We can add a new PR for the End to End app using the `ng` generated app and keep it at the same place as `packages/rum-angular/test/e2e/` and that way we can test for timeout issues you have mentioned. 

Let me know your thoughts? We can also bring back your PR and work on it together? Happy to collaborate.

**Comment by chriscarpenter12** [comment]
> * Keep the existing build setup((using Babel (Typescript) and Webpack)) and we expose `ApmModule` from the Agent and not via `ng` CLI as it bring in lots of unnecessary changes like folder restructuring and deps which is not worth to pursue.

I would like to expose an `ApmModule` which is responsible for creating the `apm` instance and injecting that into the service and error handler class vs the current `apm` static variable on those classes.

> * Can we add an exta build step and  generate the `*.metadata.json`  and types using `ng` and check-in inside the source. Would that help solve the AOT problem?

I think it will help/solve the AoT problem. Right now it will not run with AoT compilation. The recent `1.1.0` version did add support for differential loading and es2015 builds but AoT still fails. I setup an [example repo here](https://github.com/chriscarpenter12/elastic-apm-angular-demo/commit/12990f486c914e73e4d4147159f68e33a894cf5e) with the issue showing the error. 

When you generate an Angular library the `ng build` behind the scenes it uses [ng-packagr](https://github.com/ng-packagr/ng-packagr). You can use this package at build time, but it will process all the files because it's entire purpose is to create an Angular Package Format build. You can call the package directly like [this though](https://github.com/ng-packagr/ng-packagr/blob/master/integration/samples/api/ng-packagr-api.js) specifying a config and tsconfig to use. By default doing this it creates a `*.metadata.json` file for each file it processes.

You can specify the tsconfig `flatModuleId` to specify the generated metadata.json filename. Behind the scenes [ng-packagr auto-generates](https://github.com/ng-packagr/ng-packagr/blob/baa67340e7781b29cf88cdbea9b7539765183f32/src/lib/ts/tsconfig.ts#L33-L34) that from the library name.

> * We can add a new PR for the End to End app using the `ng` generated app and keep it at the same place as `packages/rum-angular/test/e2e/` and that way we can test for timeout issues you have mentioned.

This would be great!

I'd be happy to help with any of this along the way as we're trying to integrate this into a lot of apps.

**Comment by vigneshshanmugam** [comment]
Nice stuff there. Thanks for filling me in with all the necessary details.  We would be happy to collaborate as well with you on this effort. Let me know what you want to tackle it first and I can pick up other things.

**Comment by chriscarpenter12** [comment]
I can work on another PR with the changes just for the `ApmModule`. The larger AoT build issue still needs resolved and if you keep the current babel compilation my contribution will be limited there.

**Comment by vigneshshanmugam** [comment]
Thats nice. Yeah working on `ApmModule` sounds good. Regarding the build pipeline, I am okay with bringing in `ng packager` and other properties if it makes our life easier with Angular packaging Format and AOT issues you mentioned. I will do some investigation here.

**Comment by deefactorial** [comment]
Is there any update on this issue? Since angular abandoned JIT and only uses AOT for Ivy builds now the `rum-angular` package no longer works for angular 9, 10, 11.

**Comment by deefactorial** [comment]
I was able to do an ugly workaround by copying this dependencies source code into my project and building normally. I will update, when this issue is fixed I will revert the workaround. As a separate issue, there are some warnings generated from some of the dependencies:

```
WARNING in ./node_modules/@elastic/apm-rum-core/dist/es/opentracing/tracer.js depends on 'opentracing/lib/tracer'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in ./node_modules/@elastic/apm-rum-core/dist/es/opentracing/span.js depends on 'opentracing/lib/span'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in ./node_modules/@elastic/apm-rum-core/dist/es/error-logging/stack-trace.js depends on 'error-stack-parser'. CommonJS or AMD dependencies can cause optimization bailouts.
```

**Comment by chriscarpenter12** [comment]
A lot of the issues revolve around not being in the proper format using `NG` cli. In the short term I ended up packaging our own internal package fixing these shortcomings.

**Comment by emzet** [comment]
any progress here please? in meanwhile Angular 11 was released... also this issue is related to this one https://github.com/elastic/apm-agent-rum-js/issues/922

**Comment by antonselukh** [comment]
@chriscarpenter12 and @deefactorial 
Could you be so kind and give us a guide on how to implement these short-term workarounds for AOT?

I might find some time to contribute to this PR if I will understand the issues better.

**Comment by chriscarpenter12** [comment]
Took my changes in the [PR](https://github.com/elastic/apm-agent-rum-js/pull/746/files) that was declined and made our own Angular library project from it.

**Comment by malymato** [comment]
I would really appreciate an update on this issue. Is someone working on this? As was said before, library can't be used with Angular 10. Is the fix in pipeline, is there ETA?

**Comment by paulb-elastic** [comment]
https://github.com/elastic/apm-agent-rum-js/issues/962 has been raised to update the RUM Agent to support newer versions of Angular

**Comment by vigneshshanmugam** [comment]
We published the RUM Angular integration v2 Alpha which includes support for Angular 9. Would you be able to test it and let us know if it fixes your problem. 

```
npm install @elastic/apm-rum-angular@alpha
```

You have to make small changes to the initialization code. Docs here - https://github.com/elastic/apm-agent-rum-js/blob/cc4aba03d7f843e40f7256ee5a73fb74d4c18c9a/docs/angular-integration.asciidoc

Once these issues are addressed, will go ahead do the proper release. Thanks for the help in advance!

**Comment by antonselukh** [comment]
Thanky ou, It works

only a few small details:

> npm WARN @elastic/apm-rum-angular@2.0.0-alpha.1 requires a peer of @angular/core@^9.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @elastic/apm-rum-angular@2.0.0-alpha.1 requires a peer of @angular/router@^9.0.0 but none is installed. You must install peer dependencies yourself.

but only because you've set it for major version 9 and my project is: "@angular/core": "~10.1.0",

**Comment by antonselukh** [comment]
Not sure if this related to package version, but we've noticed an issue with distributed tracing.
The following example works:
`var apm = initApm({
  ...
  distributedTracingOrigins: ['https://api.example.com']
})`
but this does not:
`var apm = initApm({
  ...
  distributedTracingOrigins: ['https://api.example.com/']
})`

`traceparent` header is not added to the requests in the second case. Could be a similar issue to https://github.com/elastic/apm-agent-rum-js/issues/248

Should i log a separate issue?
