### ISSUE TITLE
React withTransaction not redefining transaction type

### ISSUE THREAD

**Issue by mgrip** [elastic/apm-agent-rum-js#758]
I'm using `withTransaction` from the react package, but its behaving strangely. I'm still getting `route-change` events, but not the custom `component` events that should be happening (I'm following the [elastic docs](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/react-integration.html#_instrumenting_individual_react_components) to create the custom `component` transactions). When I turn logging to debug, it says the transaction type is redefined at first, but it doesn't appear to stick once the transaction is actually done? The custom name does appear to stick

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/13454680/79877641-7945e180-83ba-11ea-8578-0f16f2c53af7.png">

**Comment by mgrip** [comment]
Actually I think I might have found the problem - seems like the type of the transaction doesn't actually get re-defined unless its one of the pre-defined type names?

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/13454680/79879831-346f7a00-83bd-11ea-8880-561be20db2e8.png">

Seems like that priority check is broken - its not actually allowing the type to be redefined

I double checked and if I switch the new name to an expected type of higher priority (ie "page-load"), I see the transactions get the updated type

**Comment by vigneshshanmugam** [comment]
Apologies for the delay, This seems to be a bug with the redefining as you have found out already. Will open a PR to address it.
