### ISSUE TITLE
Investigate mapping of RUM specific fields to ECS

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#766]
We should go through RUM specific fields in the spec and identify fields that either can potentially be added to ECS or fields that may have conflicts with already existing ECS fields.

We should list all the fields that are taken into account and the outcome in this issue.

**Comment by simitt** [comment]
Any update on this?

**Comment by jahtalab** [comment]
No update yet @simitt, I will post updates here as we progress!

**Comment by jahtalab** [comment]
The following fields are browser (RUM) specific and I don't think we should align them with ecs (not at this point at least):
- `transaction.page.*` and `error.page.*`, although we might use [ecs url set](https://www.elastic.co/guide/en/ecs/current/ecs-url.html) for `page.url`
- `transaction.marks.*`
- The [network set](https://www.elastic.co/guide/en/ecs/current/ecs-network.html) can not be used for the fields proposed [here](https://github.com/elastic/apm-server/issues/3657) with it's current format. We would need to define/standardize fields and values.

We can potentially use these in the future (although the fields are backend oriented):
- [ECS packages](https://www.elastic.co/guide/en/ecs/current/ecs-package.html) for detected libraries on the client

@simitt , Other than the above mentioned the rest of ecs field sets do not serve a purpose for RUM.
