### ISSUE TITLE
Payload Optimisation phase I

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#768]
+ Part of #158 
+ APM Server has deployed the first phase of the Proposed payload optimisation technique which is Shortening the field names that are sent in the payload PR - https://github.com/elastic/apm-server/pull/3414
+ Removing duplicate fields - some fields inside spans like `transaction_id`,`trace_id`, `parent_id` inside spans
+ One exception with `parent_id` is instead of passing the whole id incase when spans are subspans of other spans inside same transaction. we send the index of the parent span inside `parent_idx` mapped to `pi` of the payload to avoid sending the full id. 
+ `start`, `duration` are represented as JSON numbers so we can send integers instead of floats. 
+ `sync` is optional. so we send only when it's true. 

We are still exploring what could be done with metricsets. Moving them inside transaction or leaving them in separate lines (marking transaction details as optional). 

Full mapping of all the fields is here - https://github.com/elastic/apm-server/blob/master/model/modeldecoder/field/rum_v3_mapping.go

**Comment by vigneshshanmugam** [comment]
We need to test this before 7.8 stack goes to feature freeze. I am picking it up and working on this.

**Comment by vigneshshanmugam** [comment]
Removing the. breaking change level as we are shipping this feature behind a config flag

**Comment by jahtalab** [comment]
I've create [this issue](https://github.com/elastic/apm-agent-rum-js/issues/772) to investigate other breaking changes as well as a reminder to switch the config flag on version 6.0

**Comment by jahtalab** [comment]
@vigneshshanmugam , @jalvz , I know the changes for phase I are planned for 7.8 release. I just wanted to ask if there's any possibility of back-porting to earlier versions. 

The reason for this is when we release RUM agent version 6.0 we can only support 7.8+ stack versions and it would be nice to support earlier versions if possible. Of course, if the back-porting is not a huge burden.

**Comment by jalvz** [comment]
At most, it could potentially be back-ported to 7.7.1. But to be honest, there has been so many refactors and moving parts that I don't know how feasible it is (I think basically we would need to backport pretty much everything back to 7.7.1, probably including new 7.8 features, so don't know how much sense does it make. But I might be wrong - Ill have a look)
