### ISSUE TITLE
elasticApm.addLabels => TypeError: Cannot read property 'tags' of undefined   

### ISSUE THREAD

**Issue by adirobin** [elastic/apm-agent-rum-js#782]
I am using the RUM JavaScript agent "rum-js 5.0.0"
this is an ASP.NET web application and my init call is locate on the master page like this:
 
var elasticApmRumConfig = JSON.parse('<%=elasticApmRumConfig%>');
        if (elasticApm && elasticApmRumConfig && elasticApmRumConfig._enable) {
            elasticApm.init(elasticApmRumConfig);

            elasticApm.observe('transaction:end', function(tr) {
                if (tr.name === 'Unknown') {
                    tr.name = window.location.pathname
                }
            });
        }

later on on the same file (masterPage) i am adding labels by using the addLabels method on the elasticApm object.
 
this is working well for all aspx pages on my application except one. 
what different this file is that it contains React Application.

this application is using the "elastic APM RUM for react"  using the "instrument the application routes" like this:
import { ApmRoute } from '@elastic/apm-rum-react'
<Router basename={EnvironmentVariables.routerBaseName}>
                                    <div className="main-cover">
                                        <Switch>
                                            <ApmRoute path="/main">
                                                <Main />
                                            </ApmRoute>
                                            <ApmRoute path="/activityHistory">
                                                <ActivityHistoryFull />
                                            </ApmRoute>

this is the complete error from chrome dev tools console:
MarketingCustomerCard.aspx:100 TypeError: Cannot read property 'tags' of undefined
    at Config.addLabels (webpack-internal:///750:23653)
    at ApmBase.addLabels (webpack-internal:///750:24080)
    at HTMLDocument.<anonymous> (MarketingCustomerCard.aspx:90)
    at fire (jquery-1.8.3.js:974)
    at Object.fireWith [as resolveWith] (jquery-1.8.3.js:1084)
    at Function.ready (jquery-1.8.3.js:406)
    at HTMLDocument.DOMContentLoaded (jquery-1.8.3.js:83)

**Comment by jahtalab** [comment]
Hi @adirobin 

Thanks for reporting the issue.
This is mostly likely the result of a race condition, in which the `addLabels` is called before the `elasticApm.init`. You should make sure that the `init` function is called before any other interaction with the agent. Please keep in mind that the order of execution of event listeners might not be guaranteed.

However, we can also improve on this from the agent side by allowing `addLabels` to be called before `init`. We have https://github.com/elastic/apm-agent-rum-js/issues/780 to track this enhancement. Please subscribe to that issue for updates. Closing this one.
