### ISSUE TITLE
The PerformanceObserver has already been called with the entry type 'longtask'.

### ISSUE THREAD

**Issue by vladexologija** [elastic/apm-agent-rum-js#783]
After installing `@elastic/apm-rum` I'm constantly getting these warnings
`perf-entry-recorder.js:105 The PerformanceObserver has already been called with the entry type 'longtask'.` even though I've only initialized the library by calling `initApm` 
I'm using `Chorme 81.0.4044.138` with `@elastic/apm-rum": "^5.1.1` inside React/Relay app.

**Comment by vigneshshanmugam** [comment]
@vladexologija Please ignore the warning as Its a Chrome bug, Please check the details here - https://bugs.chromium.org/p/chromium/issues/detail?id=1052509
