### ISSUE TITLE
capture Cumulative Layout Shift as span

### ISSUE THREAD

**Issue by ImaginaryBA** [elastic/apm-agent-rum-js#795]
What - FID is a metric that measures a page's responsiveness during load. As such, it only focuses on input events from discrete actions like clicks, taps, and key presses.
SPEC - https://github.com/WICG/layout-instability/blob/master/README.md
Blog - https://web.dev/cls/

**Comment by vigneshshanmugam** [comment]
@ImaginaryBA Thanks for opening the issue, We are planning to capture CLS calculated as Span and include as part of page load transaction.
