### ISSUE TITLE
Use jsdelivr for copy/pasteable quickstart

### ISSUE THREAD

**Issue by thenewguy** [elastic/apm-agent-rum-js#808]
It would be helpful when just getting starting if your example could be copy/pasted into a file for demonstration.

```
<script src="https://cdn.jsdelivr.net/npm/@elastic/apm-rum@5.2.0/dist/bundles/elastic-apm-rum.umd.min.js" crossorigin></script>
```

instead of 
```
<script src="https://<your-cdn-host>.com/path/to/elastic-apm-rum.umd.min-<version>.js" crossorigin></script>
```

at https://www.elastic.co/guide/en/apm/agent/rum-js/current/install-the-agent.html

Implementation details can be worked out later but someone reading this page is just looking to see it work =)

**Comment by jahtalab** [comment]
Hi @thenewguy , we're planning to [deploy the agent on our CDN](https://github.com/elastic/apm-agent-rum-js/issues/481) please subscribe to that issue for updates.

Closing as duplicate.
