### ISSUE TITLE
RUM navigation timings

### ISSUE THREAD

**Issue by moix** [elastic/apm-agent-rum-js#820]
Hi! I asked recently in https://discuss.elastic.co/t/rum-navigation-timings/236744 but not sure if the forum is correct place for this kind of questions or is better asking here. It is more a generic question than an issue or bug report.

The point is that I want to create high level dashboard with navigation timings but without going to details so something that can be shown to non technical teams and easily readable. Following image gives a good idea of it:

![navigationtimingsgauges](https://user-images.githubusercontent.com/569132/85394457-e149ad00-b54e-11ea-926b-c5c274d6034e.png)

Should those be calculated by rum agent? I have logstash in between apm-server and elasticsearch so probably could calculate myself but if there are plans to calculate that in the agent I think will be more appropiate.

Thanks in advance!

**Comment by vigneshshanmugam** [comment]
RUM agent already captures some of these metrics as part of [Breakdown metrics](https://www.elastic.co/guide/en/apm/agent/rum-js/current/breakdown-metrics-docs.html)

You would need to enable the `breakdownMetrics: true` in the [configuration]( https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#breakdown-metrics) which requires APM Server and Kibana >= 7.4 version. 

Let us know if it helps your use case.

**Comment by moix** [comment]
it does indeed, sorry dunno how I didn't see those options, I'm on 4.x but checked release notes but didn't see it
will upgrade asap to 5.x and check it
