### ISSUE TITLE
Liniting section of contributing guide refers to missing script `format`

### ISSUE THREAD

**Issue by marksmithson** [elastic/apm-agent-rum-js#835]
https://github.com/elastic/apm-agent-rum-js/blob/master/CONTRIBUTING.md#linting

> To fix formatting and other auto-fixable eslint errors:
> 
> `$ npm run format`

This script does not exist. This appears to now be handled by a pre-commit hook.

If this is the case, happy to submit a PR to revise this doc and add a note about ensuring that `npm install` has been run to install hooks prior to committing code.

**Comment by vigneshshanmugam** [comment]
@marksmithson Thanks for catching it, You are correct. It is indeed handled at the commit time. Please do submit a PR, happy to review and fix it.

**Comment by vigneshshanmugam** [comment]
closed by #837
