### ISSUE TITLE
Add user context (vue plugin)

### ISSUE THREAD

**Issue by yooouuri** [elastic/apm-agent-rum-js#843]
Is there a way to add UserContext (https://www.elastic.co/guide/en/apm/agent/rum-js/current/agent-api.html#apm-set-user-context) using the Vue plugin?

We store user information in a Vuex store. The Vuex store is exported. So in theory we can import the store and access the state to set the UserContext.

We use currently:

```
Vue.use(ApmVuePlugin, {
  config: {
    serviceName: process.env.VUE_APP_APM_SERVICE_NAME,
    serviceVersion: process.env.VUE_APP_COMMIT_SHA,
    serverUrl: process.env.VUE_APP_APM_URL,
    environment: process.env.VUE_APP_ENV,
    // active: process.env.NODE_ENV === 'production',
    instrument: false,
  },
  captureErrors: true,
});
```

But maybe something like this is possible:

```
import store from '@/store';

Vue.use(ApmVuePlugin, {
  config: {
    serviceName: process.env.VUE_APP_APM_SERVICE_NAME,
    serviceVersion: process.env.VUE_APP_COMMIT_SHA,
    serverUrl: process.env.VUE_APP_APM_URL,
    environment: process.env.VUE_APP_ENV,
    // active: process.env.NODE_ENV === 'production',
    instrument: false,
  },
  captureErrors: true,
  userContext: {
    id: store.state.user.id,
    username: store.state.user.username,
    email: store.state.user.email
  }
});

**Comment by vigneshshanmugam** [comment]
Didnt see the issue, Please check my comments here and let us know if it works for you https://github.com/elastic/apm-agent-rum-js/pull/844#pullrequestreview-448709691

**Comment by vigneshshanmugam** [comment]
Closing as described in the PR comment https://github.com/elastic/apm-agent-rum-js/pull/844#pullrequestreview-448709691
