### ISSUE TITLE
Record sampling weight to transactions/spans  and propagate

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#845]
See elastic/apm#307. 

We need to record a sampling weight on transactions and spans, propagating the value through `tracestate` header for downstream services.
- [x] Document fixing CORS issue

**Comment by jahtalab** [comment]
We should consider this a breaking change since adding `tracestate` header would break existing applications due to CORS.

We should also document how to fix the CORS issue the same way we have done for traceparent.

**Comment by jahtalab** [comment]
Created an issue to [Propagate the tracestate header by default](https://github.com/elastic/apm-agent-rum-js/issues/955) in a major version. This one can be closed once the PR is merged.
