### ISSUE TITLE
Validate config options before setting them

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#86]
We should validate the value provided by the user for config options according the defined type and restrictions (varies between config options).

Some config options that need validation:
* `serviceName`
* `serverUrl`
* `pageLoadTraceId`
* `pageLoadSpanId`
* `pageLoadSampled`
* `pageLoadTransactionName`

**Comment by vigneshshanmugam** [comment]
serviceName should not contain chars other than this format `!/^[a-zA-Z0-9 _-]+$/`, Other agents already do this check and log proper error message. We should follow this in RUM agent as well.
