### ISSUE TITLE
ApmRoute instruments the app when agent is not initialized

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#881]
+ If APM is not initialised, the packages should not be instrumented. 
+ React package looks for config.isActive() which is true by default and would end up instrumenting the app, we need to have better mechanism to instrument the application from the framework specific packages only when the agent is initialised and enabled on platforms. 

**NOTE:These transactions wont get reported as there is no observer initialised for these events since `init`
 is never called in the first place**
```jsx
import { ApmRoute } from '@elastic/apm-rum-react'

render(
  <BrowserRouter basename="/">
    <App>
        <ApmRoute path="/test" render=() => {} />
    </App>
  </BrowserRouter>,
document.getElementById('app'),
() = > {})
)
```

**Comment by WangCao** [comment]
I'm browsing the doc,say:
"ApmRoute only instruments the route if component property is provided, in other cases, e.g. using render or children properties, ApmRoute will only renders the route without instrumenting it, please instrument the individual component using withTransaction in these cases instead."

**Comment by vigneshshanmugam** [comment]
No, using render wont work. I just provided it as example to reproduce the instrumentation warning that is issued from the agent. You would have to manually wrap the component under `withTransaction` as explained here https://www.elastic.co/guide/en/apm/agent/rum-js/current/react-integration.html#_instrumenting_individual_react_components

**Comment by WangCao** [comment]
> No, using render wont work. I just provided it as example to reproduce the instrumentation warning that is issued from the agent. You would have to manually wrap the component under `withTransaction` as explained here https://www.elastic.co/guide/en/apm/agent/rum-js/current/react-integration.html#_instrumenting_individual_react_components

I see, thank's reply
