### ISSUE TITLE
Could not find a declaration file for module '@elastic/apm-rum-angular'

### ISSUE THREAD

**Issue by super-kamil** [elastic/apm-agent-rum-js#884]
1. Follow the steps from https://www.elastic.co/guide/en/apm/agent/rum-js/current/angular-integration.html
2. Run `ng serve`
3. Error: `Could not find a declaration file for module '@elastic/apm-rum-angular'`

**Comment by mezzo1981** [comment]
Any update on this? We get also this error.

**Comment by vitormsilva** [comment]
I added this to my project under the `./src/@types` folder and then reference on the typeRoots inside of the `tsconfig.json` 

```typescript
// elastic__apm-rum-angular.d.ts
declare module '@elastic/apm-rum-angular' {
    import { Router } from '@angular/router';
    import { ErrorHandler } from '@angular/core';

    export interface Config {
        serviceName: string;
        serverUrl: string;
    }

    export class ApmService {
        router: Router;
        static apm: any;
        constructor(router: Router);
        init(config: Config): any;
        observe(): void;
    }

    export class ApmErrorHandler extends ErrorHandler {
        static apm: any;
        handleError(error: any): void;
    }
}
```

**Comment by blank-27** [comment]
can I work on this issue ?

**Comment by victorpintot8** [comment]
Same error here, I installed the 1.1.9 version of the package.

**Comment by mitschmidt** [comment]
Had the same issue, @victorpintot8's solution only worked for me after removing the import statements.

**Comment by ivayloc** [comment]
Same here

**Comment by JayeshPawar13** [comment]
Any update on this?

**Comment by vigneshshanmugam** [comment]
We are working on the support for Angular > 9 version which would include fixing the typings as well. You can track it here https://github.com/elastic/apm-agent-rum-js/issues/962

**Comment by vigneshshanmugam** [comment]
We published the RUM Angular integration v2 Alpha which includes support for Angular 9 and also includes type deps. Would you be able to test it and let us know if it fixes your problem. 

```
npm install @elastic/apm-rum-angular@alpha
```

You have to make small changes to the initialization code. Docs here - https://github.com/elastic/apm-agent-rum-js/blob/cc4aba03d7f843e40f7256ee5a73fb74d4c18c9a/docs/angular-integration.asciidoc

Once these issues are addressed, will go ahead do the proper release. Thanks for the help in advance!

**Comment by vigneshshanmugam** [comment]
Version 2.x.x major has been published with type declaration files. Please do let us know if you face any issues.
