### ISSUE TITLE
[Angular 10] error

### ISSUE THREAD

**Issue by JeremieLapert** [elastic/apm-agent-rum-js#891]
Hello,

After an migration from Angular 10.0.8 -> 10.1.0,I have the following error and the application does not start anymore.

![Capture d’écran du 2020-09-08 16-36-40](https://user-images.githubusercontent.com/1982908/92490792-ba1b8700-f1f1-11ea-9b56-17d971f55d8a.png)

Do you have an idea to solve this problem?
thank you in advance

Jérémie

**Configuration**
"@elastic/apm-rum-angular": "^1.1.6"
"@angular/core": "^10.1.0"

**Comment by jahtalab** [comment]
Thanks for reaching out @JeremieLapert , 

The error doesn't seem to be related to this project. 
Would you please provide more information on the actual error (e.g. stack traces)?

**Comment by JeremieLapert** [comment]
thanks for your reply, the problem seems to have been solved with the version `@elastic/apm-rum-angular": "^1.1.7"`
