### ISSUE TITLE
Investigate solutions for querying longtasks in the RUM dashboard

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#895]
Currently querying longtaks to provide aggregation in the RUM dashboard includes some expensive ES queries. The query involves getting all `page-load` transactions and then querying all longtaks spans for those transactions.

To help with this the RUM agent can aggregate longtask metrics in the transaction document:
```
{
    experience: {
        longtask: {
            duration: 1,
            max: 1,
            count: 1
        }
    }
}
```

- [x] Request the change from the APM server -> https://github.com/elastic/apm-server/issues/4226

**Comment by vigneshshanmugam** [comment]
I am leaning towards adding them under `transaction.experience` metrics as UI is having them under user centric metrics.

**Comment by jahtalab** [comment]
We discussed that we need sum, count and max of longtasks spans on each transaction.
