### ISSUE TITLE
capture screenshot of the front end page when error occure

### ISSUE THREAD

**Issue by synapticiel** [elastic/apm-agent-rum-js#921]
It would helpfull if the RUM agent capture and send a screenshot of the front end page when eror occure to the APM server that will store it on elasticsearch, so Analyst can view as part of the errors in the APM UI in Kibana

**Comment by vigneshshanmugam** [comment]
This is no API in the browser environment to capture a screenshot which comes under the RUM context and only possible in synthetics testing tools like puppeteer, playwright, lighthouse, etc. Hope that info helps.
