### ISSUE TITLE
Help needed in setting up APM with React

### ISSUE THREAD

**Issue by fernand0aguilar** [elastic/apm-agent-rum-js#923]
Hello. 

First, thanks for all the maintainers of this project. I need guidance with the documentation. 

To install an apm agent at a react project with babel.

I've done the following:
```
installed
"@elastic/apm-rum": "^5.6.1",
"@elastic/apm-rum-react": "^1.2.5",
```
added 
``` 
const apm = initApm({

  // Set required service name (allowed characters: a-z, A-Z, 0-9, -, _, and space)
  serviceName: '',

  // Set service version (required for sourcemap feature)
  serviceVersion: '',
  
  // Use if APM Server requires a token
  secretToken: 'secret',

  // Set custom APM Server URL (default: http://localhost:8200)
  serverUrl: 'secret',
})
```

and then 

`export default withTransaction('App', 'component')(App);`

what am I missing?

**Comment by jahtalab** [comment]
Hi @fernand0aguilar , thanks for using our APM product and sorry about the slow response.

First thing to point out is that you are only required to configure `serviceName`, `serverUrl` . The `serverUrl` needs to be a valid url. Furthermore, `secretToken` is not supported by the rum agent (you might be looking a the node.js agent docs)

Lastly, you can add `logLevel: debug` to see more information about issues: https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#log-level

I Hope this helps, feel free to comment if you have any other questions.
