### ISSUE TITLE
Receiving 400 bad request response - gzip invalid header

### ISSUE THREAD

**Issue by jenshoffmann1331** [elastic/apm-agent-rum-js#925]
Integrating apm-rum in our vue application we get 400 bad request responses from the APM server with the  following message:
```
{
  "accepted": 0,
  "errors": [
    {
      "message": "gzip: invalid header"
    }
  ]
}
```

Monkey patching apm-rum package, setting the header `Content-Encoding` to anything different than `gzip` or `deflate`, APM server accepts the requests with 200.

 - APM Server: 7.9.1
 - @elastic/apm-rum-vue 1.1.8
 - Chrome Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by vigneshshanmugam** [comment]
@jenshoffmann1331 Thanks for reporting, Could you please share the request/response headers along with the request payload(don't need to share the data, just whether its gzipped or NDJSON should be enough) to the APM server?

**Comment by jenshoffmann1331** [comment]
Response Header

```
access-control-allow-credentials: true
access-control-allow-headers: Authorization, Content-Type, Origin, Accept, X-Requested-With
access-control-allow-methods: DELETE, GET, HEAD, OPTIONS, POST, PUT
access-control-allow-origin: http://localhost:8080
access-control-max-age: 1728000
content-length: 91
content-type: application/json
date: Mon, 26 Oct 2020 11:29:24 GMT
set-cookie: AWSALB=****; Expires=Mon, 02 Nov 2020 11:29:24 GMT; Path=/
set-cookie: AWSALBCORS=****; Expires=Mon, 02 Nov 2020 11:29:24 GMT; Path=/; SameSite=None; Secure
status: 400
x-cloud-request-id: ****
x-content-type-options: nosniff
x-found-handling-cluster: ****
x-found-handling-instance: instance-0000000013
x-found-handling-server: ****
```

Request Header

```
:authority: ****
:method: POST
:path: /intake/v2/rum/events
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-encoding: gzip
content-length: 23
content-type: application/x-ndjson
origin: http://localhost:8080
referer: http://localhost:8080/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
```

Request Payload

```
[object ReadableStream]
```

**Comment by vigneshshanmugam** [comment]
Interesting, Readable stream on Request payload. Are you modifying the `Response.blob` method on any part of your app code? 

I just tested a sample application on same browser and its sending the gzipped post data.

**Comment by jenshoffmann1331** [comment]
@vigneshshanmugam : We are not modifying requests/responses.

This is what we do in main.js

```
// APM/RUM
import { ApmVuePlugin } from '@elastic/apm-rum-vue'
console.log(process.env.NODE_ENV, ApmVuePlugin)
if (process.env.NODE_ENV === "development") {
  Vue.use(ApmVuePlugin, {
    router,
    config: {
      serviceName: 'otto-console',
      serverUrl: process.env.VUE_APP_APM_SERVER_URL,
      serviceVersion: process.env.VUE_APP_VERSION,
      active: true,
      instrument: true,
      disableInstrumentations: [],
      environment: process.env.NODE_ENV,
      logLevel: 'warn',
      apiVersion: 2,
      breakdownMetrics: true,
      flushInterval: 1000,
    }
  })
}
```

This is what we do in our login callback:

```
          this.$apm.setUserContext({
            id: this.oidcUser.preferred_username,
            username: this.oidcUser.preferred_username,
            email: this.oidcUser.email,
          })
```

Nothing else we do with APM.

**Comment by jenshoffmann1331** [comment]
@vigneshshanmugam 

> Interesting, Readable stream on Request payload. Are you modifying the Response.blob method on any part of your app code?

Nice. The comment lead me to disable our mirage setup:

```
// Mirage/Mock Server
import { makeServer } from "@/mirage"
if (process.env.NODE_ENV === "development") {
  makeServer()
}
```

**And now events are properly send to APM!**

Though the mirage server has a passthrough definition for APM. I would expect that both could live with each other.

**Comment by vigneshshanmugam** [comment]
Great, glad you figured out the issue. Thanks for the details. Let us know if you run in to any other issues.
