### ISSUE TITLE
Receiving 400 bad request response - gzip invalid header

### ISSUE THREAD

**Issue by jenshoffmann1331** [elastic/apm-agent-rum-js#926]
**Describe the bug**

Integrating apm-rum in our vue application we get 400 bad request responses from our APM server with the following message:
```
{
  "accepted": 0,
  "errors": [
    {
      "message": "gzip: invalid header"
    }
  ]
}
```
 - APM Server: 7.9.1
 - Client: @elastic/apm-rum-vue 1.1.8

@elastic/apm-rum-vue compresses (gzip) events and sets the header `Content-Encoding` to `gzip`. Monkey patching the client, setting the   `Content-Encoding` header to a random string, the APM server accepts the request with 200.

**Comment by vigneshshanmugam** [comment]
Closing as duplicate #925
