### ISSUE TITLE
Add a note about initialising the agent with script tags to the Kibana instructions

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#93]
Link to the Kibana instructions - https://github.com/elastic/kibana/blob/master/src/legacy/core_plugins/kibana/server/tutorials/apm/instructions/apm_agent_instructions.js

**Comment by gregkalapos** [comment]
As part of the 7.0 testing I went through the setup instructions in Kibana, and for me with my limited JS knowledge it was very hard to understand the current RUM install instructions:

![image](https://user-images.githubusercontent.com/1091853/54671376-14082880-4af6-11e9-9289-1059c5581bb6.png)

Once I found the script tag in the docs I immediately knew how to add the RUM agent to my ASP.NET Core app. 

So, I also think this would help lots of users.
