### ISSUE TITLE
APM server behind a proxy

### ISSUE THREAD

**Issue by bnkamalesh** [elastic/apm-agent-rum-js#931]
I think this would be a common usecase, where the APM server is behind a proxy (in my case, Cloudflare). In which case, user IP is unavailable and we have to rely on custom headers; is there any provision of setting a custom header to be considered as user IP at the APM server or make the RUM agent set a custom header? In case of Cloudflare, they set the real user IP in the header 'True-Client-IP'.

Edit: It'd be nice if we could it set it during client init as well. e.g.

```javascript
initApm({
	environment: window.location.hostname,
	serviceName: 'my-app',
	serverUrl: 'https://apm.example.com',
	serviceVersion: getAppVersion() || 'v0.0.0',
	distributedTracing: true,
	distributedTracingOrigins: [
		'https://api.example.com'
	],
	XFFHeader: {
		key: 'X-Forwarded-For',
		value: '127.0.0.1'
	}
})
```

ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

In this case, if the value is provided, then it shall be set as value in request header. The APM server should be configurable or should understand that it should pickup user IP from this header.

**Comment by jahtalab** [comment]
I think this should be handled at the apm server, @elastic/apm-server any thoughts?

**Comment by bnkamalesh** [comment]
hmm, ideally this should be a server side feature. After 2-3 days of searching and reading docs, what I understand is that we should setup a new pipeline if we have to customize. That seemed way over the top to implement a header change or choose IP from a specific header.

**Comment by axw** [comment]
> I think this should be handled at the apm server, @elastic/apm-server any thoughts?

Yes, the server should be responsible for pulling the original client IP out of headers.

> what I understand is that we should setup a new pipeline if we have to customize.

If we're taking an IP from a custom header, then it will require code changes in APM Server.

We already parse `X-Forwarded-For`, and according to https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers this is injected by Cloudflare and includes the original client IP. It's unclear to me why you would want/need to use `True-Client-IP` instead; can you please expand on that?

**Comment by bnkamalesh** [comment]
@axw we haven't upgraded to Cloudflare's Enterprise version yet, and I was relying on this post

https://support.cloudflare.com/hc/en-us/articles/206776727-Understanding-the-True-Client-IP-Header

There's no need for me to use `True-Client-IP`, my opinion was, rather than adding support for individual providers (like CF, based on the link I posted), if we make it a configuration, it'd be helpful/easier.

**Comment by axw** [comment]
@bnkamalesh OK, thanks for the additional context.

Given that we already support `Forwarded`, `X-Forwarded-For`, and `X-Real-IP`, I think folks are pretty well covered at the moment.

Unless there is a clear need, I would prefer not to add another option. If it turns out there is a need to handle `True-Client-IP` (or other headers) instead of one of the other more common headers mentioned above, I'd be happy to learn more and consider adding an option.

**Comment by jahtalab** [comment]
Thanks @axw , closing this one for now.

**Comment by bnkamalesh** [comment]
> Given that we already support `Forwarded`, `X-Forwarded-For`, and `X-Real-IP`, I think folks are pretty well covered at the moment.

@axw 
Ok this might sound silly, but if all 3 are set. I presume it'd pick 1 based on some precedence, right?

**Comment by axw** [comment]
> Ok this might sound silly, but if all 3 are set. I presume it'd pick 1 based on some precedence, right?

Not at all silly!

Indeed, the server will pick the first of `Forwarded`, `X-Real-IP`, or `X-Forwarded-For` in that order. See also:
https://github.com/elastic/apm-server/blob/b3759fcc5cbdfb316634eeb81e43274c5fc9354e/utility/remoteaddr.go#L32-L45
