### ISSUE TITLE
how to get Traceparent/currentTraceparent in rum agent 

### ISSUE THREAD

**Issue by Manjukb** [elastic/apm-agent-rum-js#936]
our app uses socket.io and elastic apm wont track socket transactions automatically
so trying to instrument code to send trace data 
how to get traceparent value when i start a new transactions when i do `transaction.traceparent ` i get null but same works in nodejs agent 

    		`const transaction = apm.startTransaction('message', 'socket', { managed: true })
            console.log(transaction.traceparent );`

**Comment by kirbysayshi** [comment]
I was recently wondering this too. A use case is passing a `traceparent` header manually to the server in the case of an unsupported technology like WebSockets.

**Comment by vigneshshanmugam** [comment]
This is a duplicate issue - https://github.com/elastic/apm-agent-rum-js/issues/468, We will soon expose a way to set the trace propagation through the agent API.
