### ISSUE TITLE
distributedTracingOrigins wildcard support

### ISSUE THREAD

**Issue by PvanHengel** [elastic/apm-agent-rum-js#943]
Hi, 

Would it be possible to add wildcard support, or regex pattern matching as an option to the tracing origins option?

I think it would be rather simple change here: https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-core/src/common/utils.js#L120

Thank you,
Peter

**Comment by baruchiro** [comment]
I need it also. Our frontend access to multiple microservices hosted in one host, by ports, so I need the `distributedTracingOrigins` will include all ports when I set `http://10.10.10.10`, or by `http://10.10.10.10:*`.

I can't see another option to support this "multi-ports" use case.

If I can do the change myself, please tell me.

**Comment by baruchiro** [comment]
I think this is the right code:
https://github.com/elastic/apm-agent-rum-js/blob/6461364642e8879c613d7ce7e187e52bfb32ba54/packages/rum-core/src/common/utils.js#L148-L160

And I think needs to define exactly what will be the syntax, if it just `host:*`, or fully regex.

Need help from members here.

**Comment by vigneshshanmugam** [comment]
If you do want add support specific to the subnet levels and the `ips`, we could add a `RegExp` and do match on all the ips rather than introducing `*` which would be confusing. 

If you can open a PR for the same, that would be amazing.

**Comment by PvanHengel** [comment]
I think for sure regex is the way to go, it would be as simple as adding another block to the else if, that checks to see if the value passed is a regex, and go that.  It could handle wild cards in both IP address ranges, as well as in DNS names, and port numbers.  I'm a little curious how we could tell the difference between a string and regex but I'm sure it could be figured out, or just add another option in the config.
