### ISSUE TITLE
Is there a way to add more fields to the `span`?

### ISSUE THREAD

**Issue by justqyx** [elastic/apm-agent-rum-js#952]
As we all know, the `PerformanceResourceTiming entry` includes the following fields:

![image](https://user-images.githubusercontent.com/1448539/104153245-d12ae980-541c-11eb-8fc3-78dfdeeaf246.png)

This information helps to analyze the actual situation of each resource in each region of the world, but I found that APM only reported some of the following fields.

![image](https://user-images.githubusercontent.com/1448539/104153421-472f5080-541d-11eb-92af-dc8ce6fb8265.png)

I would like to ask if there is a way to record these fields about time and upload them to the APM server?

**Comment by antonselukh** [comment]
Agree.
Let's say, as a developer who installs the agent the first time, you are surprised this information is not included/parsed

**Comment by vigneshshanmugam** [comment]
@justqyx  Resource timing entries are captured as spans and some of the timings are attached to the span in a different form than the original entry. 
```
startTime - start of the span
responseEnd - end time of the span
duration - total duration of span
initiatorType - type of span
servertiming, transfersize, encodedbodysize,decodedBodySize -> added to span context
```
We currently don't have DNS(dnsStart, dnsEnd), TCP(sslStart, sslEnd), TTFB(requestStart) related metrics on the span itself as the UI does account for that information. But we will be adding support them in future as span marks. 

Please do let us know if you are looking for any specific information.

**Comment by antonselukh** [comment]
> Please do let us know if you are looking for any specific information.
@vigneshshanmugam i think OP wants to see a breakdown of http request timing in APM interface.
Something similar that NewRelic and AppDynamics provide in their RUM dashboards and that can be seen in DevTools of Chrome.
![image](https://user-images.githubusercontent.com/1457559/106032041-3eeb3c80-60d0-11eb-9335-55c8301f2b21.png)

**Comment by justqyx** [comment]
@vigneshshanmugam  Thank you very much for your reply. Is there a clear plan on which version will implement this feature?
