### ISSUE TITLE
compression is unconditionally turned on

### ISSUE THREAD

**Issue by zobo** [elastic/apm-agent-rum-js#954]
Due to _reasons_ I'm using an older version of apm-server (7.6) that does not yet support compression intake. Docs claim setting `apiVersion` to 2 would disable compression, but the stream is still sent in compressed format. Introduced in rum version 5.4.0. Here is the relevant line, that always compresses the stream.

https://github.com/elastic/apm-agent-rum-js/compare/@elastic/apm-rum@5.3.0...@elastic/apm-rum@5.4.0#diff-70b66edf2aa2af43e57c47a0b7b5c4e9128c449c20053e2b48fa4f61f4b093d2R84

Code should probably use `const compress = apiVersion > 2`.

**Comment by vigneshshanmugam** [comment]
Probably the naming of the config was the confusion here. We compress the payload using gzip, deflate algorithm by default when browser support that natively (chrome supports them). The `apiVersion` flag is used to shortern the field names that are sent to the APM server. Shortening works by this way
```
transaction - x
span - y
transaction.sampled - x.sm
...
```

This is done in the agent to reduce payload size. Hope this helps.
