### ISSUE TITLE
Page views not incrementing on changing route in React application.

### ISSUE THREAD

**Issue by adarshks-ks-by** [elastic/apm-agent-rum-js#961]
I have set the configuation like below

initApm({
  serviceName: 'LDE-APM',
  serverUrl: 'my service url',
  serviceVersion: '1',
})

and I have replaced the Route with ApmRoute which is imported from '@elastic/apm-rum-react'.

All data is showing correctly except page views count. It will increment only on first time loading of the website, when I change the route, it is not incrementing. Isn't that supposed to increment on changing the routes also?

![image](https://user-images.githubusercontent.com/75969687/107046989-4d7ed580-67ed-11eb-91c5-291dc9d71f76.png)

**Comment by vigneshshanmugam** [comment]
@adarshks-ks-by  Have you tried increasing the percentile or the time range. It could be due to the less number of impressions/page views that the aggregation considers them to be too low. Trying to change the percentile or time range should change that. Let us know if that solves.

**Comment by adarshks-ks-by** [comment]
@vigneshshanmugam  I have tried increasing the percentile and the time range, but still no difference. Its still increasing on page refresh only not on route change.

**Comment by vigneshshanmugam** [comment]
Hmmm, might be the impressions take care of only the hard navigations (page load), not the soft navigations (route change). 

@shahzad31 Could you confirm if this is the case?

**Comment by shahzad31** [comment]
@vigneshshanmugam yup page loads are only hard reloads. i think it was a product decision @drewpost

**Comment by vigneshshanmugam** [comment]
Closing the issue as the page view is applicable only for hard navigations.
