### ISSUE TITLE
Core web vital values not updating in React application

### ISSUE THREAD

**Issue by adarshks-ks-by** [elastic/apm-agent-rum-js#966]
I have integrated the web-vitals by using the following code

import { getCLS, getFID, getLCP } from 'web-vitals'

getCLS(console.log)
getFID(console.log)
getLCP(console.log)

I have also tried to send the data to google analytics using the following code

import { getCLS, getFID, getLCP } from 'web-vitals'

function sendToGoogleAnalytics({ name, delta, id }) {
  ga('send', 'event', {
    eventCategory: 'Web Vitals',
    eventAction: name,
    eventLabel: id,
    eventValue: Math.round(name === 'CLS' ? delta * 1000 : delta),
    nonInteraction: true,
    transport: 'beacon',
  })
}

getCLS(sendToGoogleAnalytics)
getFID(sendToGoogleAnalytics)
getLCP(sendToGoogleAnalytics)

But I can see that only data is updated for first input delay, like below

![image](https://user-images.githubusercontent.com/75969687/107484242-28e97b80-6ba8-11eb-85b5-60982b2947a1.png)

Is there any issue in my implementation? and I really don't understand how this analytics data will be shown in the user experience page, as I didn't see any connection between this elastic.io agent and google analytics.

**Comment by vigneshshanmugam** [comment]
This effectively happens due to the low volume of data - Please check my comment https://github.com/elastic/apm-agent-rum-js/issues/961#issuecomment-774081829 and let us know if it improves the situation. 

Also these values do only represent when you actually have those metrics reported by the browser (Chromium).

**Comment by adarshks-ks-by** [comment]
@vigneshshanmugam when I changed the time range its now showing CLS also so may be it's due to the low volume of data. but I was wondering how this web-vitals is showing in user experience section as I didn't see the connection between web-vitals module and apm-agent.

Can you tell me how the web-vitals is connecting with the apm-agent?

**Comment by vigneshshanmugam** [comment]
@adarshks-ks-by The RUM agent captures all the core web vitals metrics using [Performance Observer](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver). You can check the code here - https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-core/src/performance-monitoring/metrics.js

Please do let us know if you need more details.

**Comment by vigneshshanmugam** [comment]
Let us know if you need any more details, closing it as everything is answered.
