### ISSUE TITLE
React: User Interaction only returns "Click - div"

### ISSUE THREAD

**Issue by reecebenson** [elastic/apm-agent-rum-js#969]
This issue is possibly related to the intended fix from PR elastic/apm-agent-rum-js#951, however applying the changes there do not resolve the below issue for me.

Whenever a target is clicked, the USER_INTERACTION event is fired. As an example button:

```html
<button name="applyFiltersBtn" class="ui icon primary left labeled button">
  <i aria-hidden="true" class="check icon"></i>
  Apply
</button>
```

This then fires the following log:

```
[Elastic APM] startTransaction(86115b370489ca7c, Click - div, user-interaction)
```

As you can see, the name of this transaction is titled `Click - div`, even though the (what looks like) intended behaviour of [`performance-monitoring.js:189`](https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-core/src/performance-monitoring/performance-monitoring.js#L191) is to grab the `name` attribute from the element, in this case `applyFiltersBtn`. I'd expect this transaction to be named `Click - button["applyFiltersBtn"]` and for this to be recorded in the APM under a "user-interaction", whilst capturing network traffic to include spans such as API requests, etc.

When doing some debugging, I logged out what was being passed to [`shouldInstrumentEvent`](https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-core/src/common/patching/event-target-patch.js#L43) (or from elastic/apm-agent-rum-js#951, I have [this applied change](https://github.com/elastic/apm-agent-rum-js/blob/cd722fefc10dde2c29626144083e7b7a82477a97/packages/rum-core/src/common/patching/event-target-patch.js#L45), along with [the other changes from the PR](https://github.com/elastic/apm-agent-rum-js/pull/951/files)). When logging the `target` variable from the `shouldInstrumentEvent` function and also logging the `target` from the [getEventTargetSub](https://github.com/elastic/apm-agent-rum-js/blob/cd722fefc10dde2c29626144083e7b7a82477a97/packages/rum-core/src/performance-monitoring/performance-monitoring.js#L188), in all cases both parts of the aforementioned give back one of the following:

- `<div id="root">`
- `Window`
- `<react><react/>`.

It never gives back the _actual_ target of (in the example above) a Button. Is this intentional, if so, how would one implement a transaction to follow up on user interactions with buttons and log them correctly in APM, with React?

**Comment by StefanoSega** [comment]
same issue ...
everything else works fine, but despite specifying a value for the `name` attribute in the buttons when triggered the log is always `Click - div`
I thought it was an issue of event bubbling but is not the case

**Comment by vigneshshanmugam** [comment]
We can fix this today by using the technique described here - https://github.com/elastic/apm-agent-rum-js/pull/951/files#r588056071 

I would add this check to the PR and it should be good to go.

**Comment by reecebenson** [comment]
> We can fix this today by using the technique described here - https://github.com/elastic/apm-agent-rum-js/pull/951/files#r588056071. the resulting value of transaction would be `Click - button["applyFiltersBtn"]`

Sounds good, I'll give that a test with @clyfish's latest updates to that PR and report back here. Cheers for the update!

**Comment by reecebenson** [comment]
With the latest updates by @clyfish, still seeing a similar output as to what is described in this issue. When clicking the button, I continue to see `Click - div, user-interaction`. When logging out the `activeElement`, I'm seeing `<div id="root">` still.

| log | output |
| --- | ------ |
| [test] target is not window, document or have activeElement | `<div id="root">` |
| [test] target is not window, document or have activeElement | `<div id="root">` |
| [Elastic APM] redefining transaction(d620f145002f6e68, Click - div, user-interaction) to (Click - div, user-interaction) | `Object { name: "Click - div", type: "user-interaction", options: {…}, id: "d620f145002f6e68", traceId: "cb63b3d1613816e2302c47f4a40f3c11", sampled: true, sampleRate: 1, timestamp: undefined, _start: 118446, _end: undefined, … }` |
| [Elastic APM] redefining transaction(d620f145002f6e68, Click - div, user-interaction) to (Click - div, route-change) | `Object { name: "Click - div", type: "user-interaction", options: {…}, id: "d620f145002f6e68", traceId: "cb63b3d1613816e2302c47f4a40f3c11", sampled: true, sampleRate: 1, timestamp: undefined, _start: 118446, _end: undefined, … }` |

Updating this part of [`performance-monitoring.js`](https://github.com/elastic/apm-agent-rum-js/pull/951/files#diff-e3d6e2c6dedbb088511627f63de9cfdfed996ea94849ccf78f155b171cb33a5eR190-R198) to:
```js
        let target = task.target
        if (
          target === window ||
          target === document ||
          (typeof target.contains === 'function' &&
            target.contains(document.activeElement))
        ) {
          target = document.activeElement
          console.log('[test] target redefined to', target);
        }
        else {
          console.log('[test] target is not window, document or have activeElement', target);
        }
```

**Comment by reecebenson** [comment]
In order to get the expected functionality of `user-interaction` to have the correctly focused element, I had to do a horrible workaround like this (for testing purposes):

```js
document.addEventListener(
  'click',
  (e) => {
    // Get our clicked element
    const target = (e.target as HTMLElement) || null;
    if (!target) return;

    // Check if we have a valid element
    if (typeof target.getAttribute !== 'function') return;

    // Generate a Transaction Name from the attributes
    let transactionName = `Click - ${type}`;
    if (attr) transactionName += `.${attr}`;
    if (name) transactionName += `["${name}"]`;

    // Set activeElement
    console.log('[redef]: custom evt click', transactionName);
    target.focus();
  },
  true
);
```

Which result in the following logs:
| log | output |
| --- | ------ |
| [redef]: custom evt click | Click - BUTTON.applyFiltersBtn["applyFiltersBtn"] |
| [Elastic APM] redefining transaction(53cee16f7cb42b3f, Click - body, user-interaction) to (Click - button["applyFiltersBtn"], user-interaction) | `Object { name: "Click - body", type: "user-interaction", options: {…}, id: "53cee16f7cb42b3f", traceId: "8fab728bd8264784c4711f12679ad580", sampled: true, sampleRate: 1, timestamp: undefined, _start: 287124, _end: undefined, … }` |
| [Elastic APM] redefining transaction(53cee16f7cb42b3f, Click - button["applyFiltersBtn"], user-interaction) to (Click - button["applyFiltersBtn"], user-interaction) | `Object { name: "Click - button[\"applyFiltersBtn\"]", type: "user-interaction", options: {…}, id: "53cee16f7cb42b3f", traceId: "8fab728bd8264784c4711f12679ad580", sampled: true, sampleRate: 1, timestamp: undefined, _start: 287124, _end: undefined, … }` |
| [Elastic APM] redefining transaction(53cee16f7cb42b3f, Click - button["applyFiltersBtn"], user-interaction) to (Click - button["applyFiltersBtn"], route-change) | `Object { name: "Click - button[\"applyFiltersBtn\"]", type: "user-interaction", options: {…}, id: "53cee16f7cb42b3f", traceId: "8fab728bd8264784c4711f12679ad580", sampled: true, sampleRate: 1, timestamp: undefined, _start: 287124, _end: undefined, … }` |
| [Elastic APM] transaction(789344a1c1770ed2, Click - button["applyFiltersBtn"]) was discarded! Transaction does not have any spans | |

This looks like what I'm expecting (except the last log), however the final thing on my list is capturing network traffic. I'm not sure how this works in its entirety, as I cannot get it to record the API calls it is making. The logic of my `applyFiltersBtn` is somewhat as follows:

1. User clicks the apply button
2. Dispatch an action to refresh the table
3. React Hook checks the `refresh` flag to see if it is set to `true`, and dispatches another action which subsequently calls an API.
4. API response is received and the (Functional) Component is updated

Is there a way to force this network activity to be logged, instead of the transaction being discarded?

**Comment by clyfish** [comment]
@reecebenson I've tested without your workaround, and it works on Chrome 89. What browser did you test on?

If there is an `http-request` transaction after the `user-interaction` transaction within 100ms, The `user-interaction` will not be discarded, because the `user-interaction` transaction has no spans itself and the `http-request` transaction has.

https://github.com/elastic/apm-agent-rum-js/blob/6461364642e8879c613d7ce7e187e52bfb32ba54/packages/rum-core/src/performance-monitoring/performance-monitoring.js#L211

**Comment by StefanoSega** [comment]
also, another question ...
after collecting all user interactions as transactions how I can see them in time order kinda like breadcrumbs, to understand exactly what the user did in sequence?

**Comment by reecebenson** [comment]
> @reecebenson I've tested without your workaround, and it works on Chrome 89. What browser did you test on?
> 
> If there is an `http-request` transaction after the `user-interaction` transaction within 100ms, The `user-interaction` will not be discarded, because the `user-interaction` transaction has no spans itself and the `http-request` transaction has.
> 
> https://github.com/elastic/apm-agent-rum-js/blob/6461364642e8879c613d7ce7e187e52bfb32ba54/packages/rum-core/src/performance-monitoring/performance-monitoring.js#L211

I'm testing using Firefox 86. I'd assume this works as expected but in my use case 100ms isn't enough buffer time to track network activity, as I have state changes to apply before firing something to the API. There doesn't look like there is a way to override this value either. Is that something we could introduce here, possibly a new issue for tracking?

I don't want to propose an increase in this value as it's probably a single use-case, but an override to this value would be beneficial for some.

> also, another question ...
> after collecting all user interactions as transactions how I can see them in time order kinda like breadcrumbs, to understand exactly what the user did in sequence?

Please [create a new issue](https://github.com/elastic/apm-agent-rum-js/issues/new/choose) as your question is irrelevant to this issue. It makes these issues difficult to follow if conversation starts becoming off-topic.

**Comment by clyfish** [comment]
I've tested on Firefox 86, and it still works without your workaround. Are there any `blur` or `focus` called in your code that resetting the `activeElement` to `document.body`?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/blur

> Regarding the network activity, in my use case 100ms isn't enough buffer time to track network activity, as I have state changes to apply before firing something to the API.
Why does a state change take more than 100ms? Normally, the request is initiated immediately after clicking.

**Comment by reecebenson** [comment]
> I've tested on Firefox 86, and it still works without your workaround. Are there any `blur` or `focus` called in your code that resetting the `activeElement` to `document.body`?
> 
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/blur
> 
> > Regarding the network activity, in my use case 100ms isn't enough buffer time to track network activity, as I have state changes to apply before firing something to the API.
> 
> Why does a state change take more than 100ms? Normally, the request is initiated immediately after clicking.

Having a look through, I haven't got any additional `.blur()` or `.focus()` calls apart from the workaround I provided above (that I've commented out for testing here). I've noticed a slight improvement to logs whilst routing throughout my app, where it now records `Click - a` and occassionally `Click - body` with the relevant network activity. Although, the button in question is still being classed as a `div` and then being discarded. In attempts to give you a bigger picture, the DOM is similar to that of the below around the `button.applyFiltersBtn`:

```html
<div class="root">
  <div class="ui attached segment">
    <div>(some filtering content, dropdowns, inputs, etc.)</div>
    <button name="applyFiltersBtn" class="ui icon primary left labeled button">
      <i aria-hidden="true" class="check icon"></i>
      Apply
    </button>
  </div>
  <div>(the rest of the app, tables, etc.)</div>
</div>
```

Regarding the `Click - a` calls, this is some buttons on the table of the app. The reasoning as to why state change can take longer than 100ms is (partly) down to poor optimisation on the table (looking to lazy load this in the future / scroll load) but that is part of a future sprint as we're still in the building phase. When clicking Apply, the logic is to update the Redux store to be manipulated and prepare a payload to be pushed to the API (can contain quite a lot of data to query against the API). When that logic is generated and prepared, state is updated for a loading indicator and awaits a response. When monitoring this with the Network tab on devtools, the request happens around 500-600ms after the initial click.

**Comment by reecebenson** [comment]
I've been able to get this to work how I expect it to work, however can't seem to get it functioning exactly how I'd like due to some UI library restrictions (for example, some out of the box components don't expose the `name` attribute to the rendered DOM). To work around this, I use `data-rum` as additional props are passed through to the DOM. In attempts to clear up the workflow I have here, here's the logs below with two steps - clicking the 'Apply Filters' button, and then clicking another button to 'View Authors'.

### First Step (Apply Filters)

| log | output | info |
| --- | ------ | ---- |
| [Elastic APM] startTransaction(d69a67afece3fbc9, Click - body, user-interaction) | | my custom event firing a transaction with a larger threshold (1000ms) |
| [Elastic APM] redefining transaction(d69a67afece3fbc9, Click - body, user-interaction) to (Click - BUTTON.applyFiltersBtn, user-interaction) | `Object { name: "Click - body", type: "user-interaction", options: {…}, id: "d69a67afece3fbc9", traceId: "0e4c032c861fcad61fc25584ca32da38", sampled: true, sampleRate: 1, timestamp: undefined, _start: 5510, _end: undefined, … }` |
| [Elastic APM] redefining transaction(d69a67afece3fbc9, Click - BUTTON.applyFiltersBtn, user-interaction) to (Click - button["applyFiltersBtn"], user-interaction) | `Object { name: "Click - BUTTON.applyFiltersBtn", type: "user-interaction", options: {…}, id: "d69a67afece3fbc9", traceId: "0e4c032c861fcad61fc25584ca32da38", sampled: true, sampleRate: 1, timestamp: undefined, _start: 5510, _end: undefined, … }` | elastic renaming the transaction |
| [Elastic APM] redefining transaction(d69a67afece3fbc9, Click - button["applyFiltersBtn"], user-interaction) to (Click - button["applyFiltersBtn"], user-interaction) | `Object { name: "Click - button[\"applyFiltersBtn\"]", type: "user-interaction", options: {…}, id: "d69a67afece3fbc9", traceId: "0e4c032c861fcad61fc25584ca32da38", sampled: true, sampleRate: 1, timestamp: undefined, _start: 5510, _end: undefined, … }` | no change? |
| [Elastic APM] redefining transaction(d69a67afece3fbc9, Click - button["applyFiltersBtn"], user-interaction) to (Click - button["applyFiltersBtn"], route-change) | `Object { name: "Click - button[\"applyFiltersBtn\"]", type: "user-interaction", options: {…}, id: "d69a67afece3fbc9", traceId: "0e4c032c861fcad61fc25584ca32da38", sampled: true, sampleRate: 1, timestamp: undefined, _start: 5510, _end: undefined, … }` | changed transaction type from `user-interaction` to `route-change` (correct - as URL is updated via `history.push()`) | 
| [Elastic APM] startSpan(GET https://api.example.com/v1/data/, external) on transaction(d69a67afece3fbc9, Click - button["applyFiltersBtn"]) | | API request is found |
| [Elastic APM] endSpan(GET https://api.example.com/v1/data/, external) on transaction(d69a67afece3fbc9, Click - button["applyFiltersBtn"]) | | API request returned |
| [Elastic APM] end transaction(d69a67afece3fbc9, Click - button["applyFiltersBtn"], route-change) | `Object { name: "Click - button[\"applyFiltersBtn\"]", type: "route-change", options: {…}, id: "d69a67afece3fbc9", traceId: "0e4c032c861fcad61fc25584ca32da38", sampled: true, sampleRate: 1, timestamp: undefined, _start: 5510, _end: 7733, … }` | transaction ended for Apply button |

### Second Step (Narrow Search)

The below table represents the second action, for the purpose of this example this button is an 
"Authors" button that subsequently fetches data from the API related to the current page.

| log | output | info |
| --- | ------ | ---- |
| [Elastic APM] startTransaction(f18802a86b82aedd, Click - body, user-interaction) | | elastic detected a click |
| [Elastic APM] redefining transaction(f18802a86b82aedd, Click - body, user-interaction) to (Click - A.authorsTab, user-interaction) | `Object { name: "Click - body", type: "user-interaction", options: {…}, id: "f18802a86b82aedd", traceId: "e404c7eef739580ea62cd9054599554a", sampled: true, sampleRate: 1, timestamp: undefined, _start: 12947, _end: undefined, … }` | my custom event handler has renamed the transaction to `A.authorsTab` as the `name` attribute was not found, so used `data-rum` attribute (see snippet below) |
| [Elastic APM] redefining transaction(f18802a86b82aedd, Click - A.authorsTab, user-interaction) to (Click - div, user-interaction) | `Object { name: "Click - A.authorsTab", type: "user-interaction", options: {…}, id: "f18802a86b82aedd", traceId: "e404c7eef739580ea62cd9054599554a", sampled: true, sampleRate: 1, timestamp: undefined, _start: 12947, _end: undefined, … }` | elastic inconveniently renames this back to a generic `Click - div` as the `name` attribute does not exist (UI library limitation) |
| [Elastic APM] redefining transaction(f18802a86b82aedd, Click - div, user-interaction) to (Click - div, user-interaction) | `Object { name: "Click - div", type: "user-interaction", options: {…}, id: "f18802a86b82aedd", traceId: "e404c7eef739580ea62cd9054599554a", sampled: true, sampleRate: 1, timestamp: undefined, _start: 12947, _end: undefined, … }` | no change |
| [Elastic APM] redefining transaction(f18802a86b82aedd, Click - div, user-interaction) to (Click - div, route-change) | `Object { name: "Click - div", type: "user-interaction", options: {…}, id: "f18802a86b82aedd", traceId: "e404c7eef739580ea62cd9054599554a", sampled: true, sampleRate: 1, timestamp: undefined, _start: 12947, _end: undefined, … }` | correct, route is updated |
| [Elastic APM] startSpan(GET https://api.example.com/v1/author-info/, external) on transaction(f18802a86b82aedd, Click - div) | | api request detected |
| [Elastic APM] endSpan(GET https://api.example.com/v1/author-info/, external) on transaction(f18802a86b82aedd, Click - div) | | api request ended |
| [Elastic APM] end transaction(f18802a86b82aedd, Click - div, route-change) | `Object { name: "Click - div", type: "route-change", options: {…}, id: "f18802a86b82aedd", traceId: "e404c7eef739580ea62cd9054599554a", sampled: true, sampleRate: 1, timestamp: undefined, _start: 12947, _end: 15842, … }` | transaction ended |

​The snippet mentioned above, and previously in this ticket has been slightly updated and now looks like the below. As we aren't able to override the `reuseThreshold` directly (through some configuration), the next best thing was to fire a new transaction as my event gets called:

```javascript
import { apm } from '@elastic/apm-rum';

// Elastic APM Services
const apmServices = apm.serviceFactory;
const trService = apmServices.getService('TransactionService');
document.addEventListener(
  'click',
  (e) => {
    // Get our clicked element
    const target = (e.target as HTMLElement) || null;
    if (!target) return;

    // Check if we have a valid element
    if (typeof target.getAttribute !== 'function') return;

    // Check if we have the "data-rum" attribute
    const type = target.tagName;
    const attr = target.getAttribute('data-rum');
    if (!attr) return;

    // Generate a Transaction Name from the attributes
    let transactionName = `Click - ${type}`;
    if (attr) transactionName += `.${attr}`;

    // Set activeElement
    target.focus();

    // Kick start our APM transaction so that Elastic can redefine it
    // Let the transaction be reused by APM so that we can monitor traffic
    trService.startTransaction(transactionName, 'user-interaction', {
      managed: true,
      canReuse: true,
      reuseThreshold: 1000
    } as ActualTransactionOptions) as Transaction;
  },
  true
);
```

The `ActualTransactionOptions` refers to a cover interface, as the `reuseThreshold` isn't a valid propery for the [`SpanOptions` interface](https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum/src/index.d.ts#L148).

All of the above gives me the results I'm expecting. I'm guessing what comes out of this is:

1. Can we have an override setting to look for a different attribute if `name` isn't valid?
2. Can we have an override setting for the `reuseThreshold` SpanOption?

**Comment by reecebenson** [comment]
Hi @clyfish / @vigneshshanmugam, would the two aforementioned overrides be something you'd consider? I'd be happy to raise a PR if that is the case - maybe even just the `reuseThreshold` override as I've raised a [PR](https://github.com/Semantic-Org/Semantic-UI-React/pull/4169) and [issue](https://github.com/Semantic-Org/Semantic-UI-React/issues/4168) for the UI library I'm using (Semantic UI for React). Let me know your thoughts, happy to discuss.

**Comment by vigneshshanmugam** [comment]
@reecebenson Thanks for the extensive test. I did a quick look around the new React 17 event system. It seems like React is registering two click events on the `application root` where the react app is mounted One with useCapture flag set to true and other with false. 

As a result, I can see your test producing redefining transactions with no changes and also `document.activeElement` also not having the correct focus. 

I am still doing some testing to figure out what would be the best solution here. 

@clyfish Not sure why you closed the PR. Using `window.onclick` is easier, but it does not guarantee that 
+ our listeners always fires before everyone elses
+ We have to also account for events that have been explicity called with `e.stopPropagation` or `e.preventDefault`. 

So if we can fix it using eventtarget, it would be a better solution.

**Comment by clyfish** [comment]
> document.activeElement also not having the correct focus

I can't reproduce it.

```html
<!doctype html>
<div><a href="javascript:">test1</a></div>
<p>test2</p>
<div><button>test3</button></div>
<script>
window.addEventListener('click', function(e) {
    console.log(document.activeElement)
}, true)
</script>
```

click test1: document.activeElement is the `a`.
click test2: document.activeElement is the `body`.
click test3: document.activeElement is the `button`.

> Not sure why you closed the PR

Because I think I've solved my problem by using `window.onclick`, and I don't know which solution is better for `apm-agent-rum-js`. You can create another PR to solve this issue.

> our listeners always fires before everyone elses
> We have to also account for events that have been explicity called with e.stopPropagation or e.preventDefault.

We can listen on window with useCapture flag before react-dom's `render` to solve the two problem.

**Comment by jahtalab** [comment]
Re. capturing the network event for the user-interaction transaction, I believe there's an async operation that we're not capturing between the time the click happens and the time the network event is fired. I think having a small reproduction code would be useful (maybe in a separate issue as well), @reecebenson would you be able to push a simplified version of your code so we can reproduce this?

@vigneshshanmugam , Have you been able to reproduce the element attribute issue locally? If so I think sharing your code would be helpful to debug this.

**Comment by reecebenson** [comment]
> I think having a small reproduction code would be useful (maybe in a separate issue as well), @reecebenson would you be able to push a simplified version of your code so we can reproduce this?

I'll see if I can get some time authorised and put aside to produce a reproducable codebase for you. It may not be authorised until this time next week, however, so apologies in advance.

**Comment by jahtalab** [comment]
No worries @reecebenson , I think even a very simple piece of code (could be a single html file with some JS) that essentially demonstrates your problem is very helpful. There's no need for the actual code.

**Comment by vigneshshanmugam** [comment]
> Have you been able to reproduce the element attribute issue locally? If so I think sharing your code would be helpful to debug this.

Updating our react-* packages to 17 and running our E2E application for React would showcase the problem. Also play a bit with this PR once you are done updating - https://github.com/elastic/apm-agent-rum-js/pull/951. You will notice how the attribute changes.

**Comment by jahtalab** [comment]
@vigneshshanmugam , to post the examples he has generate in a PR so we can come up with solutions for this one.

**Comment by reecebenson** [comment]
Hi @vigneshshanmugam / @jahtalab, apologies for not getting back to you with a snippet, but has there been any work on this that I could potentially test with?

**Comment by fsalazarh** [comment]
Hi, any updates with this Issue? 

I'm using ```"@elastic/apm-rum": "^5.9.1"``` and i'm facing the same issue. 

I'm created a React app using ```"react": "^17.0.1"``` with Ionic Framework, and I'm receive the ```Click - div```, ```Click - ion-button``` and ```Click - ion-tab-button```, ```Click - ion-content```, etc... in the "user-interaction" transactions type.

**Comment by FedeOmoto** [comment]
Hi, any updates with this Issue?
