### ISSUE TITLE
React errors displaying as inline script errors in output

### ISSUE THREAD

**Issue by EBruchet** [elastic/apm-agent-rum-js#975]
We are currently trying to set up the APM Rum Agent for our React applications, and have followed the instructions specified here: https://www.elastic.co/guide/en/apm/agent/rum-js/master/react-integration.html

When starting up the React application, we make a call to `initApm({ serviceName: "...", serverUrl: "..."})` and wrap the relevant component(s) in a `withTransaction` call.

When running the application locally, all error messages come through with the full React stacktrace, but unfortunately once the applications have been deployed to production, any errors that crop up in production are displayed as follows:

<img width="520" alt="Inline Script Error" src="https://user-images.githubusercontent.com/20384291/110323647-c9e31f00-800c-11eb-8ff3-8aaba078bd6b.png">

Is there an additional property we are missing in the `initApm({})` call or is this simply a limitation of how the APM Agent interacts with bundlers like Webpack?

Thanks for any help with this.

**Comment by vigneshshanmugam** [comment]
This is not related to the integration, but mostly due to CORS. Browsers dont expose the error message/stack trace when the error is thrown from a script that is loaded from third party domain. So you need to two things to get the actual error message. 

1. Set the CORS header from which server the script is served from 
```
Access-Control-Allow-Origin: *
```

2. Add the **crossorigin** attribute to your script tag.
```html
<script type="text/javascript" src="https://example.com/app.js" crossorigin=""></script>
```

Hope this helps.

**Comment by EBruchet** [comment]
Wanted to bring this issue back up, as after upgrading to Webpack v5 we have started encountering this issue again. We have left our script tags untouched in our template files, so the `crossorigin` property is still the same. 

Same goes for the CORS settings, so is it possible the way Webpack v5 generates sourcemaps is now incompatible with the APM RUM Agent?

**Comment by andriijas** [comment]
Im running webpack 5 successfully with sourcemaps working as expected in kibana using the apm rum client and CORS.
