### ISSUE TITLE
SPA support

### ISSUE THREAD

**Issue by bp-fndr** [elastic/apm-agent-rum-js#99]
Does APM RUM support single page web apps, e.g. web apps using Vue, Angular frameworks?
When I tried RUM agent locally it seems I am only getting a single page called "unknown" under APM dashboard

**Comment by jahtalab** [comment]
Thanks for reaching out @bp-fndr 

Our RUM agent is framework independent therefore it works with any JavaScript application.
However, by default we only capture page load transactions. The default name for transactions is "Unknown" but you can change that using [pageLoadTransactionName](https://www.elastic.co/guide/en/apm/agent/js-base/current/configuration.html#page-load-transaction-name) configuration.

Furthermore, you can instrument your single page application using [Custom transaction API](https://www.elastic.co/guide/en/apm/agent/js-base/current/custom-transactions.html).

Let me know if you have any questions.

**Comment by gcssabbagh** [comment]
@jahtalab If I start a transaction on each of my SPA (Vuejs) route changes with let's say type `route-change`, will I still get all the spans for navigation timing, resources, etc.. automatically (similar to `page-load` transactions) or do I have to instrument those myself as well?

**Comment by jahtalab** [comment]
Hi @gcssabbagh , 

The navigation and resource timing is only recorded for transactions with the special type `page-load`, therefor they would not be included in a transaction with `route-change` as its type.

Also, please note that the navigation timing spans might not match the the timings in a route change since a route change might happen at any time and that could result in long gaps in the transaction view in the APM UI.

However, please feel free to open a new issue for supporting navigation and resource timings on custom transactions and we will definitely consider it.

**Comment by rajasaur** [comment]
@jahtalab : Since this is quite critical for any SPA, would it be better to plug into the chrome devtools so its framework agnostic? that way, any change that appears on a XHR request can be traced rather than limiting to page-load ? 
I can try and build something up if that seems like the direction you'd like to take. My only concern with being framework specific is that you'd have to build something specific for every new framework that comes by, but building it for devtools(for chrome/safari) and/or toolbox(for Firefox) maybe easier?

**Comment by jahtalab** [comment]
Thanks for reaching out @rajasaur , 

Our current implementation of the agent is in fact framework agnostic. So the `route-change` transactions need to be create using our [Custom Transaction API](https://www.elastic.co/guide/en/apm/agent/js-base/current/custom-transactions.html).

Regarding your suggestion of using devtools, our focus is to provide an agent for Real User Monitoring (RUM) which means we can't rely on having access to devtools (or other similar) APIs. However, your suggestion would be feasible for synthetic monitoring but currently we don't have any plans to provide that.

Cheers

**Comment by rajasaur** [comment]
@jahtalab : Are there any examples of using Custom Transaction for Angular apps. I looked at the example but wasnt sure what should be used as a span. If I want to track every page request using an angular router, would it be enough to create a span for each of the routes being loaded?

**Comment by jahtalab** [comment]
@rajasaur , We're in the process of improving our API to make it easier to use Custom Transactions (see #101). We also have plans to publish a blog post on how to instrument a framework (such as Angular or React) with Custom transactions.

Unfortunately I can't provide a timeline for it yet, but I will make sure to update the relevant issues once it's done.

However, to provide a quick answer to your questions, generally speaking, Spans are for measuring an activity and Transactions are our way of grouping spans under a meaningful action (such as route change). Therefore you should listen for route change start events from angular router, and start a Transaction, but you need to make sure to manually end the transaction once your route change has completed (this is the part that we're trying to improve with #101 ). As long as the custom transaction is running, http calls are automatically recorded as spans into the current transaction, so you don't have to add them manually.

I Hope this helps :)

**Comment by aaqibjavith** [comment]
@jahtalab Do you have any update on this?

It will be great if you provide basic steps to instrument both Reach and Angularjs apps.

**Comment by jahtalab** [comment]
@aaqibjavith , We're currently working on https://github.com/elastic/apm-agent-rum-js/issues/90 to facilitate capturing route changes.

However it would help us a lot to know about your use-case. 
What exactly do you want to capture with regards to React or Angular? Does capturing route changes help in your use-case?

**Comment by aaqibjavith** [comment]
@jahtalab we are using React and React-router. It will be awesome if we can see the performance of  each and every route changes. 

As of now, I am using fullstory to know about the performance and usage of our product. As you know, it is really hard to check every sessions.

**Comment by kisonay** [comment]
Same thing for me with Vue. Would be great if the loading of a route would be counted as a (page)view. I was attempting to do something with before and after route changes within Vue.

**Comment by sundarv85** [comment]
I’m having the same issue with Angular. I see that it is now moved to In Progress @jahtalab Do you have any timeline for it..

**Comment by jahtalab** [comment]
@sundarv85 , Currently we're working on instrumenting [history.pushState](https://github.com/elastic/apm-agent-rum-js/pull/259) plus providing a [react integration](https://github.com/elastic/apm-agent-rum-js/pull/265). 

An Angular integration will follow after these. At the moment I don't have a specific timeline for it, but I will make updates here as we progress. 

Which version of Angular are you currently using? 
What parts of your application do want to instrument, for example route changes or individual components?

**Comment by sundarv85** [comment]
@jahtalab Thanks for the update. We are using Angular 1 and are planning to update. We are looking for ways to instrument route changes.

**Comment by freezy** [comment]
Is "manual" SPA even possible with this library today? I've tried hooking into AngularJS' router event hooks triggering `apm.startTransaction()` manually, but obviously there is no `onload` so it never finishes.

Then I've tried ending it manually when the last HTTP request completes (by hooking into AngularJS' `$http` service), but then the beacon is sent before the transaction finishes (I have a 500ms cooldown to determine whether there are any more HTTP requests). I've looked at `flushInterval`, and it seems to be triggered when the transaction is *started*? Shouldn't it trigger after it *ended*?

**Comment by jahtalab** [comment]
Hi @freezy , 

Manual instrumentation is possible, however after calling `var transaction = apm.startTransaction()` you should make sure to call `transaction.end()` to end the transaction. 

Regarding the `flushInterval`, it is used in our Queue class and it is only triggered once an item is added to the queue which is after the transaction has ended.

Let me know if you have more questions.

**Comment by freezy** [comment]
Well, I *do* end it manually with `transaction.end()`, but as mentioned the beacon is sent before doing that.

I'll try to figure out why and come up with a Plunker if necessary. Thanks!

**Comment by jahtalab** [comment]
Closing this in favor of framework-specific issues.
