### ISSUE TITLE
vue install can not get the version

### ISSUE THREAD

**Issue by cs686** [elastic/apm-agent-rum-js#990]
![image](https://user-images.githubusercontent.com/11469578/111401372-27115b80-8704-11eb-9d87-06118ee9ad29.png)

**Comment by vigneshshanmugam** [comment]
@cs686 I am not sure why you are seeing that error. Its published already - https://www.npmjs.com/package/@elastic/apm-rum-core

It could be that the package manager/registry you are using does not have that version yet.

**Comment by vigneshshanmugam** [comment]
Just did a check on cnpm registry and this is what i found 
```
Sync Status
This registry will sync all packages from official registry.

Last sync time is Thu Jun 22 2017 04:59:54 GMT-0700 (Pacific Daylight Time).
```

I don't think we can do anything here, You could configure your registry to point to `registry.npmjs.com` and should work fine.
