### ISSUE TITLE
expose blocking transaction/span type information in typings file

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#995]
+ Support is added via this PR #875 
+ We didn't expose these options when creating blocking transactions and spans in our typings file for `@elastic/apm-rum` - https://github.com/elastic/apm-agent-rum-js/blob/dc53188ec6e74eba76a69ed24e09930a576dd88f/packages/rum/src/index.d.ts#L151

Details - https://discuss.elastic.co/t/is-it-possible-to-obtain-user-centric-metrics-with-custom-transactions/267707?u=felix_roessel

**Comment by vigneshshanmugam** [comment]
@devcorpio Missed to add this to the other Issue.

**Comment by devcorpio** [comment]
@vigneshshanmugam in the SpanOptions type we should add blocking and parentId, right? 

In the [PR](https://github.com/elastic/apm-agent-rum-js/pull/875) I'm seeing that we added the parentId property too

**Comment by vigneshshanmugam** [comment]
@devcorpio Yes, We can expose parentId as well.
