### ISSUE TITLE
Missing Types for React integration

### ISSUE THREAD

**Issue by olidotjpeg** [elastic/apm-agent-rum-js#997]
Hey Elastic,

I am using this package in a project where we are rolling with TypeScript, however my build tool and IDE is complaining about missing declaration file(s).

Am I missing something or does this project have none?

```
Could not find a declaration file for module '@elastic/apm-rum-react'. 'pathToProject/node_modules/@elastic/apm-rum-react/dist/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/elastic__apm-rum-react` if it exists or add a new declaration (.d.ts) file containing `declare module '@elastic/apm-rum-react';`  TS7016
  ```
  
  I already tried the suggest `npm install` but it returns a 404
  
  Thanks

**Comment by ovflowd** [comment]
Hey folks 👋 it would be really nice to have this done! Or at least an answer from the maintainers/contributors of this project 😄

**Comment by jahtalab** [comment]
Hi @olidotjpeg and @ovflowd , 

Thanks for reporting the issue.

At the moment, the react integration doesn't provide any typings. The installation for the typings (in the error message) is an automatically generated suggestion and doesn't related to a specific repo but I agree it could be confusing to see that.

I will convert this issue to an enhancement request to provide typings for the react integration. However, the typings, most likely, will be provide in the same repo as the react integration so there would no need for a separate installation.

**Comment by jahtalab** [comment]
There's a separate issue for providing this so I'll close this one in favour of #624
