### ISSUE TITLE
Add session id and transaction number to transaction docs

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/apm-agent-rum-js#998]
Whilst working through the RUM Session implementation (https://github.com/elastic/apm-agent-rum-js/issues/634), we should at least add the session id to all transaction documents, so that we (and/or users) can manually report on the session data available (albeit likely with less than efficient queries).  Similarly, it should be possible to identify the order of the transactions from just the transaction documents themselves (whilst we don’t have anything for sessions).  This can also be used to compare the performance of first page hits to other pages.

ACs:
* Add the session id to transaction documents
* Add a transaction number identifier to transaction documents for that session
  * e.g. `transactionNumber=1` for the first transaction (index from `1` for the `first` as this is more human readable, for anyone running queries)
  * This will be related to the active session (e.g. if not browsing the site and the session has expired, the next page hit will generate a new session id, and the transaction number will be reset back to `1` again)
* The APM Server will need to be updated to ensure [these two new fields are indexed](https://github.com/elastic/apm-server/issues/5032)

**Comment by graphaelli** [comment]
> Add the session id to transaction documents

Definitely not span documents?

> Add a transaction number identifier to transaction documents for that session 

Suggestion: `transaction.sequence`

**Comment by jahtalab** [comment]
@graphaelli , session id will be added only to transaction docs.
