### ISSUE TITLE
How to get download bandwidth per second

### ISSUE THREAD

**Issue by RammusXu** [elastic/apm-agent-rum-js#999]
Hi, 

I'm trying to find out bytes/second metric on every clients. It helps us to know how much traffic we might need and what's client's networking environments.

I can't find this metric/information on existed RUM (js APM). I already know I can create customize transaction to do that, but it's kind of wasting client's bandwidth.

Thus, I'm curious on `how to measure client's download speed (byte/second)` if is possible. Or any other best practice way to do this. Thank you.

## Other Infomation
This all empty on all devices and browsers. Not sure if it correct.
```
span.http.response.transfer_size
span.http.response.decoded_body_size
span.http.response.encoded_body_size
```

**Comment by vigneshshanmugam** [comment]
@RammusXu Browsers expose the connection information of the device through the [Network Information](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation) API. 

Download speed is exposed through the [downlink](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/downlink) property and can be estimated accordingly.

We already have a PR to measure this information - PR #752. Hope this helps, Let us know if you need more information.

**Comment by RammusXu** [comment]
@vigneshshanmugam That's nice. Thank you!
